"""gen_reference_vectors.py - generate assets/reference_vectors.json from NumPy/SciPy/sklearn.

This is the SOTA validation harness for the recipe library: every numeric kernel that backs a
recipe is checked against the published reference implementation (scikit-learn for ML metrics,
SciPy for statistics and special functions, NumPy for quantiles/aggregates, the HumanEval paper
estimator for pass@k, the SQuAD eval script for normalized exact-match, Guo et al. 2017 for ECE).

Run it with a venv that has numpy, scipy, scikit-learn:
    /path/to/venv/bin/python gen_reference_vectors.py
The committed JSON is what scripts/tests/test_recipes_sota.py validates against - the test
suite itself stays pure stdlib, per the repo rule. Datasets are generated by a fixed-seed LCG
(never random.random), so re-running reproduces the identical file.
"""
import json
import os

import numpy as np
from scipy import stats, special
import sklearn.metrics as skm

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "assets", "reference_vectors.json")

CASES = []


def case(cid, kind, args, expected, atol=1e-12, rtol=1e-12):
    CASES.append({"id": cid, "kind": kind, "args": args, "expected": float(expected),
                  "atol": atol, "rtol": rtol})


# ---------------- deterministic data (64-bit LCG, 53-bit uniforms) ----------------

def uniforms(seed, n, lo=0.0, hi=1.0):
    state = seed & ((1 << 64) - 1)
    out = []
    for _ in range(n):
        state = (state * 6364136223846793005 + 1442695040888963407) % (1 << 64)
        out.append(lo + (hi - lo) * (state >> 11) / float(1 << 53))
    return out


# ============================ existing 15 recipes ============================

rets = uniforms(1, 252, -0.03, 0.035)
case("total_return", "total_return", {"rets": rets}, np.prod(1.0 + np.array(rets)) - 1.0, atol=1e-9, rtol=1e-9)
sr = np.mean(rets) / np.std(rets, ddof=1) * np.sqrt(252.0)
case("sharpe_252", "sharpe", {"rets": rets, "periods": 252}, sr, atol=1e-10)
eq = np.cumprod(1.0 + np.array(rets))
peaks = np.maximum.accumulate(eq)
case("max_drawdown", "max_drawdown", {"rets": rets}, float(np.min(eq / peaks - 1.0)), atol=1e-12)

target = uniforms(2, 300, -5.0, 10.0)
noise = uniforms(3, 300, -1.0, 1.0)
pred = [t + e for t, e in zip(target, noise)]
case("rmse", "rmse", {"pred": pred, "actual": target},
     np.sqrt(skm.mean_squared_error(target, pred)), atol=1e-11)
case("mae", "mae", {"pred": pred, "actual": target}, skm.mean_absolute_error(target, pred), atol=1e-11)
case("r2", "r2", {"pred": pred, "actual": target}, skm.r2_score(target, pred), atol=1e-11)

u1 = uniforms(4, 400)
u2 = uniforms(5, 400)
labels = [1 if u < 0.4 else 0 for u in u1]
scores = [round(0.55 * y + 0.45 * u, 2) for y, u in zip(labels, u2)]  # 2dp -> deliberate ties
probs = [min(max(0.62 * y + 0.38 * u, 0.02), 0.98) for y, u in zip(labels, u2)]
hard = [1 if s > 0.5 else 0 for s in scores]
case("accuracy", "accuracy", {"preds": hard, "labels": labels}, skm.accuracy_score(labels, hard))
case("precision", "precision", {"preds": hard, "labels": labels}, skm.precision_score(labels, hard))
case("recall", "recall", {"preds": hard, "labels": labels}, skm.recall_score(labels, hard))
case("f1", "f1", {"preds": hard, "labels": labels}, skm.f1_score(labels, hard))
case("auc_ties", "auc", {"scores": scores, "labels": labels}, skm.roc_auc_score(labels, scores), atol=1e-11)
case("brier", "brier", {"probs": probs, "labels": labels}, skm.brier_score_loss(labels, probs), atol=1e-12)

vals = uniforms(7, 250, 10.0, 500.0)
case("column_sum", "column_sum", {"xs": vals}, np.sum(np.array(vals)), atol=1e-8)
case("column_mean", "column_mean", {"xs": vals}, np.mean(np.array(vals)), atol=1e-10)

# ============================ Pack 1 - engineering ============================

for q in (0.25, 0.5, 0.9, 0.95, 0.99):
    case("quantile_%g" % q, "quantile", {"xs": vals, "q": q}, np.quantile(np.array(vals), q), atol=1e-10)
small = [4.0, 1.0, 3.0, 2.0]
case("quantile_small_p75", "quantile", {"xs": small, "q": 0.75}, np.quantile(np.array(small), 0.75))
case("quantile_n1", "quantile", {"xs": [42.0], "q": 0.9}, 42.0)

before = uniforms(8, 60, 80.0, 120.0)
after = uniforms(9, 75, 30.0, 50.0)
case("speedup_mean", "speedup", {"before": before, "after": after, "mode": "mean"},
     np.mean(before) / np.mean(after), atol=1e-12)
case("speedup_median", "speedup", {"before": before, "after": after, "mode": "median"},
     np.quantile(np.array(before), 0.5) / np.quantile(np.array(after), 0.5), atol=1e-12)

lat = uniforms(10, 500, 5.0, 900.0)
for q, name in ((0.5, "p50"), (0.95, "p95"), (0.99, "p99")):
    case("latency_%s" % name, "quantile", {"xs": lat, "q": q}, np.quantile(np.array(lat), q), atol=1e-10)
case("throughput", "throughput", {"durs": lat}, len(lat) / np.sum(np.array(lat)), atol=1e-13)
case("peak_memory", "peak", {"xs": lat}, np.max(np.array(lat)))

hits = [int(u * 6) if v > 0.3 else 0 for u, v in zip(uniforms(11, 320), uniforms(12, 320))]
case("test_coverage", "coverage", {"hits": [float(h) for h in hits]},
     np.count_nonzero(np.array(hits) > 0) / len(hits))
flags = [1.0 if u < 0.07 else 0.0 for u in uniforms(13, 600)]
case("error_rate_flag", "error_rate", {"flags": flags, "mode": "flag"}, np.mean(np.array(flags)))
codes = [float([200, 201, 301, 404, 500, 503][int(u * 6)]) for u in uniforms(14, 600)]
case("error_rate_4xx", "error_rate", {"flags": codes, "mode": "http4xx"},
     np.count_nonzero(np.array(codes) >= 400) / len(codes))
case("error_rate_5xx", "error_rate", {"flags": codes, "mode": "http5xx"},
     np.count_nonzero(np.array(codes) >= 500) / len(codes))

# ============================ Pack 2 - analytics ============================

case("column_median", "quantile", {"xs": vals, "q": 0.5}, np.median(np.array(vals)), atol=1e-10)

raw_ids = []
for i, u in enumerate(uniforms(15, 240)):
    if u < 0.06:
        raw_ids.append(["", "NaN", "null", "None", "NA"][i % 5])
    else:
        raw_ids.append("id-%03d" % int(u * 90))
nonnull = [s for s in raw_ids if s.strip().lower() not in ("", "nan", "na", "null", "none")]
case("null_fraction", "null_fraction", {"raw": raw_ids}, (len(raw_ids) - len(nonnull)) / len(raw_ids))
case("distinct_count", "distinct_count", {"raw": raw_ids, "include_null": False},
     float(len(set(nonnull))))
case("duplicate_count", "duplicate_count", {"raw": raw_ids},
     float(len(raw_ids) - len(set(s.strip() for s in raw_ids))))

series = uniforms(16, 24, 1000.0, 5000.0)
case("growth_period", "growth_rate", {"xs": series, "mode": "period"}, series[-1] / series[-2] - 1.0)
case("growth_total", "growth_rate", {"xs": series, "mode": "total"}, series[-1] / series[0] - 1.0)

share_flags = [1.0 if u < 0.42 else 0.0 for u in uniforms(17, 800)]
case("ratio_share", "ratio_share", {"flags": share_flags}, np.mean(np.array(share_flags)))

regions = [["West", "East", "North", "South"][int(u * 4)] for u in uniforms(18, 300)]
amounts = uniforms(19, 300, 50.0, 2000.0)
west = [a for r, a in zip(regions, amounts) if r == "West"]
east = [a for r, a in zip(regions, amounts) if r == "East"]
case("groupby_sum_west", "groupby", {"groups": regions, "values": amounts, "agg": "sum", "label": "West"},
     np.sum(np.array(west)), atol=1e-9)
case("groupby_mean_east", "groupby", {"groups": regions, "values": amounts, "agg": "mean", "label": "East"},
     np.mean(np.array(east)), atol=1e-10)

# ============================ Pack 3 - ML & RAG evals ============================

# retrieval corpus: 25 queries, 8-20 ranked docs each, binary + graded relevance
queries, ranks, rels_bin, rels_grad = [], [], [], []
for qi in range(25):
    depth = 8 + int(uniforms(100 + qi, 1)[0] * 13)
    us = uniforms(200 + qi, depth)
    for r in range(1, depth + 1):
        queries.append("q%02d" % qi)
        ranks.append(float(r))
        rels_bin.append(1.0 if us[r - 1] < 0.25 else 0.0)
        rels_grad.append(float(int(us[r - 1] * 4)))  # graded 0..3


def ref_recall_at_k(k):
    per, out = {}, []
    for q, r, rel in zip(queries, ranks, rels_bin):
        per.setdefault(q, []).append((r, rel))
    for q in per:
        rows = sorted(per[q])
        tot = sum(1 for _, rel in rows if rel > 0)
        if tot:
            out.append(sum(1 for _, rel in rows[:k] if rel > 0) / tot)
    return float(np.mean(out))


def ref_ndcg_at_k(k, rel_list, exp_gain):
    per, out = {}, []
    for q, r, rel in zip(queries, ranks, rel_list):
        per.setdefault(q, []).append((r, rel))
    for q in per:
        rows = sorted(per[q])
        rel_arr = np.array([rel for _, rel in rows])[None, :]
        score_arr = -np.array([r for r, _ in rows])[None, :]
        if exp_gain:
            g = np.power(2.0, np.array([rel for _, rel in rows])) - 1.0
            disc = 1.0 / np.log2(np.arange(2, len(rows) + 2))
            dcg = float(np.sum((g * disc)[:k]))
            ideal = np.sort(g)[::-1]
            idcg = float(np.sum((ideal * disc)[:k]))
            if idcg > 0:
                out.append(dcg / idcg)
        else:
            if np.sum(rel_arr) > 0:
                out.append(float(skm.ndcg_score(rel_arr, score_arr, k=k)))
    return float(np.mean(out))


def ref_mrr(k=None):
    per, out = {}, []
    for q, r, rel in zip(queries, ranks, rels_bin):
        per.setdefault(q, []).append((r, rel))
    for q in per:
        rows = sorted(per[q])
        rows = rows if k is None else rows[:k]
        rr = 0.0
        for pos, (_, rel) in enumerate(rows, 1):
            if rel > 0:
                rr = 1.0 / pos
                break
        out.append(rr)
    return float(np.mean(out))


def ref_hit_at_k(k):
    per = {}
    for q, r, rel in zip(queries, ranks, rels_bin):
        per.setdefault(q, []).append((r, rel))
    hit = sum(1 for q in per if any(rel > 0 for _, rel in sorted(per[q])[:k]))
    return hit / len(per)


RETR = {"queries": queries, "ranks": ranks, "rels": rels_bin}
RETR_G = {"queries": queries, "ranks": ranks, "rels": rels_grad}
case("recall_at_5", "recall_at_k", dict(RETR, k=5), ref_recall_at_k(5), atol=1e-12)
case("recall_at_10", "recall_at_k", dict(RETR, k=10), ref_recall_at_k(10), atol=1e-12)
case("ndcg_at_10_linear", "ndcg_at_k", dict(RETR_G, k=10, gain="linear"),
     ref_ndcg_at_k(10, rels_grad, False), atol=1e-10)
case("ndcg_at_10_exp", "ndcg_at_k", dict(RETR_G, k=10, gain="exp"),
     ref_ndcg_at_k(10, rels_grad, True), atol=1e-10)
case("ndcg_at_5_linear_bin", "ndcg_at_k", dict(RETR, k=5, gain="linear"),
     ref_ndcg_at_k(5, rels_bin, False), atol=1e-10)
case("mrr", "mrr", dict(RETR, k=None), ref_mrr(), atol=1e-12)
case("mrr_at_10", "mrr", dict(RETR, k=10), ref_mrr(10), atol=1e-12)
case("hit_at_5", "hit_at_k", dict(RETR, k=5), ref_hit_at_k(5))

# pass@k (HumanEval unbiased estimator, Chen et al. 2021)
problems, corrects = [], []
ccounts = [0, 1, 2, 3, 5, 7, 10, 4, 0, 10, 6, 8]
for pi, c in enumerate(ccounts):
    for s in range(10):
        problems.append("prob%02d" % pi)
        corrects.append(1.0 if s < c else 0.0)


def ref_pass_at_k(n, c, k):
    if n - c < k:
        return 1.0
    return 1.0 - np.prod(1.0 - k / np.arange(n - c + 1, n + 1))


for k in (1, 5, 10):
    exp = float(np.mean([ref_pass_at_k(10, c, k) for c in ccounts]))
    case("pass_at_%d" % k, "pass_at_k", {"problems": problems, "corrects": corrects, "k": k},
         exp, atol=1e-12)

# multiclass
mc_labels = [int(u * 4) for u in uniforms(30, 500)]
mc_preds = [y if v < 0.7 else int(w * 4) for y, v, w in zip(mc_labels, uniforms(31, 500), uniforms(32, 500))]
case("macro_f1", "macro_f1", {"preds": [float(p) for p in mc_preds], "labels": [float(y) for y in mc_labels]},
     skm.f1_score(mc_labels, mc_preds, average="macro", zero_division=0), atol=1e-12)
case("micro_f1", "micro_f1", {"preds": [float(p) for p in mc_preds], "labels": [float(y) for y in mc_labels]},
     skm.f1_score(mc_labels, mc_preds, average="micro", zero_division=0), atol=1e-12)
case("mcc_multiclass", "mcc", {"preds": [float(p) for p in mc_preds], "labels": [float(y) for y in mc_labels]},
     skm.matthews_corrcoef(mc_labels, mc_preds), atol=1e-12)
case("mcc_binary", "mcc", {"preds": [float(p) for p in hard], "labels": [float(y) for y in labels]},
     skm.matthews_corrcoef(labels, hard), atol=1e-12)
# a class present in labels but never predicted (zero_division=0 path)
zd_labels = [0.0, 1.0, 2.0, 2.0, 1.0, 0.0, 2.0, 1.0]
zd_preds = [0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0]
case("macro_f1_zero_division", "macro_f1", {"preds": zd_preds, "labels": zd_labels},
     skm.f1_score([int(x) for x in zd_labels], [int(x) for x in zd_preds], average="macro", zero_division=0))

case("pr_auc_ap", "average_precision", {"scores": scores, "labels": labels},
     skm.average_precision_score(labels, scores), atol=1e-11)
case("log_loss", "log_loss", {"probs": probs, "labels": labels, "clip": False},
     skm.log_loss(labels, probs), atol=1e-12, rtol=1e-12)


def ref_ece(p, y, bins):
    p, y = np.array(p), np.array(y)
    idx = np.clip(np.ceil(p * bins).astype(int) - 1, 0, bins - 1)
    total = 0.0
    for b in range(bins):
        m = idx == b
        if m.any():
            total += abs(y[m].mean() - p[m].mean()) * m.sum() / len(p)
    return total


case("ece_15", "ece", {"probs": probs, "labels": labels, "bins": 15}, ref_ece(probs, labels, 15), atol=1e-12)
case("ece_10", "ece", {"probs": probs, "labels": labels, "bins": 10}, ref_ece(probs, labels, 10), atol=1e-12)

# ============================ Pack 4 - statistical claims ============================

sa = uniforms(20, 40, 9.5, 11.0)
sb = uniforms(21, 55, 10.0, 12.0)
case("p_welch", "t_test_p", {"a": sa, "b": sb, "mode": "welch"},
     stats.ttest_ind(sa, sb, equal_var=False).pvalue, atol=1e-13, rtol=1e-11)
case("p_pooled", "t_test_p", {"a": sa, "b": sb, "mode": "pooled"},
     stats.ttest_ind(sa, sb, equal_var=True).pvalue, atol=1e-13, rtol=1e-11)
zstat = (np.mean(sa) - np.mean(sb)) / np.sqrt(np.var(sa, ddof=1) / len(sa) + np.var(sb, ddof=1) / len(sb))
case("p_z", "t_test_p", {"a": sa, "b": sb, "mode": "z"},
     2.0 * stats.norm.sf(abs(zstat)), atol=1e-13, rtol=1e-11)
# a close pair (p ~ large) so both tails are exercised
sc = uniforms(22, 35, 10.0, 12.0)
case("p_welch_null", "t_test_p", {"a": sc, "b": sb, "mode": "welch"},
     stats.ttest_ind(sc, sb, equal_var=False).pvalue, atol=1e-13, rtol=1e-11)

for level, dist in ((0.95, "t"), (0.99, "t"), (0.95, "z")):
    crit = stats.t.ppf(1 - (1 - level) / 2, len(sa) - 1) if dist == "t" else stats.norm.ppf(1 - (1 - level) / 2)
    exp = crit * np.std(sa, ddof=1) / np.sqrt(len(sa))
    case("ci_%s%d" % (dist, level * 100), "ci_half_width",
         {"xs": sa, "level": level, "dist": dist}, exp, atol=1e-12, rtol=1e-10)

conv_a = [1.0 if u < 0.10 else 0.0 for u in uniforms(23, 1000)]
conv_b = [1.0 if u < 0.123 else 0.0 for u in uniforms(24, 1100)]
case("lift_rel", "lift", {"a": conv_a, "b": conv_b, "mode": "relative"},
     (np.mean(conv_b) - np.mean(conv_a)) / np.mean(conv_a), atol=1e-12)
case("lift_abs", "lift", {"a": conv_a, "b": conv_b, "mode": "absolute"},
     np.mean(conv_b) - np.mean(conv_a), atol=1e-14)

# chi-square from raw (group, outcome) pairs - 2x2 (Yates on/off) and 3x3 (df>1)
g2 = [["ctrl", "treat"][int(u * 2)] for u in uniforms(25, 500)]
o2 = [("yes" if v < (0.30 if g == "ctrl" else 0.38) else "no") for g, v in zip(g2, uniforms(26, 500))]


def contingency(gs, os_):
    rows, cols_ = sorted(set(gs)), sorted(set(os_))
    return np.array([[sum(1 for g, o in zip(gs, os_) if g == r and o == c) for c in cols_] for r in rows])


t2 = contingency(g2, o2)
r_yes = stats.chi2_contingency(t2, correction=True)
r_no = stats.chi2_contingency(t2, correction=False)
case("chi2_2x2_p_yates", "chi_square", {"groups": g2, "outcomes": o2, "yates": True, "output": "p"},
     r_yes.pvalue, atol=1e-13, rtol=1e-11)
case("chi2_2x2_stat_yates", "chi_square", {"groups": g2, "outcomes": o2, "yates": True, "output": "statistic"},
     r_yes.statistic, atol=1e-11)
case("chi2_2x2_p_noyates", "chi_square", {"groups": g2, "outcomes": o2, "yates": False, "output": "p"},
     r_no.pvalue, atol=1e-13, rtol=1e-11)
g3 = [["a", "b", "c"][int(u * 3)] for u in uniforms(27, 700)]
o3 = [["x", "y", "z"][int((u + v) * 3) % 3] for u, v in zip(uniforms(28, 700), uniforms(29, 700))]
t3 = contingency(g3, o3)
r3 = stats.chi2_contingency(t3, correction=True)  # df>1 -> correction is a no-op (scipy)
case("chi2_3x3_p", "chi_square", {"groups": g3, "outcomes": o3, "yates": True, "output": "p"},
     r3.pvalue, atol=1e-13, rtol=1e-11)
case("chi2_3x3_stat", "chi_square", {"groups": g3, "outcomes": o3, "yates": True, "output": "statistic"},
     r3.statistic, atol=1e-10)

cx = [round(v, 1) for v in uniforms(33, 80, 0.0, 30.0)]   # 1dp -> ties for the midrank path
cy = [x * 0.7 + e for x, e in zip(cx, uniforms(34, 80, -4.0, 4.0))]
case("pearson", "correlation", {"xs": cx, "ys": cy, "mode": "pearson"},
     stats.pearsonr(cx, cy).statistic, atol=1e-13)
case("spearman_ties", "correlation", {"xs": cx, "ys": cy, "mode": "spearman"},
     stats.spearmanr(cx, cy).statistic, atol=1e-13)

na, nb = len(sa), len(sb)
df = na + nb - 2
sp = np.sqrt(((na - 1) * np.var(sa, ddof=1) + (nb - 1) * np.var(sb, ddof=1)) / df)
d = (np.mean(sa) - np.mean(sb)) / sp
case("cohen_d", "cohen_d", {"a": sa, "b": sb, "mode": "cohen_d"}, d, atol=1e-13)
jexact = special.gamma(df / 2.0) / (np.sqrt(df / 2.0) * special.gamma((df - 1) / 2.0))
case("hedges_g", "cohen_d", {"a": sa, "b": sb, "mode": "hedges_g"}, d * jexact, atol=1e-12)
case("glass_delta", "cohen_d", {"a": sa, "b": sb, "mode": "glass_delta"},
     (np.mean(sa) - np.mean(sb)) / np.std(sb, ddof=1), atol=1e-13)

# ============================ Pack 5 - business & finance ============================

import numpy_financial as npf  # noqa: E402

monthly = []
v = 100000.0
for u in uniforms(40, 36, -0.02, 0.045):
    v *= (1.0 + u)
    monthly.append(v)
years = (len(monthly) - 1) / 12.0
case("cagr_monthly", "cagr", {"xs": monthly, "ppy": 12.0},
     (monthly[-1] / monthly[0]) ** (1.0 / years) - 1.0, atol=1e-13)
annual = monthly[::12]
case("cagr_annual", "cagr", {"xs": annual, "ppy": 1.0},
     (annual[-1] / annual[0]) ** (1.0 / (len(annual) - 1)) - 1.0, atol=1e-13)

cfs = [-2500.0] + uniforms(41, 8, 200.0, 700.0)
case("npv_8pct", "npv", {"cashflows": cfs, "rate": 0.08}, npf.npv(0.08, cfs), atol=1e-9)
case("npv_0pct", "npv", {"cashflows": cfs, "rate": 0.0}, np.sum(np.array(cfs)), atol=1e-10)
case("irr", "irr", {"cashflows": cfs}, npf.irr(cfs), atol=1e-10)
cfs2 = [-1000.0, 400.0, 400.0, 400.0]
case("irr_simple", "irr", {"cashflows": cfs2}, npf.irr(cfs2), atol=1e-10)

churn_flags = [1.0 if u < 0.031 else 0.0 for u in uniforms(42, 900)]
case("churn", "churn_rate", {"flags": churn_flags, "mode": "churn"}, np.mean(np.array(churn_flags)))
case("retention", "churn_rate", {"flags": churn_flags, "mode": "retention"},
     1.0 - np.mean(np.array(churn_flags)))

rev = uniforms(43, 150, 100.0, 900.0)
cost = [r * u for r, u in zip(rev, uniforms(44, 150, 0.3, 0.6))]
case("margin_pct", "margin_pct", {"revenue": rev, "cost": cost},
     (np.sum(np.array(rev)) - np.sum(np.array(cost))) / np.sum(np.array(rev)), atol=1e-12)

ledger_b = uniforms(45, 220, 10.0, 400.0)
ledger_a = list(ledger_b)
ledger_a[17] += 12.5   # a deliberate 12.5 mismatch
case("reconciliation_diff", "reconciliation", {"a": ledger_a, "b": ledger_b}, 12.5, atol=1e-9)

# ============================ Pack 6 - forecasting ============================

f_actual = uniforms(46, 120, 50.0, 250.0)
f_pred = [a + e for a, e in zip(f_actual, uniforms(47, 120, -12.0, 12.0))]
case("mape", "mape", {"pred": f_pred, "actual": f_actual, "symmetric": False},
     skm.mean_absolute_percentage_error(f_actual, f_pred), atol=1e-13)
smape_ref = float(np.mean(2.0 * np.abs(np.array(f_pred) - np.array(f_actual))
                          / (np.abs(np.array(f_pred)) + np.abs(np.array(f_actual)))))
case("smape", "mape", {"pred": f_pred, "actual": f_actual, "symmetric": True}, smape_ref, atol=1e-13)


def ref_mase(pred, actual, m):
    a = np.array(actual)
    scale = np.mean(np.abs(a[m:] - a[:-m]))
    return float(np.mean(np.abs(np.array(pred) - a)) / scale)


case("mase_m1", "mase", {"pred": f_pred, "actual": f_actual, "m": 1}, ref_mase(f_pred, f_actual, 1),
     atol=1e-13)
case("mase_m12", "mase", {"pred": f_pred, "actual": f_actual, "m": 12}, ref_mase(f_pred, f_actual, 12),
     atol=1e-13)
for q in (0.1, 0.5, 0.9):
    case("pinball_q%g" % q, "pinball", {"pred": f_pred, "actual": f_actual, "q": q},
         skm.mean_pinball_loss(f_actual, f_pred, alpha=q), atol=1e-13)

# ============================ Pack 7 - quant risk & relative performance ============================

r = np.array(rets)
case("volatility", "volatility", {"rets": rets, "periods": 252},
     np.std(r, ddof=1) * np.sqrt(252.0), atol=1e-12)
dd2 = float(np.mean(np.minimum(r, 0.0) ** 2))
case("downside_dev", "downside_deviation", {"rets": rets, "periods": 252},
     np.sqrt(dd2) * np.sqrt(252.0), atol=1e-12)
case("sortino", "sortino", {"rets": rets, "periods": 252},
     np.mean(r) / np.sqrt(dd2) * np.sqrt(252.0), atol=1e-10)
eqc = np.cumprod(1.0 + r)
mdd_ref = float(np.min(eqc / np.maximum.accumulate(eqc) - 1.0))
ann_ref = float(np.prod(1.0 + r) ** (252.0 / len(r)) - 1.0)
case("calmar", "calmar", {"rets": rets, "periods": 252}, ann_ref / abs(mdd_ref), atol=1e-10)
case("var_95", "value_at_risk", {"rets": rets, "level": 0.95},
     -np.quantile(r, 0.05), atol=1e-12)
case("var_99", "value_at_risk", {"rets": rets, "level": 0.99},
     -np.quantile(r, 0.01), atol=1e-12)
tail = r[r <= np.quantile(r, 0.05)]
case("cvar_95", "cvar", {"rets": rets, "level": 0.95}, -np.mean(tail), atol=1e-13)
case("win_rate", "win_rate", {"rets": rets}, np.count_nonzero(r > 0) / len(r))
case("profit_factor", "profit_factor", {"rets": rets},
     np.sum(r[r > 0]) / -np.sum(r[r < 0]), atol=1e-12)
case("omega_0", "omega_ratio", {"rets": rets, "threshold": 0.0},
     np.sum(np.maximum(r, 0)) / np.sum(np.maximum(-r, 0)), atol=1e-12)
case("omega_001", "omega_ratio", {"rets": rets, "threshold": 0.001},
     np.sum(np.maximum(r - 0.001, 0)) / np.sum(np.maximum(0.001 - r, 0)), atol=1e-12)

bench = [0.6 * x + e for x, e in zip(rets, uniforms(50, 252, -0.012, 0.014))]
bv = np.array(bench)
beta_ref = float(np.cov(r, bv, ddof=1)[0, 1] / np.var(bv, ddof=1))
case("beta", "beta", {"rets": rets, "bench": bench}, beta_ref, atol=1e-12)
case("alpha", "alpha", {"rets": rets, "bench": bench, "periods": 252},
     (np.mean(r) - beta_ref * np.mean(bv)) * 252.0, atol=1e-11)
act = r - bv
case("tracking_error", "tracking_error", {"rets": rets, "bench": bench, "periods": 252},
     np.std(act, ddof=1) * np.sqrt(252.0), atol=1e-12)
case("information_ratio", "information_ratio", {"rets": rets, "bench": bench, "periods": 252},
     np.mean(act) / np.std(act, ddof=1) * np.sqrt(252.0), atol=1e-10)

# ============================ Pack 8 - classification & regression depth II ============================

case("balanced_accuracy", "balanced_accuracy", {"preds": hard, "labels": labels},
     skm.balanced_accuracy_score(labels, hard), atol=1e-12)
case("balanced_accuracy_mc", "balanced_accuracy",
     {"preds": [float(p) for p in mc_preds], "labels": [float(y) for y in mc_labels]},
     skm.balanced_accuracy_score(mc_labels, mc_preds), atol=1e-12)
case("cohen_kappa_mc", "cohen_kappa",
     {"preds": [float(p) for p in mc_preds], "labels": [float(y) for y in mc_labels]},
     skm.cohen_kappa_score(mc_labels, mc_preds), atol=1e-12)
tn_ = sum(1 for p, y in zip(hard, labels) if p == 0 and y == 0)
fp_ = sum(1 for p, y in zip(hard, labels) if p == 1 and y == 0)
case("specificity", "specificity", {"preds": hard, "labels": labels}, tn_ / (tn_ + fp_))
case("fbeta_2", "fbeta", {"preds": hard, "labels": labels, "beta": 2.0},
     skm.fbeta_score(labels, hard, beta=2.0), atol=1e-12)
case("fbeta_05", "fbeta", {"preds": hard, "labels": labels, "beta": 0.5},
     skm.fbeta_score(labels, hard, beta=0.5), atol=1e-12)
case("jaccard", "jaccard", {"preds": hard, "labels": labels},
     skm.jaccard_score(labels, hard), atol=1e-12)
case("weighted_f1", "weighted_f1",
     {"preds": [float(p) for p in mc_preds], "labels": [float(y) for y in mc_labels]},
     skm.f1_score(mc_labels, mc_preds, average="weighted", zero_division=0), atol=1e-12)
pos_scores = [s for s, y in zip(scores, labels) if y == 1]
neg_scores = [s for s, y in zip(scores, labels) if y == 0]
case("ks_statistic", "ks_statistic", {"scores": scores, "labels": labels},
     stats.ks_2samp(pos_scores, neg_scores).statistic, atol=1e-12)
case("gini_norm", "gini_norm", {"scores": scores, "labels": labels},
     2.0 * skm.roc_auc_score(labels, scores) - 1.0, atol=1e-11)

m_actual = uniforms(51, 200, 5.0, 300.0)
m_pred = [a * (1.0 + e) for a, e in zip(m_actual, uniforms(52, 200, -0.25, 0.25))]
case("msle", "msle", {"pred": m_pred, "actual": m_actual, "root": False},
     skm.mean_squared_log_error(m_actual, m_pred), atol=1e-12)
case("rmsle", "msle", {"pred": m_pred, "actual": m_actual, "root": True},
     np.sqrt(skm.mean_squared_log_error(m_actual, m_pred)), atol=1e-12)
case("medae", "medae", {"pred": pred, "actual": target},
     skm.median_absolute_error(target, pred), atol=1e-12)
case("max_error", "max_error", {"pred": pred, "actual": target},
     skm.max_error(target, pred), atol=1e-12)
case("explained_variance", "explained_variance", {"pred": pred, "actual": target},
     skm.explained_variance_score(target, pred), atol=1e-12)
case("wape", "wape", {"pred": f_pred, "actual": f_actual},
     np.sum(np.abs(np.array(f_pred) - np.array(f_actual))) / np.sum(np.abs(np.array(f_actual))),
     atol=1e-13)
case("forecast_bias", "forecast_bias", {"pred": f_pred, "actual": f_actual},
     (np.sum(f_pred) - np.sum(f_actual)) / np.sum(f_actual), atol=1e-13)
r2_ref = skm.r2_score(target, pred)
n_r = len(target)
case("adjusted_r2_p8", "adjusted_r2", {"pred": pred, "actual": target, "p": 8},
     1.0 - (1.0 - r2_ref) * (n_r - 1) / (n_r - 8 - 1), atol=1e-12)
rmse_ref = np.sqrt(skm.mean_squared_error(target, pred))
case("nrmse_mean", "nrmse", {"pred": pred, "actual": target, "mode": "mean"},
     rmse_ref / np.mean(target), atol=1e-12)
case("nrmse_range", "nrmse", {"pred": pred, "actual": target, "mode": "range"},
     rmse_ref / (np.max(target) - np.min(target)), atol=1e-12)
from statsmodels.stats.stattools import durbin_watson as sm_dw  # noqa: E402
resid = np.array(target) - np.array(pred)
case("durbin_watson", "durbin_watson", {"pred": pred, "actual": target},
     sm_dw(resid), atol=1e-12)

# ============================ Pack 9 - analytics & engineering depth II ============================

case("column_min", "column_min", {"xs": vals}, np.min(np.array(vals)))
case("column_max", "column_max", {"xs": vals}, np.max(np.array(vals)))
case("column_std", "column_std", {"xs": vals, "ddof": 1}, np.std(np.array(vals), ddof=1), atol=1e-11)
case("column_std_ddof0", "column_std", {"xs": vals, "ddof": 0}, np.std(np.array(vals)), atol=1e-11)
case("iqr", "iqr", {"xs": vals}, stats.iqr(np.array(vals)), atol=1e-10)
q1_, q3_ = np.quantile(np.array(vals), [0.25, 0.75])
fence = 1.5 * (q3_ - q1_)
case("outlier_count", "outlier_count", {"xs": vals, "k": 1.5},
     float(np.count_nonzero((np.array(vals) < q1_ - fence) | (np.array(vals) > q3_ + fence))))
id_counts = {}
for s_ in raw_ids:
    id_counts[s_.strip()] = id_counts.get(s_.strip(), 0) + 1
case("mode_share", "mode_share", {"raw": raw_ids}, max(id_counts.values()) / len(raw_ids))
amounts_arr = np.sort(np.array(amounts))
n_a = len(amounts_arr)
gini_ref = float(np.sum((2 * np.arange(1, n_a + 1) - n_a - 1) * amounts_arr) / (n_a * np.sum(amounts_arr)))
case("gini_coefficient", "gini_coefficient", {"xs": amounts}, gini_ref, atol=1e-12)
shares = np.array(amounts) / np.sum(amounts)
case("hhi", "hhi", {"xs": amounts}, float(np.sum(shares ** 2)), atol=1e-13)
case("entropy_bits", "entropy", {"raw": raw_ids, "base": "bits"},
     stats.entropy(list(id_counts.values()), base=2), atol=1e-12)
case("entropy_nats", "entropy", {"raw": raw_ids, "base": "nats"},
     stats.entropy(list(id_counts.values())), atol=1e-12)

case("latency_p90", "quantile", {"xs": lat, "q": 0.90}, np.quantile(np.array(lat), 0.90), atol=1e-10)
lat_arr = np.array(lat)
t_ap = 120.0
apdex_ref = (np.count_nonzero(lat_arr <= t_ap) + np.count_nonzero((lat_arr > t_ap) & (lat_arr <= 4 * t_ap)) / 2.0) / len(lat_arr)
case("apdex_t120", "apdex", {"durs": lat, "t": t_ap}, apdex_ref)
up_flags = [0.0 if u < 0.0008 else 1.0 for u in uniforms(53, 5000)]
case("uptime", "ratio_share", {"flags": up_flags}, np.mean(np.array(up_flags)))

# ============================ Pack 10 - statistical tests II ============================

ta = [round(v, 1) for v in sa]   # 1dp -> ties, forcing the tie-corrected asymptotic path
tb = [round(v, 1) for v in sb]
case("mann_whitney_p", "mann_whitney_p", {"a": ta, "b": tb},
     stats.mannwhitneyu(ta, tb, alternative="two-sided", method="asymptotic").pvalue,
     atol=1e-12, rtol=1e-10)
# the classical Kolmogorov asymptotic (kstwobign): the textbook two-sample formula;
# scipy's method='asymp' switched to the finite-n kstwo refinement in 1.5+, so the
# recipe documents and validates the classical limit explicitly
ks_d_ref = stats.ks_2samp(sa, sb).statistic
en_ref = np.sqrt(len(sa) * len(sb) / (len(sa) + len(sb)))
case("ks_p", "ks_p", {"a": sa, "b": sb}, stats.kstwobign.sf(en_ref * ks_d_ref),
     atol=1e-12, rtol=1e-9)
buckets_ref = {}
for g_, v_ in zip(regions, amounts):
    buckets_ref.setdefault(g_, []).append(v_)
f_res = stats.f_oneway(*buckets_ref.values())
case("anova_p", "anova", {"groups": regions, "values": amounts, "output": "p"},
     f_res.pvalue, atol=1e-13, rtol=1e-10)
case("anova_f", "anova", {"groups": regions, "values": amounts, "output": "statistic"},
     f_res.statistic, atol=1e-10)
from statsmodels.stats.proportion import proportions_ztest  # noqa: E402
x1 = sum(1 for v in conv_a if v != 0)
x2 = sum(1 for v in conv_b if v != 0)
_, pz = proportions_ztest([x1, x2], [len(conv_a), len(conv_b)])
case("proportion_z_p", "proportion_z_p", {"a": conv_a, "b": conv_b}, pz, atol=1e-13, rtol=1e-10)
fe_or, fe_p = stats.fisher_exact(t2)
case("fisher_exact_p", "fisher_exact_p", {"groups": g2, "outcomes": o2}, fe_p,
     atol=1e-12, rtol=1e-9)
case("odds_ratio", "odds_ratio_2x2", {"groups": g2, "outcomes": o2, "haldane": False},
     fe_or, atol=1e-12)
rr_ref = (t2[0][0] / (t2[0][0] + t2[0][1])) / (t2[1][0] / (t2[1][0] + t2[1][1]))
case("relative_risk", "relative_risk_2x2", {"groups": g2, "outcomes": o2}, rr_ref, atol=1e-12)
chi2_nc = stats.chi2_contingency(t2, correction=False).statistic
case("cramers_v_2x2", "cramers_v", {"groups": g2, "outcomes": o2},
     np.sqrt(chi2_nc / (len(g2) * 1)), atol=1e-11)
chi3_nc = stats.chi2_contingency(t3, correction=False).statistic
case("cramers_v_3x3", "cramers_v", {"groups": g3, "outcomes": o3},
     np.sqrt(chi3_nc / (len(g3) * 2)), atol=1e-11)
case("skewness", "skewness", {"xs": rets}, stats.skew(np.array(rets)), atol=1e-12)
case("kurtosis", "kurtosis", {"xs": rets}, stats.kurtosis(np.array(rets)), atol=1e-12)
jb_res = stats.jarque_bera(np.array(rets))
case("jarque_bera_p", "jarque_bera", {"xs": rets, "output": "p"}, jb_res.pvalue,
     atol=1e-13, rtol=1e-9)
case("jarque_bera_stat", "jarque_bera", {"xs": rets, "output": "statistic"},
     jb_res.statistic, atol=1e-10)
from statsmodels.tsa.stattools import acf as sm_acf  # noqa: E402
acf_ref = sm_acf(np.array(f_actual), nlags=3, adjusted=False, fft=False)
case("acf_lag1", "autocorrelation", {"xs": f_actual, "lag": 1}, acf_ref[1], atol=1e-12)
case("acf_lag3", "autocorrelation", {"xs": f_actual, "lag": 3}, acf_ref[3], atol=1e-12)

# ============================ Pack 11 - retrieval / LLM evals II ============================


def ref_precision_at_k(k):
    per = {}
    for q, rk, rel in zip(queries, ranks, rels_bin):
        per.setdefault(q, []).append((rk, rel))
    return float(np.mean([sum(1 for _, rel in sorted(rows)[:k] if rel > 0) / k
                          for rows in per.values()]))


def ref_map_at_k(k):
    per, out = {}, []
    for q, rk, rel in zip(queries, ranks, rels_bin):
        per.setdefault(q, []).append((rk, rel))
    for rows in per.values():
        rows = sorted(rows)
        total_rel = sum(1 for _, rel in rows if rel > 0)
        if total_rel == 0:
            continue
        hits, terms = 0, []
        for i, (_, rel) in enumerate(rows[:k], 1):
            if rel > 0:
                hits += 1
                terms.append(hits / i)
        out.append(sum(terms) / min(total_rel, k))
    return float(np.mean(out))


case("precision_at_5", "precision_at_k", dict(RETR, k=5), ref_precision_at_k(5), atol=1e-12)
case("precision_at_10", "precision_at_k", dict(RETR, k=10), ref_precision_at_k(10), atol=1e-12)
case("map_at_5", "map_at_k", dict(RETR, k=5), ref_map_at_k(5), atol=1e-12)
case("map_at_10", "map_at_k", dict(RETR, k=10), ref_map_at_k(10), atol=1e-12)

logprobs = [-(0.2 + u * 4.0) for u in uniforms(54, 600)]
case("perplexity", "perplexity", {"logprobs": logprobs},
     np.exp(-np.mean(np.array(logprobs))), atol=1e-10, rtol=1e-12)

import jiwer  # noqa: E402

VOCAB = ["the", "model", "ran", "fast", "on", "data", "with", "errors", "loss", "clean",
         "tokens", "noise", "result", "good", "bad", "trace"]
wer_refs, wer_hyps = [], []
for i in range(40):
    us = uniforms(300 + i, 12)
    n_words = 5 + int(us[0] * 6)
    ref_words = [VOCAB[int(us[j + 1] * 16) % 16] for j in range(n_words)]
    hyp_words = list(ref_words)
    if us[7] < 0.6 and hyp_words:
        hyp_words[int(us[8] * len(hyp_words))] = VOCAB[int(us[9] * 16) % 16]   # substitution
    if us[10] < 0.3 and len(hyp_words) > 1:
        del hyp_words[int(us[11] * len(hyp_words))]                            # deletion
    wer_refs.append(" ".join(ref_words))
    wer_hyps.append(" ".join(hyp_words))
case("wer", "wer", {"preds": wer_hyps, "refs": wer_refs, "char_level": False},
     jiwer.wer(wer_refs, wer_hyps), atol=1e-12)
case("cer", "wer", {"preds": wer_hyps, "refs": wer_refs, "char_level": True},
     jiwer.cer(wer_refs, wer_hyps), atol=1e-12)

# ============================ special-function kernels ============================

for x in (1e-300, 1e-12, 0.1, 0.5, 1.0, 1.5, 2.0, 2.718281828459045, 10.0, 1e5, 1e150, 1e300):
    case("log_%g" % x, "dlog", {"x": x}, np.log(x), atol=1e-14, rtol=1e-14)
for x in (-700.0, -100.0, -5.0, -1.0, 0.0, 1e-9, 0.5, 1.0, 10.0, 100.0, 709.0):
    case("exp_%g" % x, "dexp", {"x": x}, np.exp(x), atol=1e-300, rtol=5e-15)
for z in (1e-3, 0.1, 0.5, 1.0, 1.5, 2.0, 7.3, 100.5, 252.0, 1e4):
    case("lgamma_%g" % z, "dlgamma", {"z": z}, special.gammaln(z), atol=5e-13, rtol=5e-13)
for a in (0.5, 1.0, 2.5, 5.0, 30.0, 126.0):
    for b in (0.5, 2.0, 27.5):
        for x in (0.01, 0.3, 0.5, 0.7, 0.99):
            case("betainc_%g_%g_%g" % (a, b, x), "betainc", {"a": a, "b": b, "x": x},
                 special.betainc(a, b, x), atol=1e-13, rtol=1e-11)
for s in (0.5, 1.0, 2.5, 7.0, 50.0):
    for x in (0.01, 0.5, 2.0, 10.0, 80.0):
        case("gammaincc_%g_%g" % (s, x), "gammaincc", {"s": s, "x": x},
             special.gammaincc(s, x), atol=1e-15, rtol=1e-11)
for x in (-3.0, -1.0, -0.1, 0.0, 0.5, 1.0, 2.0, 5.0):
    case("erfc_%g" % x, "erfc", {"x": x}, special.erfc(x), atol=1e-15, rtol=1e-11)
for t in (0.5, 1.5, 2.2, 4.0):
    for dfv in (1.0, 2.0, 10.0, 29.0, 100.7):
        case("tsf2_%g_%g" % (t, dfv), "t_sf2", {"t": t, "df": dfv},
             2.0 * stats.t.sf(t, dfv), atol=1e-15, rtol=1e-11)
for x in (0.5, 3.84, 10.0, 25.0):
    for dfv in (1.0, 2.0, 5.0, 12.0):
        case("chi2sf_%g_%g" % (x, dfv), "chi2_sf", {"x": x, "df": dfv},
             stats.chi2.sf(x, dfv), atol=1e-15, rtol=1e-11)
for alpha in (0.1, 0.05, 0.01, 0.001):
    for dfv in (1.0, 5.0, 10.0, 30.0, 200.0):
        case("tppf2_%g_%g" % (alpha, dfv), "t_ppf2", {"alpha": alpha, "df": dfv},
             stats.t.ppf(1 - alpha / 2, dfv), atol=1e-12, rtol=1e-10)
for alpha in (0.1, 0.05, 0.01):
    case("zppf2_%g" % alpha, "z_ppf2", {"alpha": alpha},
         stats.norm.ppf(1 - alpha / 2), atol=1e-12, rtol=1e-12)

# ============================ Pack QR - quant-risk depth ============================

qr = np.array(rets)
qbench = np.array(uniforms(40, 252, -0.025, 0.03))
bench_list = [float(x) for x in qbench]
qp = 252

eqc = np.cumprod(1.0 + qr)
pk = np.maximum(np.maximum.accumulate(eqc), 1.0)  # peak floored at initial capital 1.0 (engine convention)
ddq = eqc / pk - 1.0
ui = float(np.sqrt(np.mean(ddq ** 2)))
case("ulcer_index", "ulcer_index", {"rets": rets}, ui, atol=1e-12)
case("pain_index", "pain_index", {"rets": rets}, float(np.mean(-ddq)), atol=1e-12)
ann_q = float(np.prod(1.0 + qr)) ** (qp / len(qr)) - 1.0
case("martin_ratio", "martin_ratio", {"rets": rets, "periods": qp}, ann_q / ui, atol=1e-10)
mdd_q = float(np.min(eqc / pk - 1.0))
case("recovery_factor", "recovery_factor", {"rets": rets},
     float(np.prod(1.0 + qr) - 1.0) / abs(mdd_q), atol=1e-11)
case("gain_to_pain_ratio", "gain_to_pain_ratio", {"rets": rets},
     float(np.sum(qr) / np.sum(-qr[qr < 0])), atol=1e-11)
case("tail_ratio", "tail_ratio", {"rets": rets},
     float(abs(np.quantile(qr, 0.95)) / abs(np.quantile(qr, 0.05))), atol=1e-11)
case("gain_loss_ratio", "gain_loss_ratio", {"rets": rets},
     float(np.mean(qr[qr > 0]) / abs(np.mean(qr[qr < 0]))), atol=1e-11)
case("win_loss_ratio", "win_loss_ratio", {"rets": rets},
     float(np.sum(qr > 0) / np.sum(qr < 0)), atol=1e-12)
qwins, qloss = qr[qr > 0], qr[qr < 0]
qpayoff = float(np.mean(qwins) / abs(np.mean(qloss)))
qW = len(qwins) / (len(qwins) + len(qloss))
case("kelly_criterion", "kelly_criterion", {"rets": rets}, qW - (1.0 - qW) / qpayoff, atol=1e-12)
case("upside_deviation", "upside_deviation", {"rets": rets, "periods": qp},
     float(np.sqrt(np.mean(np.maximum(qr, 0.0) ** 2)) * np.sqrt(qp)), atol=1e-11)
case("upside_potential_ratio", "upside_potential_ratio", {"rets": rets},
     float(np.mean(np.maximum(qr, 0.0)) / np.sqrt(np.mean(np.minimum(qr, 0.0) ** 2))), atol=1e-11)
case("kappa_three", "kappa_three", {"rets": rets},
     float(np.mean(qr) / np.mean(np.maximum(-qr, 0.0) ** 3) ** (1.0 / 3.0)), atol=1e-11)
cut_q = np.quantile(ddq, 0.05)
case("cdar", "cdar", {"rets": rets, "level": 0.95},
     float(-np.mean(ddq[ddq <= cut_q])), atol=1e-11)


def _mdd_dur(r):
    e, p, cur, longest = 1.0, 1.0, 0, 0
    for x in r:
        e *= (1.0 + x)
        if e >= p:
            p, cur = e, 0
        else:
            cur += 1
            longest = max(longest, cur)
    return float(longest)


case("max_drawdown_duration", "max_drawdown_duration", {"rets": rets}, _mdd_dur(rets), atol=0.0, rtol=0.0)
qmu, qsd = float(np.mean(qr)), float(np.std(qr, ddof=1))
qS = float(stats.skew(qr, bias=True))
qKx = float(stats.kurtosis(qr, fisher=True, bias=True))
for lv in (0.95, 0.99):
    zq = stats.norm.ppf(1.0 - lv)
    case("parametric_var_%g" % lv, "parametric_var", {"rets": rets, "level": lv},
         float(-(qmu + zq * qsd)), atol=1e-9)
    aq = 1.0 - lv
    za = stats.norm.ppf(aq)
    case("parametric_es_%g" % lv, "parametric_es", {"rets": rets, "level": lv},
         float(-(qmu - qsd * stats.norm.pdf(za) / aq)), atol=1e-9)
    zcf = (zq + (zq * zq - 1) * qS / 6 + (zq ** 3 - 3 * zq) * qKx / 24
           - (2 * zq ** 3 - 5 * zq) * qS * qS / 36)
    case("cornish_fisher_var_%g" % lv, "cornish_fisher_var", {"rets": rets, "level": lv},
         float(-(qmu + zcf * qsd)), atol=1e-9)
qsr = qmu / qsd
case("adjusted_sharpe_ratio", "adjusted_sharpe_ratio", {"rets": rets},
     float(qsr * (1 + (qS / 6) * qsr - (qKx / 24) * qsr * qsr)), atol=1e-11)
qg4 = float(stats.kurtosis(qr, fisher=False, bias=True))
qdenom = 1 - qS * qsr + ((qg4 - 1) / 4) * qsr * qsr
qstat = qsr * np.sqrt(len(qr) - 1) / np.sqrt(qdenom)
case("probabilistic_sharpe_ratio", "probabilistic_sharpe_ratio",
     {"rets": rets, "benchmark_sr": 0.0}, float(stats.norm.cdf(qstat)), atol=1e-9)
upc = float(np.mean(qr[qbench > 0]) / np.mean(qbench[qbench > 0]))
dnc = float(np.mean(qr[qbench < 0]) / np.mean(qbench[qbench < 0]))
case("up_capture_ratio", "up_capture_ratio", {"rets": rets, "bench": bench_list}, upc, atol=1e-11)
case("down_capture_ratio", "down_capture_ratio", {"rets": rets, "bench": bench_list}, dnc, atol=1e-11)
case("capture_ratio", "capture_ratio", {"rets": rets, "bench": bench_list}, upc / dnc, atol=1e-11)
qbeta = float(np.cov(qr, qbench, ddof=1)[0, 1] / np.var(qbench, ddof=1))
case("treynor_ratio", "treynor_ratio", {"rets": rets, "bench": bench_list, "periods": qp},
     float(qmu * qp / qbeta), atol=1e-10)
qrho = float(np.corrcoef(qr, qbench)[0, 1])
case("r_squared", "r_squared", {"rets": rets, "bench": bench_list}, qrho * qrho, atol=1e-11)
case("active_return", "active_return", {"rets": rets, "bench": bench_list, "periods": qp},
     float(np.mean(qr - qbench) * qp), atol=1e-11)

# ============================ Pack ST - statistics & hypothesis tests ============================

from statsmodels.stats.contingency_tables import mcnemar as sm_mcnemar  # noqa: E402

# point-biserial = Pearson(binary, continuous)
pb_bin = [1.0 if u < 0.45 else 0.0 for u in uniforms(50, 200)]
pb_val = uniforms(51, 200, 0.0, 10.0)
case("point_biserial", "point_biserial", {"binary": pb_bin, "value": pb_val},
     float(stats.pointbiserialr(pb_bin, pb_val)[0]), atol=1e-11)

# kendall tau-b (with ties)
kt_x = [round(u, 1) for u in uniforms(52, 120, 0.0, 5.0)]
kt_y = [round(u, 1) for u in uniforms(53, 120, 0.0, 5.0)]
case("kendall_tau", "kendall_tau", {"xs": kt_x, "ys": kt_y},
     float(stats.kendalltau(kt_x, kt_y)[0]), atol=1e-11)

# Theil-Sen slope
ts_x = uniforms(54, 80, 0.0, 20.0)
ts_y = [2.0 * x + e for x, e in zip(ts_x, uniforms(55, 80, -3.0, 3.0))]
case("theil_sen_slope", "theil_sen_slope", {"xs": ts_x, "ys": ts_y},
     float(stats.theilslopes(ts_y, ts_x)[0]), atol=1e-11)

# Cliff's delta (definitional)
cd_a = uniforms(56, 90, 0.0, 10.0)
cd_b = uniforms(57, 85, 2.0, 12.0)
_gt = sum(1 for x in cd_a for y in cd_b if x > y)
_lt = sum(1 for x in cd_a for y in cd_b if x < y)
case("cliffs_delta", "cliffs_delta", {"a": cd_a, "b": cd_b},
     (_gt - _lt) / (len(cd_a) * len(cd_b)), atol=1e-12)

# rank-biserial from Mann-Whitney U
rb_a = [round(u, 1) for u in uniforms(58, 60, 0.0, 5.0)]
rb_b = [round(u, 1) for u in uniforms(59, 70, 1.0, 6.0)]
_u1 = float(stats.mannwhitneyu(rb_a, rb_b, alternative="two-sided", method="asymptotic").statistic)
case("rank_biserial", "rank_biserial", {"a": rb_a, "b": rb_b},
     1.0 - 2.0 * _u1 / (len(rb_a) * len(rb_b)), atol=1e-11)

# eta-squared (one-way; definitional SS_between / SS_total)
_names = ["A", "B", "C"]
_offs = {"A": 0.0, "B": 1.5, "C": -1.0}
es_g = [_names[int(u * 3)] for u in uniforms(60, 150)]
es_v = [_offs[g] + e for g, e in zip(es_g, uniforms(61, 150, -1.0, 1.0))]
_grand = float(np.mean(es_v))
_ssb = float(sum((es_g.count(nm)) * (np.mean([v for v, g in zip(es_v, es_g) if g == nm]) - _grand) ** 2
                 for nm in set(es_g)))
_sst = float(np.sum((np.array(es_v) - _grand) ** 2))
case("eta_squared", "eta_squared", {"groups": es_g, "values": es_v}, _ssb / _sst, atol=1e-11)

# G-test of independence (log-likelihood, no continuity correction)
gt_g = ["X" if u < 0.5 else "Y" for u in uniforms(62, 220)]
gt_o = ["hit" if v < (0.6 if g == "X" else 0.38) else "miss"
        for g, v in zip(gt_g, uniforms(63, 220))]
_tab = [[sum(1 for g, o in zip(gt_g, gt_o) if g == gg and o == oo) for oo in ("hit", "miss")]
        for gg in ("X", "Y")]
case("g_test", "g_test", {"groups": gt_g, "outcomes": gt_o, "output": "p"},
     float(stats.chi2_contingency(_tab, lambda_="log-likelihood", correction=False)[1]), atol=1e-9)

# McNemar (paired binary, asymptotic + continuity)
mc_a = [1 if u < 0.5 else 0 for u in uniforms(64, 160)]
mc_b = [1 if u < 0.45 else 0 for u in uniforms(65, 160)]
_n11 = sum(1 for x, y in zip(mc_a, mc_b) if x == 1 and y == 1)
_n10 = sum(1 for x, y in zip(mc_a, mc_b) if x == 1 and y == 0)
_n01 = sum(1 for x, y in zip(mc_a, mc_b) if x == 0 and y == 1)
_n00 = sum(1 for x, y in zip(mc_a, mc_b) if x == 0 and y == 0)
_mc = sm_mcnemar([[_n11, _n10], [_n01, _n00]], exact=False, correction=True)
case("mcnemar", "mcnemar", {"a": [float(x) for x in mc_a], "b": [float(x) for x in mc_b]},
     float(_mc.pvalue), atol=1e-9)

# ============================ Pack ST2 - variance/distribution/nonparametric ============================

from statsmodels.stats.proportion import proportion_confint  # noqa: E402
from statsmodels.stats.multitest import multipletests  # noqa: E402

# k-sample groups with different spread/location (rounded -> ties exercise tie corrections)
_lvnm = ["A", "B", "C"]
_scale = {"A": 1.0, "B": 2.0, "C": 0.5}
_loc = {"A": 0.0, "B": 1.0, "C": -1.0}
lv_g = [_lvnm[int(u * 3)] for u in uniforms(70, 180)]
lv_v = [round(_loc[g] + _scale[g] * e, 1) for g, e in zip(lv_g, uniforms(71, 180, -2.0, 2.0))]
_samples = [[v for v, g in zip(lv_v, lv_g) if g == nm] for nm in _lvnm]
case("levene", "levene", {"groups": lv_g, "values": lv_v},
     float(stats.levene(*_samples, center="median")[1]), atol=1e-10)
case("bartlett", "bartlett", {"groups": lv_g, "values": lv_v},
     float(stats.bartlett(*_samples)[1]), atol=1e-9)
case("fligner", "fligner", {"groups": lv_g, "values": lv_v},
     float(stats.fligner(*_samples, center="median")[1]), atol=1e-9)
case("kruskal_wallis", "kruskal_wallis", {"groups": lv_g, "values": lv_v},
     float(stats.kruskal(*_samples)[1]), atol=1e-9)

# Wilcoxon signed-rank (paired, continuous -> no zeros)
ws_a = uniforms(72, 80, 0.0, 10.0)
ws_b = [x + e for x, e in zip(ws_a, uniforms(73, 80, -2.0, 3.0))]
_wd = [x - y for x, y in zip(ws_a, ws_b)]
case("wilcoxon_signed_rank", "wilcoxon_signed_rank", {"a": ws_a, "b": ws_b},
     float(stats.wilcoxon(_wd, method="approx")[1]), atol=1e-9)

# Anderson-Darling A^2 (normality)
ad_x = uniforms(74, 100, -3.0, 5.0)
case("anderson_darling", "anderson_darling", {"xs": ad_x},
     float(stats.anderson(ad_x, "norm").statistic), atol=1e-9)

# Wilson score interval bounds
wl_f = [1.0 if u < 0.4 else 0.0 for u in uniforms(75, 150)]
_x = int(sum(wl_f))
_lo, _hi = proportion_confint(_x, len(wl_f), alpha=0.05, method="wilson")
case("wilson_lower", "wilson_lower", {"flags": wl_f, "level": 0.95}, float(_lo), atol=1e-10)
case("wilson_upper", "wilson_upper", {"flags": wl_f, "level": 0.95}, float(_hi), atol=1e-10)

# Multiple-testing rejection counts
pv = [round(u ** 2, 6) for u in uniforms(76, 40)]
case("bh_rejections", "bh_rejections", {"pvals": pv, "alpha": 0.05},
     float(multipletests(pv, alpha=0.05, method="fdr_bh")[0].sum()), atol=0.0, rtol=0.0)
case("holm_rejections", "holm_rejections", {"pvals": pv, "alpha": 0.05},
     float(multipletests(pv, alpha=0.05, method="holm")[0].sum()), atol=0.0, rtol=0.0)

# ============================ Pack RM - risk-model validation ============================


def _clnp_ref(c, p):
    return c * float(np.log(p)) if (c > 0 and p > 0) else 0.0


# VaR exception sequence (1 = breach)
ex = [1 if u < 0.03 else 0 for u in uniforms(80, 250)]
rm_p0 = 0.01
_nx, _nn = sum(ex), len(ex)
_pi = _nx / _nn
_ll0 = (_nn - _nx) * float(np.log(1 - rm_p0)) + _clnp_ref(_nx, rm_p0)
_ll1 = _clnp_ref(_nn - _nx, 1 - _pi) + _clnp_ref(_nx, _pi)
_lruc = max(0.0, -2.0 * (_ll0 - _ll1))
ex_f = [float(f) for f in ex]
case("kupiec_pof", "kupiec_pof", {"flags": ex_f, "p0": rm_p0}, float(stats.chi2.sf(_lruc, 1)), atol=1e-9)
_n00 = _n01 = _n10 = _n11 = 0
for _pr, _cu in zip(ex, ex[1:]):
    if _pr == 0 and _cu == 0:
        _n00 += 1
    elif _pr == 0 and _cu == 1:
        _n01 += 1
    elif _pr == 1 and _cu == 0:
        _n10 += 1
    else:
        _n11 += 1
_t = _n00 + _n01 + _n10 + _n11
_piC = (_n01 + _n11) / _t
_pi01 = _n01 / (_n00 + _n01) if (_n00 + _n01) > 0 else 0.0
_pi11 = _n11 / (_n10 + _n11) if (_n10 + _n11) > 0 else 0.0
_llind = _clnp_ref(_n00 + _n10, 1 - _piC) + _clnp_ref(_n01 + _n11, _piC)
_llmkv = (_clnp_ref(_n00, 1 - _pi01) + _clnp_ref(_n01, _pi01)
          + _clnp_ref(_n10, 1 - _pi11) + _clnp_ref(_n11, _pi11))
_lrind = max(0.0, -2.0 * (_llind - _llmkv))
case("christoffersen_independence", "christoffersen_independence", {"flags": ex_f},
     float(stats.chi2.sf(_lrind, 1)), atol=1e-9)
case("christoffersen_cc", "christoffersen_cc", {"flags": ex_f, "p0": rm_p0},
     float(stats.chi2.sf(_lruc + _lrind, 2)), atol=1e-9)

# Population Stability Index
psi_e = uniforms(81, 12, 1.0, 100.0)
psi_a = uniforms(82, 12, 1.0, 100.0)
_se, _sa = sum(psi_e), sum(psi_a)
_psi = float(sum((a / _sa - e / _se) * np.log((a / _sa) / (e / _se)) for e, a in zip(psi_e, psi_a)))
case("psi", "psi", {"expected": psi_e, "actual": psi_a}, _psi, atol=1e-11)

# Information value (binned good/bad; label 1 = bad)
iv_g = [["b1", "b2", "b3", "b4"][int(u * 4)] for u in uniforms(83, 300)]
iv_y = [1.0 if v < (0.6 if g in ("b1", "b2") else 0.3) else 0.0 for g, v in zip(iv_g, uniforms(84, 300))]
_ivb = {}
for _g, _y in zip(iv_g, iv_y):
    _bb = _ivb.setdefault(_g, [0, 0])
    _bb[1 if _y != 0 else 0] += 1
_tg = sum(b[0] for b in _ivb.values())
_tb = sum(b[1] for b in _ivb.values())
_iv = float(sum((b[0] / _tg - b[1] / _tb) * np.log((b[0] / _tg) / (b[1] / _tb))
                for b in _ivb.values() if b[0] > 0 and b[1] > 0))
case("information_value", "information_value", {"groups": iv_g, "labels": iv_y}, _iv, atol=1e-11)

# KL / JS divergence
kp = uniforms(85, 15, 0.1, 5.0)
kq = uniforms(86, 15, 0.1, 5.0)
case("kl_divergence", "kl_divergence", {"p": kp, "q": kq}, float(stats.entropy(kp, kq)), atol=1e-11)
_P = np.array(kp) / sum(kp)
_Q = np.array(kq) / sum(kq)
_Md = (_P + _Q) / 2.0
case("js_divergence", "js_divergence", {"p": kp, "q": kq},
     float(0.5 * stats.entropy(_P, _Md) + 0.5 * stats.entropy(_Q, _Md)), atol=1e-11)

# Wasserstein / energy / two-sample KS
wa = uniforms(87, 90, 0.0, 10.0)
wb = uniforms(88, 80, 1.0, 12.0)
case("wasserstein_1d", "wasserstein_1d", {"a": wa, "b": wb}, float(stats.wasserstein_distance(wa, wb)), atol=1e-10)
case("energy_distance", "energy_distance", {"a": wa, "b": wb}, float(stats.energy_distance(wa, wb)), atol=1e-10)
case("ks_2samp", "ks_2samp", {"a": wa, "b": wb}, float(stats.ks_2samp(wa, wb).statistic), atol=1e-12)

# ============================ Pack CR - classification & regression depth ============================

cr_label = [1 if u < 0.45 else 0 for u in uniforms(90, 300)]
cr_pred = [1 if u < (0.72 if y == 1 else 0.22) else 0 for y, u in zip(cr_label, uniforms(91, 300))]
_cm = skm.confusion_matrix(cr_label, cr_pred, labels=[0, 1])
_tn, _fp, _fn, _tp = int(_cm[0, 0]), int(_cm[0, 1]), int(_cm[1, 0]), int(_cm[1, 1])
_pf = [float(x) for x in cr_pred]
_lf = [float(x) for x in cr_label]
_tpr = _tp / (_tp + _fn)
_tnr = _tn / (_tn + _fp)
case("g_mean", "g_mean", {"pred": _pf, "label": _lf}, float(np.sqrt(_tpr * _tnr)), atol=1e-12)
case("youden_j", "youden_j", {"pred": _pf, "label": _lf}, _tpr + _tnr - 1.0, atol=1e-12)
case("markedness", "markedness", {"pred": _pf, "label": _lf},
     _tp / (_tp + _fp) + _tn / (_tn + _fn) - 1.0, atol=1e-12)
case("negative_predictive_value", "negative_predictive_value", {"pred": _pf, "label": _lf},
     _tn / (_tn + _fn), atol=1e-12)
case("false_positive_rate", "false_positive_rate", {"pred": _pf, "label": _lf}, _fp / (_fp + _tn), atol=1e-12)
case("false_negative_rate", "false_negative_rate", {"pred": _pf, "label": _lf}, _fn / (_fn + _tp), atol=1e-12)
case("false_discovery_rate", "false_discovery_rate", {"pred": _pf, "label": _lf}, _fp / (_fp + _tp), atol=1e-12)
_lrp, _lrn = skm.class_likelihood_ratios(cr_label, cr_pred)
case("positive_likelihood_ratio", "positive_likelihood_ratio", {"pred": _pf, "label": _lf}, float(_lrp), atol=1e-11)
case("negative_likelihood_ratio", "negative_likelihood_ratio", {"pred": _pf, "label": _lf}, float(_lrn), atol=1e-11)
case("diagnostic_odds_ratio", "diagnostic_odds_ratio", {"pred": _pf, "label": _lf},
     (_tp * _tn) / (_fp * _fn), atol=1e-10)
case("threat_score", "threat_score", {"pred": _pf, "label": _lf}, _tp / (_tp + _fn + _fp), atol=1e-12)
case("fowlkes_mallows", "fowlkes_mallows", {"pred": _pf, "label": _lf},
     float(np.sqrt((_tp / (_tp + _fp)) * (_tp / (_tp + _fn)))), atol=1e-12)

# regression depth (positive targets/preds for the deviances)
rg_actual = uniforms(92, 200, 0.5, 20.0)
rg_pred = [max(0.1, a + e) for a, e in zip(rg_actual, uniforms(93, 200, -3.0, 3.0))]
_mp, _ma = float(np.mean(rg_pred)), float(np.mean(rg_actual))
_vp = float(np.mean((np.array(rg_pred) - _mp) ** 2))
_va = float(np.mean((np.array(rg_actual) - _ma) ** 2))
_cov = float(np.mean((np.array(rg_pred) - _mp) * (np.array(rg_actual) - _ma)))
case("concordance_correlation", "concordance_correlation", {"pred": rg_pred, "actual": rg_actual},
     2.0 * _cov / (_vp + _va + (_mp - _ma) ** 2), atol=1e-11)
_delta = 1.0
_hub = float(np.mean([0.5 * (p - a) ** 2 if abs(p - a) <= _delta else _delta * (abs(p - a) - 0.5 * _delta)
                      for p, a in zip(rg_pred, rg_actual)]))
case("huber_loss", "huber_loss", {"pred": rg_pred, "actual": rg_actual, "delta": _delta}, _hub, atol=1e-12)
case("poisson_deviance", "poisson_deviance", {"pred": rg_pred, "actual": rg_actual},
     float(skm.mean_poisson_deviance(rg_actual, rg_pred)), atol=1e-11)
case("gamma_deviance", "gamma_deviance", {"pred": rg_pred, "actual": rg_actual},
     float(skm.mean_gamma_deviance(rg_actual, rg_pred)), atol=1e-11)
case("d2_absolute_error", "d2_absolute_error", {"pred": rg_pred, "actual": rg_actual},
     float(skm.d2_absolute_error_score(rg_actual, rg_pred)), atol=1e-11)

# ============================ Pack AN - analytics / data-quality / robust stats ============================

from statsmodels.stats.diagnostic import acorr_ljungbox  # noqa: E402

an_x = uniforms(94, 200, 5.0, 50.0)
_ax = np.array(an_x)
case("variance", "variance", {"xs": an_x}, float(np.var(_ax, ddof=1)), atol=1e-9)
case("range_value", "range_value", {"xs": an_x}, float(np.max(_ax) - np.min(_ax)), atol=1e-12)
case("mean_abs_deviation", "mean_abs_deviation", {"xs": an_x},
     float(np.mean(np.abs(_ax - np.mean(_ax)))), atol=1e-10)
case("median_abs_deviation", "median_abs_deviation", {"xs": an_x},
     float(stats.median_abs_deviation(_ax, scale=1.0)), atol=1e-10)
case("trimmed_mean", "trimmed_mean", {"xs": an_x, "proportion": 0.1},
     float(stats.trim_mean(_ax, 0.1)), atol=1e-10)
case("geometric_mean", "geometric_mean", {"xs": an_x}, float(stats.gmean(_ax)), atol=1e-10)
case("harmonic_mean", "harmonic_mean", {"xs": an_x}, float(stats.hmean(_ax)), atol=1e-10)
_m = float(np.mean(_ax))
case("theil_index", "theil_index", {"xs": an_x},
     float(np.mean((_ax / _m) * np.log(_ax / _m))), atol=1e-11)
case("atkinson_index", "atkinson_index", {"xs": an_x}, float(1.0 - stats.gmean(_ax) / _m), atol=1e-10)
_q1, _q3 = float(np.quantile(_ax, 0.25)), float(np.quantile(_ax, 0.75))
case("quartile_coefficient_dispersion", "quartile_coefficient_dispersion", {"xs": an_x},
     (_q3 - _q1) / (_q3 + _q1), atol=1e-11)
case("index_of_dispersion", "index_of_dispersion", {"xs": an_x}, float(np.var(_ax, ddof=1) / _m), atol=1e-10)

an_v = uniforms(95, 80, 0.0, 10.0)
an_w = uniforms(96, 80, 0.5, 3.0)
case("weighted_mean", "weighted_mean", {"values": an_v, "weights": an_w},
     float(np.average(an_v, weights=an_w)), atol=1e-11)

cov_x = uniforms(97, 90, 0.0, 10.0)
cov_y = [2.0 * x + e for x, e in zip(cov_x, uniforms(98, 90, -2.0, 2.0))]
case("covariance", "covariance", {"xs": cov_x, "ys": cov_y},
     float(np.cov(cov_x, cov_y, ddof=1)[0, 1]), atol=1e-10)

uq_raw = [str(int(u * 20)) for u in uniforms(101, 150)]
case("uniqueness_ratio", "uniqueness_ratio", {"raw": uq_raw}, len(set(uq_raw)) / len(uq_raw), atol=1e-12)

ts = uniforms(102, 120, -1.0, 1.0)
_lb = acorr_ljungbox(np.array(ts), lags=[10], return_df=True)
case("ljung_box", "ljung_box", {"xs": ts, "lags": 10}, float(_lb["lb_pvalue"].iloc[0]), atol=1e-9)

# ============================ Pack TS - forecasting / time-series accuracy ============================

ts_actual = uniforms(103, 100, 10.0, 60.0)
ts_pred = [a + e for a, e in zip(ts_actual, uniforms(104, 100, -5.0, 5.0))]
_ta, _tp = np.array(ts_actual), np.array(ts_pred)
_n = len(_ta)
_rmse = float(np.sqrt(np.mean((_tp - _ta) ** 2)))
_u1 = _rmse / (float(np.sqrt(np.mean(_tp ** 2))) + float(np.sqrt(np.mean(_ta ** 2))))
case("theil_u1", "theil_u1", {"pred": ts_pred, "actual": ts_actual}, _u1, atol=1e-10)
_num = float(np.sum(((_tp[1:] - _ta[1:]) / _ta[:-1]) ** 2))
_den = float(np.sum(((_ta[1:] - _ta[:-1]) / _ta[:-1]) ** 2))
case("theil_u2", "theil_u2", {"pred": ts_pred, "actual": ts_actual},
     float(np.sqrt(_num) / np.sqrt(_den)), atol=1e-10)
_mse = float(np.mean((_ta - _tp) ** 2))
_denom = float(np.sum((_ta[1:] - _ta[:-1]) ** 2) / (_n - 1))
case("rmsse", "rmsse", {"pred": ts_pred, "actual": ts_actual}, float(np.sqrt(_mse / _denom)), atol=1e-10)
case("tracking_signal", "tracking_signal", {"pred": ts_pred, "actual": ts_actual},
     float(np.sum(_tp - _ta) / np.mean(np.abs(_tp - _ta))), atol=1e-10)
_hits = sum(1 for t in range(1, _n)
            if (np.sign(_ta[t] - _ta[t - 1]) == np.sign(_tp[t] - _ta[t - 1])))
case("mean_directional_accuracy", "mean_directional_accuracy", {"pred": ts_pred, "actual": ts_actual},
     _hits / (_n - 1), atol=1e-12)
_mam = float(np.mean(_ta))
case("relative_absolute_error", "relative_absolute_error", {"pred": ts_pred, "actual": ts_actual},
     float(np.sum(np.abs(_tp - _ta)) / np.sum(np.abs(_ta - _mam))), atol=1e-11)
case("relative_squared_error", "relative_squared_error", {"pred": ts_pred, "actual": ts_actual},
     float(np.sum((_tp - _ta) ** 2) / np.sum((_ta - _mam) ** 2)), atol=1e-11)
case("mean_percentage_error", "mean_percentage_error", {"pred": ts_pred, "actual": ts_actual},
     float(np.mean((_ta - _tp) / _ta)), atol=1e-11)
case("median_absolute_percentage_error", "median_absolute_percentage_error",
     {"pred": ts_pred, "actual": ts_actual}, float(np.median(np.abs(_tp - _ta) / np.abs(_ta))), atol=1e-11)

# ============================ Pack FAIR - fairness / bias ============================

import fairlearn.metrics as fm  # noqa: E402

fa_group = [["a", "b"][int(u * 2)] for u in uniforms(105, 320)]
fa_label = [1 if u < 0.5 else 0 for u in uniforms(106, 320)]
fa_pred = [1 if u < (0.72 if (y == 1 and g == "a") else 0.5 if y == 1 else 0.3 if g == "a" else 0.15) else 0
           for y, g, u in zip(fa_label, fa_group, uniforms(107, 320))]
_fp_pred = [float(x) for x in fa_pred]
_fp_lab = [float(x) for x in fa_label]
_fargs = {"pred": _fp_pred, "label": _fp_lab, "group": fa_group}
case("demographic_parity_difference", "demographic_parity_difference", _fargs,
     float(fm.demographic_parity_difference(fa_label, fa_pred, sensitive_features=fa_group)), atol=1e-12)
case("demographic_parity_ratio", "demographic_parity_ratio", _fargs,
     float(fm.demographic_parity_ratio(fa_label, fa_pred, sensitive_features=fa_group)), atol=1e-12)
case("equalized_odds_difference", "equalized_odds_difference", _fargs,
     float(fm.equalized_odds_difference(fa_label, fa_pred, sensitive_features=fa_group)), atol=1e-12)
case("equalized_odds_ratio", "equalized_odds_ratio", _fargs,
     float(fm.equalized_odds_ratio(fa_label, fa_pred, sensitive_features=fa_group)), atol=1e-12)
_gr = {}
for _p, _y, _s in zip(fa_pred, fa_label, fa_group):
    _d = _gr.setdefault(_s, [0, 0, 0, 0])
    _d[0 if (_p == 1 and _y == 1) else 1 if (_p == 1 and _y == 0) else 2 if (_p == 0 and _y == 1) else 3] += 1
_tprs = [tp / (tp + fn) for tp, fp, fn, tn in _gr.values() if tp + fn]
_ppvs = [tp / (tp + fp) for tp, fp, fn, tn in _gr.values() if tp + fp]
_fprs = [fp / (fp + tn) for tp, fp, fn, tn in _gr.values() if fp + tn]
_accs = [(tp + tn) / (tp + fp + fn + tn) for tp, fp, fn, tn in _gr.values()]
case("equal_opportunity_difference", "equal_opportunity_difference", _fargs, max(_tprs) - min(_tprs), atol=1e-12)
case("predictive_parity_difference", "predictive_parity_difference", _fargs, max(_ppvs) - min(_ppvs), atol=1e-12)
case("fpr_parity_difference", "fpr_parity_difference", _fargs, max(_fprs) - min(_fprs), atol=1e-12)
case("accuracy_parity_difference", "accuracy_parity_difference", _fargs, max(_accs) - min(_accs), atol=1e-12)

# ============================ Pack BC - survival concordance + clustering ============================

from lifelines.utils import concordance_index as ll_ci  # noqa: E402

surv_t = uniforms(108, 80, 1.0, 100.0)
surv_s = uniforms(109, 80, 0.0, 1.0)
surv_e = [1.0 if u < 0.7 else 0.0 for u in uniforms(110, 80)]
case("concordance_index", "concordance_index", {"time": surv_t, "score": surv_s, "event": surv_e},
     float(ll_ci(surv_t, surv_s, surv_e)), atol=1e-10)

cl_a = [float(int(u * 4)) for u in uniforms(111, 200)]
cl_b = [float(int(v * 4)) if u < 0.2 else a for a, u, v in zip(cl_a, uniforms(112, 200), uniforms(113, 200))]
_cargs = {"a": cl_a, "b": cl_b}
case("mutual_info_score", "mutual_info_score", _cargs, float(skm.mutual_info_score(cl_a, cl_b)), atol=1e-11)
case("normalized_mutual_info", "normalized_mutual_info", _cargs,
     float(skm.normalized_mutual_info_score(cl_a, cl_b)), atol=1e-11)
case("homogeneity_score", "homogeneity_score", _cargs, float(skm.homogeneity_score(cl_a, cl_b)), atol=1e-11)
case("completeness_score", "completeness_score", _cargs, float(skm.completeness_score(cl_a, cl_b)), atol=1e-11)
case("v_measure_score", "v_measure_score", _cargs, float(skm.v_measure_score(cl_a, cl_b)), atol=1e-11)
case("rand_index", "rand_index", _cargs, float(skm.rand_score(cl_a, cl_b)), atol=1e-12)
case("adjusted_rand_index", "adjusted_rand_index", _cargs, float(skm.adjusted_rand_score(cl_a, cl_b)), atol=1e-12)
case("fowlkes_mallows_clustering", "fowlkes_mallows_clustering", _cargs,
     float(skm.fowlkes_mallows_score(cl_a, cl_b)), atol=1e-12)

# ============================ Pack ENG - performance / SRE depth ============================

eng_dur = uniforms(114, 500, 1.0, 900.0)
_ed = np.array(eng_dur)
case("latency_p75", "latency_p75", {"durations": eng_dur}, float(np.quantile(_ed, 0.75)), atol=1e-10)
case("latency_p999", "latency_p999", {"durations": eng_dur}, float(np.quantile(_ed, 0.999)), atol=1e-10)
case("tail_latency_ratio", "tail_latency_ratio", {"durations": eng_dur},
     float(np.quantile(_ed, 0.99) / np.quantile(_ed, 0.5)), atol=1e-10)
case("latency_stddev", "latency_stddev", {"durations": eng_dur}, float(np.std(_ed, ddof=1)), atol=1e-9)
case("jitter", "jitter", {"durations": eng_dur}, float(np.mean(np.abs(np.diff(_ed)))), atol=1e-10)
case("slo_attainment", "slo_attainment", {"durations": eng_dur, "threshold": 500.0},
     float(np.mean(_ed <= 500.0)), atol=1e-12)
eb_flags = [1.0 if u < 0.03 else 0.0 for u in uniforms(115, 400)]
case("error_budget_burn", "error_budget_burn", {"flags": eb_flags, "target": 0.01},
     (sum(eb_flags) / len(eb_flags)) / 0.01, atol=1e-11)
cr_orig = uniforms(116, 60, 100.0, 1000.0)
cr_comp = uniforms(117, 60, 10.0, 300.0)
case("compression_ratio", "compression_ratio", {"original": cr_orig, "compressed": cr_comp},
     float(np.sum(cr_orig) / np.sum(cr_comp)), atol=1e-10)
av_up = uniforms(118, 40, 90.0, 100.0)
av_dn = uniforms(119, 40, 0.0, 10.0)
case("availability", "availability", {"uptime": av_up, "downtime": av_dn},
     float(np.sum(av_up) / (np.sum(av_up) + np.sum(av_dn))), atol=1e-12)
mt_flags = [1.0 if u < 0.1 else 0.0 for u in uniforms(120, 300)]
case("mtbf", "mtbf", {"flags": mt_flags}, len(mt_flags) / sum(mt_flags), atol=1e-12)

# ============================ Pack QR2 - quant performance depth ============================

_annq = float(np.prod(1.0 + qr)) ** (qp / len(qr)) - 1.0
case("pain_ratio", "pain_ratio", {"rets": rets, "periods": qp}, _annq / float(np.mean(-ddq)), atol=1e-10)
case("sterling_ratio", "sterling_ratio", {"rets": rets, "periods": qp},
     _annq / (abs(float(np.min(ddq))) + 0.10), atol=1e-10)
case("burke_ratio", "burke_ratio", {"rets": rets, "periods": qp},
     _annq / float(np.sqrt(np.sum(ddq ** 2))), atol=1e-10)
case("m2_measure", "m2_measure", {"rets": rets, "bench": bench_list},
     float((np.mean(qr) / np.std(qr, ddof=1)) * np.std(qbench, ddof=1)), atol=1e-10)
_beta2 = float(np.cov(qr, qbench, ddof=1)[0, 1] / np.var(qbench, ddof=1))
_alpha2 = float(np.mean(qr) - _beta2 * np.mean(qbench))
_resid = qr - (_alpha2 + _beta2 * qbench)
case("appraisal_ratio", "appraisal_ratio", {"rets": rets, "bench": bench_list},
     float(_alpha2 / np.std(_resid, ddof=1)), atol=1e-10)
_csr = float(abs(np.quantile(qr, 0.95)) / abs(np.quantile(qr, 0.05))) * float(np.sum(qr[qr > 0]) / -np.sum(qr[qr < 0]))
case("common_sense_ratio", "common_sense_ratio", {"rets": rets}, _csr, atol=1e-10)
_rlo, _rhi = np.quantile(qr, 0.05), np.quantile(qr, 0.95)
case("rachev_ratio", "rachev_ratio", {"rets": rets, "level": 0.95},
     float(np.mean(qr[qr >= _rhi]) / -np.mean(qr[qr <= _rlo])), atol=1e-10)
case("downside_potential", "downside_potential", {"rets": rets}, float(np.mean(np.maximum(-qr, 0.0))), atol=1e-11)
case("upside_potential", "upside_potential", {"rets": rets}, float(np.mean(np.maximum(qr, 0.0))), atol=1e-11)
case("omega_sharpe_ratio", "omega_sharpe_ratio", {"rets": rets, "threshold": 0.0},
     float(np.mean(qr) / np.mean(np.maximum(-qr, 0.0))), atol=1e-11)

# ============================ Pack EXP - causal / experimentation ============================

at_t = uniforms(125, 120, 0.0, 10.0)
at_c = uniforms(126, 100, -1.0, 8.0)
case("average_treatment_effect", "average_treatment_effect", {"treatment": at_t, "control": at_c},
     float(np.mean(at_t) - np.mean(at_c)), atol=1e-11)
case("standardized_mean_difference", "standardized_mean_difference", {"treatment": at_t, "control": at_c},
     float((np.mean(at_t) - np.mean(at_c)) / np.sqrt((np.var(at_t, ddof=1) + np.var(at_c, ddof=1)) / 2)), atol=1e-11)
rb_t = [1.0 if u < 0.6 else 0.0 for u in uniforms(127, 150)]
rb_c = [1.0 if u < 0.4 else 0.0 for u in uniforms(128, 150)]
case("risk_difference", "risk_difference", {"treatment": rb_t, "control": rb_c},
     float(np.mean(rb_t) - np.mean(rb_c)), atol=1e-12)
case("relative_risk_reduction", "relative_risk_reduction", {"treatment": rb_t, "control": rb_c},
     float((np.mean(rb_c) - np.mean(rb_t)) / np.mean(rb_c)), atol=1e-12)
case("number_needed_to_treat", "number_needed_to_treat", {"treatment": rb_t, "control": rb_c},
     float(1.0 / abs(np.mean(rb_t) - np.mean(rb_c))), atol=1e-11)
cu_x = uniforms(129, 200, 0.0, 10.0)
cu_g = [1.0 if u < 0.5 else 0.0 for u in uniforms(130, 200)]
cu_y = [0.6 * x + (1.0 if g else 0.0) + e for x, g, e in zip(cu_x, cu_g, uniforms(131, 200, -2.0, 2.0))]
_theta = float(np.cov(cu_y, cu_x, ddof=1)[0, 1] / np.var(cu_x, ddof=1))
_yadj = np.array(cu_y) - _theta * (np.array(cu_x) - np.mean(cu_x))
_gm = np.array(cu_g)
case("cuped_ate", "cuped_ate", {"value": cu_y, "covariate": cu_x, "group": cu_g},
     float(np.mean(_yadj[_gm != 0]) - np.mean(_yadj[_gm == 0])), atol=1e-11)
case("variance_reduction_cuped", "variance_reduction_cuped", {"value": cu_y, "covariate": cu_x},
     float(1.0 - np.var(_yadj, ddof=1) / np.var(cu_y, ddof=1)), atol=1e-11)
srm_g = ["A" if u < 0.52 else "B" for u in uniforms(132, 500)]
_obs = [srm_g.count("A"), srm_g.count("B")]
_n = len(srm_g)
case("srm_pvalue", "srm_pvalue", {"group": srm_g},
     float(stats.chisquare(_obs, [_n / 2, _n / 2])[1]), atol=1e-9)

# ============================ Pack IR - retrieval / ranking + token overlap ============================


def _byq(qs, rks, rls):
    per = {}
    for q, r, rel in zip(qs, rks, rls):
        per.setdefault(q, []).append((r, rel))
    for q in per:
        per[q].sort(key=lambda t: t[0])
    return list(per.values())


def ref_r_precision():
    vals = []
    for rows in _byq(queries, ranks, rels_bin):
        rr = sum(1 for _, rel in rows if rel > 0)
        if rr:
            vals.append(sum(1 for _, rel in rows[:rr] if rel > 0) / rr)
    return float(np.mean(vals))


def ref_map():
    vals = []
    for rows in _byq(queries, ranks, rels_bin):
        rr = sum(1 for _, rel in rows if rel > 0)
        if not rr:
            continue
        h, ap = 0, 0.0
        for i, (_, rel) in enumerate(rows, start=1):
            if rel > 0:
                h += 1
                ap += h / i
        vals.append(ap / rr)
    return float(np.mean(vals))


def ref_f1_at_k(k):
    vals = []
    for rows in _byq(queries, ranks, rels_bin):
        rr = sum(1 for _, rel in rows if rel > 0)
        if not rr:
            continue
        hits = sum(1 for _, rel in rows[:k] if rel > 0)
        pr, rc = hits / k, hits / rr
        vals.append(2 * pr * rc / (pr + rc) if (pr + rc) > 0 else 0.0)
    return float(np.mean(vals))


def ref_fallout_at_k(k):
    vals = []
    for rows in _byq(queries, ranks, rels_bin):
        nr = sum(1 for _, rel in rows if rel <= 0)
        if nr:
            vals.append(sum(1 for _, rel in rows[:k] if rel <= 0) / nr)
    return float(np.mean(vals))


def ref_rbp(p):
    vals = []
    for rows in _byq(queries, ranks, rels_bin):
        s, pw = 0.0, 1.0
        for _, rel in rows:
            if rel > 0:
                s += pw
            pw *= p
        vals.append((1 - p) * s)
    return float(np.mean(vals))


case("r_precision", "r_precision", RETR, ref_r_precision(), atol=1e-12)
case("mean_average_precision", "mean_average_precision", RETR, ref_map(), atol=1e-12)
case("f1_at_5", "f1_at_k", dict(RETR, k=5), ref_f1_at_k(5), atol=1e-12)
case("f1_at_10", "f1_at_k", dict(RETR, k=10), ref_f1_at_k(10), atol=1e-12)
case("fallout_at_5", "fallout_at_k", dict(RETR, k=5), ref_fallout_at_k(5), atol=1e-12)
case("rbp_08", "rbp", dict(RETR, p=0.8), ref_rbp(0.8), atol=1e-11)

# token-overlap text metrics
_ARTS = {"a", "an", "the"}


def _emn(s):
    s = s.lower()
    s = "".join(ch if (ch.isalnum() or ch.isspace()) else " " for ch in s)
    return [t for t in s.split() if t not in _ARTS]


tok_preds = ["the cat sat on the mat", "a quick brown fox", "hello world foo",
             "machine learning is fun", "the answer is 42"]
tok_refs = ["the cat sat on a mat", "the quick brown fox jumps", "hello there world",
            "deep learning is fun", "the answer is forty two"]
_tf = []
for _p, _r in zip(tok_preds, tok_refs):
    _pt, _rt = _emn(_p), _emn(_r)
    _rc = {}
    for _t in _rt:
        _rc[_t] = _rc.get(_t, 0) + 1
    _c = 0
    for _t in _pt:
        if _rc.get(_t, 0) > 0:
            _c += 1
            _rc[_t] -= 1
    if not _pt and not _rt:
        _tf.append(1.0)
    elif not _pt or not _rt or _c == 0:
        _tf.append(0.0)
    else:
        _pp, _rr2 = _c / len(_pt), _c / len(_rt)
        _tf.append(2 * _pp * _rr2 / (_pp + _rr2))
case("token_f1", "token_f1", {"preds": tok_preds, "refs": tok_refs}, float(np.mean(_tf)), atol=1e-12)
_tj = []
_td = []
for _p, _r in zip(tok_preds, tok_refs):
    _a, _b = set(_p.split()), set(_r.split())
    _u = len(_a | _b)
    _tj.append(len(_a & _b) / _u if _u else 0.0)
    _dd = len(_a) + len(_b)
    _td.append(2 * len(_a & _b) / _dd if _dd else 1.0)
case("token_jaccard", "token_jaccard", {"preds": tok_preds, "refs": tok_refs}, float(np.mean(_tj)), atol=1e-12)
case("token_dice", "token_dice", {"preds": tok_preds, "refs": tok_refs}, float(np.mean(_td)), atol=1e-12)

# ============================ Pack FI - fixed-income analytics ============================

from scipy.optimize import brentq  # noqa: E402

fi_cf = [5.0, 5.0, 5.0, 5.0, 105.0]
fi_t = [1.0, 2.0, 3.0, 4.0, 5.0]
fi_y = 0.04
fi_args = {"cashflow": fi_cf, "time": fi_t, "ytm": fi_y}
fi_pv = [cf / (1 + fi_y) ** t for cf, t in zip(fi_cf, fi_t)]
fi_price = sum(fi_pv)
fi_mac = sum(t * v for t, v in zip(fi_t, fi_pv)) / fi_price
fi_mod = fi_mac / (1 + fi_y)
fi_cvx = sum(t * (t + 1) * v for t, v in zip(fi_t, fi_pv)) / (fi_price * (1 + fi_y) ** 2)
fi_dv01 = fi_mod * fi_price * 1e-4
fi_wal = sum(t * cf for t, cf in zip(fi_t, fi_cf)) / sum(fi_cf)
case("bond_price", "bond_price", fi_args, fi_price, atol=1e-9)
case("macaulay_duration", "macaulay_duration", fi_args, fi_mac, atol=1e-9)
case("modified_duration", "modified_duration", fi_args, fi_mod, atol=1e-9)
case("convexity", "convexity", fi_args, fi_cvx, atol=1e-9)
case("dv01", "dv01", fi_args, fi_dv01, atol=1e-12)
case("weighted_average_life", "weighted_average_life",
     {"cashflow": fi_cf, "time": fi_t}, fi_wal, atol=1e-9)
fi_target = 100.0
fi_ytm = brentq(lambda y: sum(cf / (1 + y) ** t for cf, t in zip(fi_cf, fi_t)) - fi_target,
                -0.99, 10.0, xtol=1e-13)
case("yield_to_maturity", "yield_to_maturity",
     {"cashflow": fi_cf, "time": fi_t, "price": fi_target}, fi_ytm, atol=1e-9)

# ============================ Pack OPT - Black-Scholes options & Greeks ============================
# Independent reference: a closed-form Black-Scholes (no dividend, q=0) on scipy.stats.norm,
# aggregated to a signed-quantity book; implied vol recovered with scipy.optimize.brentq.

from scipy.stats import norm as _spn  # noqa: E402
import math as _opt_m  # noqa: E402

opt_S = [100.0, 95.0, 110.0]
opt_K = [100.0, 90.0, 105.0]
opt_T = [0.5, 1.0, 0.25]
opt_sig = [0.20, 0.35, 0.15]
opt_r = [0.03, 0.03, 0.03]
opt_qty = [10.0, -5.0, 8.0]


def _opt_d1d2(s, k, t, v, r):
    rt = v * _opt_m.sqrt(t)
    d1 = (_opt_m.log(s / k) + (r + 0.5 * v * v) * t) / rt
    return d1, d1 - rt


def _opt_px(s, k, t, v, r, c):
    d1, d2 = _opt_d1d2(s, k, t, v, r)
    disc = _opt_m.exp(-r * t)
    if c:
        return s * _spn.cdf(d1) - k * disc * _spn.cdf(d2)
    return k * disc * _spn.cdf(-d2) - s * _spn.cdf(-d1)


def _opt_delta(s, k, t, v, r, c):
    d1, _ = _opt_d1d2(s, k, t, v, r)
    return _spn.cdf(d1) if c else _spn.cdf(d1) - 1.0


def _opt_gamma(s, k, t, v, r, c):
    d1, _ = _opt_d1d2(s, k, t, v, r)
    return _spn.pdf(d1) / (s * v * _opt_m.sqrt(t))


def _opt_vega(s, k, t, v, r, c):
    d1, _ = _opt_d1d2(s, k, t, v, r)
    return s * _spn.pdf(d1) * _opt_m.sqrt(t)


def _opt_theta(s, k, t, v, r, c):
    d1, d2 = _opt_d1d2(s, k, t, v, r)
    disc = _opt_m.exp(-r * t)
    decay = -s * _spn.pdf(d1) * v / (2.0 * _opt_m.sqrt(t))
    if c:
        return decay - r * k * disc * _spn.cdf(d2)
    return decay + r * k * disc * _spn.cdf(-d2)


def _opt_rho(s, k, t, v, r, c):
    d1, d2 = _opt_d1d2(s, k, t, v, r)
    disc = _opt_m.exp(-r * t)
    if c:
        return k * t * disc * _spn.cdf(d2)
    return -k * t * disc * _spn.cdf(-d2)


def _opt_vanna(s, k, t, v, r, c):
    d1, d2 = _opt_d1d2(s, k, t, v, r)
    return -_spn.pdf(d1) * d2 / v


def _opt_volga(s, k, t, v, r, c):
    d1, d2 = _opt_d1d2(s, k, t, v, r)
    return s * _spn.pdf(d1) * _opt_m.sqrt(t) * d1 * d2 / v


def _opt_book(fn, c):
    return float(sum(qq * fn(s, k, t, v, r, c)
                     for s, k, t, v, r, qq in zip(opt_S, opt_K, opt_T, opt_sig, opt_r, opt_qty)))


def _opt_args(c):
    return {"S": opt_S, "K": opt_K, "T": opt_T, "sigma": opt_sig, "r": opt_r, "qty": opt_qty, "is_call": c}


case("bs_value_call", "bs_value", _opt_args(True), _opt_book(_opt_px, True), atol=1e-9)
case("bs_value_put", "bs_value", _opt_args(False), _opt_book(_opt_px, False), atol=1e-9)
case("bs_delta_call", "bs_delta", _opt_args(True), _opt_book(_opt_delta, True), atol=1e-10)
case("bs_delta_put", "bs_delta", _opt_args(False), _opt_book(_opt_delta, False), atol=1e-10)
case("bs_gamma", "bs_gamma", _opt_args(True), _opt_book(_opt_gamma, True), atol=1e-12)
case("bs_vega", "bs_vega", _opt_args(True), _opt_book(_opt_vega, True), atol=1e-9)
case("bs_theta_call", "bs_theta", _opt_args(True), _opt_book(_opt_theta, True), atol=1e-9)
case("bs_theta_put", "bs_theta", _opt_args(False), _opt_book(_opt_theta, False), atol=1e-9)
case("bs_rho_call", "bs_rho", _opt_args(True), _opt_book(_opt_rho, True), atol=1e-9)
case("bs_rho_put", "bs_rho", _opt_args(False), _opt_book(_opt_rho, False), atol=1e-9)
case("bs_vanna", "bs_vanna", _opt_args(True), _opt_book(_opt_vanna, True), atol=1e-10)
case("bs_volga", "bs_volga", _opt_args(True), _opt_book(_opt_volga, True), atol=1e-9)

# implied vol: price each call at a known sigma, recover it with brentq, average across rows
iv_price = [_opt_px(s, k, t, v, r, True)
            for s, k, t, v, r in zip(opt_S, opt_K, opt_T, opt_sig, opt_r)]
iv_rec = [brentq(lambda v, s=s, k=k, t=t, r=r, p=p: _opt_px(s, k, t, v, r, True) - p,
                 1e-6, 10.0, xtol=1e-13)
          for s, k, t, r, p in zip(opt_S, opt_K, opt_T, opt_r, iv_price)]
iv_mean = float(sum(iv_rec) / len(iv_rec))
case("bs_implied_vol", "bs_implied_vol",
     {"S": opt_S, "K": opt_K, "T": opt_T, "r": opt_r, "price": iv_price, "is_call": True},
     iv_mean, atol=1e-8)

# ============================ write ============================

doc = {
    "comment": "Reference vectors for the SOTA recipe validation suite. Generated by "
               "calibration/gen_reference_vectors.py - do not edit by hand.",
    "generators": {"numpy": np.__version__, "scipy": __import__("scipy").__version__,
                   "sklearn": __import__("sklearn").__version__},
    "n_cases": len(CASES),
    "cases": CASES,
}
with open(os.path.abspath(OUT), "w") as fh:
    json.dump(doc, fh, indent=1)
print("wrote %d cases -> %s" % (len(CASES), os.path.abspath(OUT)))
