"""gen_reference_vectors.py - generate assets/reference_vectors.json from NumPy/SciPy/sklearn.

This is the SOTA validation harness for the recipe library: every numeric kernel that backs a
recipe is checked against the published reference implementation (scikit-learn for ML metrics,
SciPy for statistics and special functions, NumPy for quantiles/aggregates, the HumanEval paper
estimator for pass@k, the SQuAD eval script for normalized exact-match, Guo et al. 2017 for ECE).

Run it with a venv that has numpy, scipy, scikit-learn:
    /path/to/venv/bin/python gen_reference_vectors.py
The committed JSON is what scripts/tests/test_recipes_sota.py validates against - the test
suite itself stays pure stdlib, per the repo rule. Datasets are generated by a fixed-seed LCG
(never random.random), so re-running reproduces the identical file.
"""
import json
import os

import numpy as np
from scipy import stats, special
import sklearn.metrics as skm

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "assets", "reference_vectors.json")

CASES = []


def case(cid, kind, args, expected, atol=1e-12, rtol=1e-12):
    CASES.append({"id": cid, "kind": kind, "args": args, "expected": float(expected),
                  "atol": atol, "rtol": rtol})


# ---------------- deterministic data (64-bit LCG, 53-bit uniforms) ----------------

def uniforms(seed, n, lo=0.0, hi=1.0):
    state = seed & ((1 << 64) - 1)
    out = []
    for _ in range(n):
        state = (state * 6364136223846793005 + 1442695040888963407) % (1 << 64)
        out.append(lo + (hi - lo) * (state >> 11) / float(1 << 53))
    return out


# ============================ existing 15 recipes ============================

rets = uniforms(1, 252, -0.03, 0.035)
case("total_return", "total_return", {"rets": rets}, np.prod(1.0 + np.array(rets)) - 1.0, atol=1e-9, rtol=1e-9)
sr = np.mean(rets) / np.std(rets, ddof=1) * np.sqrt(252.0)
case("sharpe_252", "sharpe", {"rets": rets, "periods": 252}, sr, atol=1e-10)
eq = np.cumprod(1.0 + np.array(rets))
peaks = np.maximum.accumulate(eq)
case("max_drawdown", "max_drawdown", {"rets": rets}, float(np.min(eq / peaks - 1.0)), atol=1e-12)

target = uniforms(2, 300, -5.0, 10.0)
noise = uniforms(3, 300, -1.0, 1.0)
pred = [t + e for t, e in zip(target, noise)]
case("rmse", "rmse", {"pred": pred, "actual": target},
     np.sqrt(skm.mean_squared_error(target, pred)), atol=1e-11)
case("mae", "mae", {"pred": pred, "actual": target}, skm.mean_absolute_error(target, pred), atol=1e-11)
case("r2", "r2", {"pred": pred, "actual": target}, skm.r2_score(target, pred), atol=1e-11)

u1 = uniforms(4, 400)
u2 = uniforms(5, 400)
labels = [1 if u < 0.4 else 0 for u in u1]
scores = [round(0.55 * y + 0.45 * u, 2) for y, u in zip(labels, u2)]  # 2dp -> deliberate ties
probs = [min(max(0.62 * y + 0.38 * u, 0.02), 0.98) for y, u in zip(labels, u2)]
hard = [1 if s > 0.5 else 0 for s in scores]
case("accuracy", "accuracy", {"preds": hard, "labels": labels}, skm.accuracy_score(labels, hard))
case("precision", "precision", {"preds": hard, "labels": labels}, skm.precision_score(labels, hard))
case("recall", "recall", {"preds": hard, "labels": labels}, skm.recall_score(labels, hard))
case("f1", "f1", {"preds": hard, "labels": labels}, skm.f1_score(labels, hard))
case("auc_ties", "auc", {"scores": scores, "labels": labels}, skm.roc_auc_score(labels, scores), atol=1e-11)
case("brier", "brier", {"probs": probs, "labels": labels}, skm.brier_score_loss(labels, probs), atol=1e-12)

vals = uniforms(7, 250, 10.0, 500.0)
case("column_sum", "column_sum", {"xs": vals}, np.sum(np.array(vals)), atol=1e-8)
case("column_mean", "column_mean", {"xs": vals}, np.mean(np.array(vals)), atol=1e-10)

# ============================ Pack 1 - engineering ============================

for q in (0.25, 0.5, 0.9, 0.95, 0.99):
    case("quantile_%g" % q, "quantile", {"xs": vals, "q": q}, np.quantile(np.array(vals), q), atol=1e-10)
small = [4.0, 1.0, 3.0, 2.0]
case("quantile_small_p75", "quantile", {"xs": small, "q": 0.75}, np.quantile(np.array(small), 0.75))
case("quantile_n1", "quantile", {"xs": [42.0], "q": 0.9}, 42.0)

before = uniforms(8, 60, 80.0, 120.0)
after = uniforms(9, 75, 30.0, 50.0)
case("speedup_mean", "speedup", {"before": before, "after": after, "mode": "mean"},
     np.mean(before) / np.mean(after), atol=1e-12)
case("speedup_median", "speedup", {"before": before, "after": after, "mode": "median"},
     np.quantile(np.array(before), 0.5) / np.quantile(np.array(after), 0.5), atol=1e-12)

lat = uniforms(10, 500, 5.0, 900.0)
for q, name in ((0.5, "p50"), (0.95, "p95"), (0.99, "p99")):
    case("latency_%s" % name, "quantile", {"xs": lat, "q": q}, np.quantile(np.array(lat), q), atol=1e-10)
case("throughput", "throughput", {"durs": lat}, len(lat) / np.sum(np.array(lat)), atol=1e-13)
case("peak_memory", "peak", {"xs": lat}, np.max(np.array(lat)))

hits = [int(u * 6) if v > 0.3 else 0 for u, v in zip(uniforms(11, 320), uniforms(12, 320))]
case("test_coverage", "coverage", {"hits": [float(h) for h in hits]},
     np.count_nonzero(np.array(hits) > 0) / len(hits))
flags = [1.0 if u < 0.07 else 0.0 for u in uniforms(13, 600)]
case("error_rate_flag", "error_rate", {"flags": flags, "mode": "flag"}, np.mean(np.array(flags)))
codes = [float([200, 201, 301, 404, 500, 503][int(u * 6)]) for u in uniforms(14, 600)]
case("error_rate_4xx", "error_rate", {"flags": codes, "mode": "http4xx"},
     np.count_nonzero(np.array(codes) >= 400) / len(codes))
case("error_rate_5xx", "error_rate", {"flags": codes, "mode": "http5xx"},
     np.count_nonzero(np.array(codes) >= 500) / len(codes))

# ============================ Pack 2 - analytics ============================

case("column_median", "quantile", {"xs": vals, "q": 0.5}, np.median(np.array(vals)), atol=1e-10)

raw_ids = []
for i, u in enumerate(uniforms(15, 240)):
    if u < 0.06:
        raw_ids.append(["", "NaN", "null", "None", "NA"][i % 5])
    else:
        raw_ids.append("id-%03d" % int(u * 90))
nonnull = [s for s in raw_ids if s.strip().lower() not in ("", "nan", "na", "null", "none")]
case("null_fraction", "null_fraction", {"raw": raw_ids}, (len(raw_ids) - len(nonnull)) / len(raw_ids))
case("distinct_count", "distinct_count", {"raw": raw_ids, "include_null": False},
     float(len(set(nonnull))))
case("duplicate_count", "duplicate_count", {"raw": raw_ids},
     float(len(raw_ids) - len(set(s.strip() for s in raw_ids))))

series = uniforms(16, 24, 1000.0, 5000.0)
case("growth_period", "growth_rate", {"xs": series, "mode": "period"}, series[-1] / series[-2] - 1.0)
case("growth_total", "growth_rate", {"xs": series, "mode": "total"}, series[-1] / series[0] - 1.0)

share_flags = [1.0 if u < 0.42 else 0.0 for u in uniforms(17, 800)]
case("ratio_share", "ratio_share", {"flags": share_flags}, np.mean(np.array(share_flags)))

regions = [["West", "East", "North", "South"][int(u * 4)] for u in uniforms(18, 300)]
amounts = uniforms(19, 300, 50.0, 2000.0)
west = [a for r, a in zip(regions, amounts) if r == "West"]
east = [a for r, a in zip(regions, amounts) if r == "East"]
case("groupby_sum_west", "groupby", {"groups": regions, "values": amounts, "agg": "sum", "label": "West"},
     np.sum(np.array(west)), atol=1e-9)
case("groupby_mean_east", "groupby", {"groups": regions, "values": amounts, "agg": "mean", "label": "East"},
     np.mean(np.array(east)), atol=1e-10)

# ============================ Pack 3 - ML & RAG evals ============================

# retrieval corpus: 25 queries, 8-20 ranked docs each, binary + graded relevance
queries, ranks, rels_bin, rels_grad = [], [], [], []
for qi in range(25):
    depth = 8 + int(uniforms(100 + qi, 1)[0] * 13)
    us = uniforms(200 + qi, depth)
    for r in range(1, depth + 1):
        queries.append("q%02d" % qi)
        ranks.append(float(r))
        rels_bin.append(1.0 if us[r - 1] < 0.25 else 0.0)
        rels_grad.append(float(int(us[r - 1] * 4)))  # graded 0..3


def ref_recall_at_k(k):
    per, out = {}, []
    for q, r, rel in zip(queries, ranks, rels_bin):
        per.setdefault(q, []).append((r, rel))
    for q in per:
        rows = sorted(per[q])
        tot = sum(1 for _, rel in rows if rel > 0)
        if tot:
            out.append(sum(1 for _, rel in rows[:k] if rel > 0) / tot)
    return float(np.mean(out))


def ref_ndcg_at_k(k, rel_list, exp_gain):
    per, out = {}, []
    for q, r, rel in zip(queries, ranks, rel_list):
        per.setdefault(q, []).append((r, rel))
    for q in per:
        rows = sorted(per[q])
        rel_arr = np.array([rel for _, rel in rows])[None, :]
        score_arr = -np.array([r for r, _ in rows])[None, :]
        if exp_gain:
            g = np.power(2.0, np.array([rel for _, rel in rows])) - 1.0
            disc = 1.0 / np.log2(np.arange(2, len(rows) + 2))
            dcg = float(np.sum((g * disc)[:k]))
            ideal = np.sort(g)[::-1]
            idcg = float(np.sum((ideal * disc)[:k]))
            if idcg > 0:
                out.append(dcg / idcg)
        else:
            if np.sum(rel_arr) > 0:
                out.append(float(skm.ndcg_score(rel_arr, score_arr, k=k)))
    return float(np.mean(out))


def ref_mrr(k=None):
    per, out = {}, []
    for q, r, rel in zip(queries, ranks, rels_bin):
        per.setdefault(q, []).append((r, rel))
    for q in per:
        rows = sorted(per[q])
        rows = rows if k is None else rows[:k]
        rr = 0.0
        for pos, (_, rel) in enumerate(rows, 1):
            if rel > 0:
                rr = 1.0 / pos
                break
        out.append(rr)
    return float(np.mean(out))


def ref_hit_at_k(k):
    per = {}
    for q, r, rel in zip(queries, ranks, rels_bin):
        per.setdefault(q, []).append((r, rel))
    hit = sum(1 for q in per if any(rel > 0 for _, rel in sorted(per[q])[:k]))
    return hit / len(per)


RETR = {"queries": queries, "ranks": ranks, "rels": rels_bin}
RETR_G = {"queries": queries, "ranks": ranks, "rels": rels_grad}
case("recall_at_5", "recall_at_k", dict(RETR, k=5), ref_recall_at_k(5), atol=1e-12)
case("recall_at_10", "recall_at_k", dict(RETR, k=10), ref_recall_at_k(10), atol=1e-12)
case("ndcg_at_10_linear", "ndcg_at_k", dict(RETR_G, k=10, gain="linear"),
     ref_ndcg_at_k(10, rels_grad, False), atol=1e-10)
case("ndcg_at_10_exp", "ndcg_at_k", dict(RETR_G, k=10, gain="exp"),
     ref_ndcg_at_k(10, rels_grad, True), atol=1e-10)
case("ndcg_at_5_linear_bin", "ndcg_at_k", dict(RETR, k=5, gain="linear"),
     ref_ndcg_at_k(5, rels_bin, False), atol=1e-10)
case("mrr", "mrr", dict(RETR, k=None), ref_mrr(), atol=1e-12)
case("mrr_at_10", "mrr", dict(RETR, k=10), ref_mrr(10), atol=1e-12)
case("hit_at_5", "hit_at_k", dict(RETR, k=5), ref_hit_at_k(5))

# pass@k (HumanEval unbiased estimator, Chen et al. 2021)
problems, corrects = [], []
ccounts = [0, 1, 2, 3, 5, 7, 10, 4, 0, 10, 6, 8]
for pi, c in enumerate(ccounts):
    for s in range(10):
        problems.append("prob%02d" % pi)
        corrects.append(1.0 if s < c else 0.0)


def ref_pass_at_k(n, c, k):
    if n - c < k:
        return 1.0
    return 1.0 - np.prod(1.0 - k / np.arange(n - c + 1, n + 1))


for k in (1, 5, 10):
    exp = float(np.mean([ref_pass_at_k(10, c, k) for c in ccounts]))
    case("pass_at_%d" % k, "pass_at_k", {"problems": problems, "corrects": corrects, "k": k},
         exp, atol=1e-12)

# multiclass
mc_labels = [int(u * 4) for u in uniforms(30, 500)]
mc_preds = [y if v < 0.7 else int(w * 4) for y, v, w in zip(mc_labels, uniforms(31, 500), uniforms(32, 500))]
case("macro_f1", "macro_f1", {"preds": [float(p) for p in mc_preds], "labels": [float(y) for y in mc_labels]},
     skm.f1_score(mc_labels, mc_preds, average="macro", zero_division=0), atol=1e-12)
case("micro_f1", "micro_f1", {"preds": [float(p) for p in mc_preds], "labels": [float(y) for y in mc_labels]},
     skm.f1_score(mc_labels, mc_preds, average="micro", zero_division=0), atol=1e-12)
case("mcc_multiclass", "mcc", {"preds": [float(p) for p in mc_preds], "labels": [float(y) for y in mc_labels]},
     skm.matthews_corrcoef(mc_labels, mc_preds), atol=1e-12)
case("mcc_binary", "mcc", {"preds": [float(p) for p in hard], "labels": [float(y) for y in labels]},
     skm.matthews_corrcoef(labels, hard), atol=1e-12)
# a class present in labels but never predicted (zero_division=0 path)
zd_labels = [0.0, 1.0, 2.0, 2.0, 1.0, 0.0, 2.0, 1.0]
zd_preds = [0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0]
case("macro_f1_zero_division", "macro_f1", {"preds": zd_preds, "labels": zd_labels},
     skm.f1_score([int(x) for x in zd_labels], [int(x) for x in zd_preds], average="macro", zero_division=0))

case("pr_auc_ap", "average_precision", {"scores": scores, "labels": labels},
     skm.average_precision_score(labels, scores), atol=1e-11)
case("log_loss", "log_loss", {"probs": probs, "labels": labels, "clip": False},
     skm.log_loss(labels, probs), atol=1e-12, rtol=1e-12)


def ref_ece(p, y, bins):
    p, y = np.array(p), np.array(y)
    idx = np.clip(np.ceil(p * bins).astype(int) - 1, 0, bins - 1)
    total = 0.0
    for b in range(bins):
        m = idx == b
        if m.any():
            total += abs(y[m].mean() - p[m].mean()) * m.sum() / len(p)
    return total


case("ece_15", "ece", {"probs": probs, "labels": labels, "bins": 15}, ref_ece(probs, labels, 15), atol=1e-12)
case("ece_10", "ece", {"probs": probs, "labels": labels, "bins": 10}, ref_ece(probs, labels, 10), atol=1e-12)

# ============================ Pack 4 - statistical claims ============================

sa = uniforms(20, 40, 9.5, 11.0)
sb = uniforms(21, 55, 10.0, 12.0)
case("p_welch", "t_test_p", {"a": sa, "b": sb, "mode": "welch"},
     stats.ttest_ind(sa, sb, equal_var=False).pvalue, atol=1e-13, rtol=1e-11)
case("p_pooled", "t_test_p", {"a": sa, "b": sb, "mode": "pooled"},
     stats.ttest_ind(sa, sb, equal_var=True).pvalue, atol=1e-13, rtol=1e-11)
zstat = (np.mean(sa) - np.mean(sb)) / np.sqrt(np.var(sa, ddof=1) / len(sa) + np.var(sb, ddof=1) / len(sb))
case("p_z", "t_test_p", {"a": sa, "b": sb, "mode": "z"},
     2.0 * stats.norm.sf(abs(zstat)), atol=1e-13, rtol=1e-11)
# a close pair (p ~ large) so both tails are exercised
sc = uniforms(22, 35, 10.0, 12.0)
case("p_welch_null", "t_test_p", {"a": sc, "b": sb, "mode": "welch"},
     stats.ttest_ind(sc, sb, equal_var=False).pvalue, atol=1e-13, rtol=1e-11)

for level, dist in ((0.95, "t"), (0.99, "t"), (0.95, "z")):
    crit = stats.t.ppf(1 - (1 - level) / 2, len(sa) - 1) if dist == "t" else stats.norm.ppf(1 - (1 - level) / 2)
    exp = crit * np.std(sa, ddof=1) / np.sqrt(len(sa))
    case("ci_%s%d" % (dist, level * 100), "ci_half_width",
         {"xs": sa, "level": level, "dist": dist}, exp, atol=1e-12, rtol=1e-10)

conv_a = [1.0 if u < 0.10 else 0.0 for u in uniforms(23, 1000)]
conv_b = [1.0 if u < 0.123 else 0.0 for u in uniforms(24, 1100)]
case("lift_rel", "lift", {"a": conv_a, "b": conv_b, "mode": "relative"},
     (np.mean(conv_b) - np.mean(conv_a)) / np.mean(conv_a), atol=1e-12)
case("lift_abs", "lift", {"a": conv_a, "b": conv_b, "mode": "absolute"},
     np.mean(conv_b) - np.mean(conv_a), atol=1e-14)

# chi-square from raw (group, outcome) pairs - 2x2 (Yates on/off) and 3x3 (df>1)
g2 = [["ctrl", "treat"][int(u * 2)] for u in uniforms(25, 500)]
o2 = [("yes" if v < (0.30 if g == "ctrl" else 0.38) else "no") for g, v in zip(g2, uniforms(26, 500))]


def contingency(gs, os_):
    rows, cols_ = sorted(set(gs)), sorted(set(os_))
    return np.array([[sum(1 for g, o in zip(gs, os_) if g == r and o == c) for c in cols_] for r in rows])


t2 = contingency(g2, o2)
r_yes = stats.chi2_contingency(t2, correction=True)
r_no = stats.chi2_contingency(t2, correction=False)
case("chi2_2x2_p_yates", "chi_square", {"groups": g2, "outcomes": o2, "yates": True, "output": "p"},
     r_yes.pvalue, atol=1e-13, rtol=1e-11)
case("chi2_2x2_stat_yates", "chi_square", {"groups": g2, "outcomes": o2, "yates": True, "output": "statistic"},
     r_yes.statistic, atol=1e-11)
case("chi2_2x2_p_noyates", "chi_square", {"groups": g2, "outcomes": o2, "yates": False, "output": "p"},
     r_no.pvalue, atol=1e-13, rtol=1e-11)
g3 = [["a", "b", "c"][int(u * 3)] for u in uniforms(27, 700)]
o3 = [["x", "y", "z"][int((u + v) * 3) % 3] for u, v in zip(uniforms(28, 700), uniforms(29, 700))]
t3 = contingency(g3, o3)
r3 = stats.chi2_contingency(t3, correction=True)  # df>1 -> correction is a no-op (scipy)
case("chi2_3x3_p", "chi_square", {"groups": g3, "outcomes": o3, "yates": True, "output": "p"},
     r3.pvalue, atol=1e-13, rtol=1e-11)
case("chi2_3x3_stat", "chi_square", {"groups": g3, "outcomes": o3, "yates": True, "output": "statistic"},
     r3.statistic, atol=1e-10)

cx = [round(v, 1) for v in uniforms(33, 80, 0.0, 30.0)]   # 1dp -> ties for the midrank path
cy = [x * 0.7 + e for x, e in zip(cx, uniforms(34, 80, -4.0, 4.0))]
case("pearson", "correlation", {"xs": cx, "ys": cy, "mode": "pearson"},
     stats.pearsonr(cx, cy).statistic, atol=1e-13)
case("spearman_ties", "correlation", {"xs": cx, "ys": cy, "mode": "spearman"},
     stats.spearmanr(cx, cy).statistic, atol=1e-13)

na, nb = len(sa), len(sb)
df = na + nb - 2
sp = np.sqrt(((na - 1) * np.var(sa, ddof=1) + (nb - 1) * np.var(sb, ddof=1)) / df)
d = (np.mean(sa) - np.mean(sb)) / sp
case("cohen_d", "cohen_d", {"a": sa, "b": sb, "mode": "cohen_d"}, d, atol=1e-13)
jexact = special.gamma(df / 2.0) / (np.sqrt(df / 2.0) * special.gamma((df - 1) / 2.0))
case("hedges_g", "cohen_d", {"a": sa, "b": sb, "mode": "hedges_g"}, d * jexact, atol=1e-12)
case("glass_delta", "cohen_d", {"a": sa, "b": sb, "mode": "glass_delta"},
     (np.mean(sa) - np.mean(sb)) / np.std(sb, ddof=1), atol=1e-13)

# ============================ Pack 5 - business & finance ============================

import numpy_financial as npf  # noqa: E402

monthly = []
v = 100000.0
for u in uniforms(40, 36, -0.02, 0.045):
    v *= (1.0 + u)
    monthly.append(v)
years = (len(monthly) - 1) / 12.0
case("cagr_monthly", "cagr", {"xs": monthly, "ppy": 12.0},
     (monthly[-1] / monthly[0]) ** (1.0 / years) - 1.0, atol=1e-13)
annual = monthly[::12]
case("cagr_annual", "cagr", {"xs": annual, "ppy": 1.0},
     (annual[-1] / annual[0]) ** (1.0 / (len(annual) - 1)) - 1.0, atol=1e-13)

cfs = [-2500.0] + uniforms(41, 8, 200.0, 700.0)
case("npv_8pct", "npv", {"cashflows": cfs, "rate": 0.08}, npf.npv(0.08, cfs), atol=1e-9)
case("npv_0pct", "npv", {"cashflows": cfs, "rate": 0.0}, np.sum(np.array(cfs)), atol=1e-10)
case("irr", "irr", {"cashflows": cfs}, npf.irr(cfs), atol=1e-10)
cfs2 = [-1000.0, 400.0, 400.0, 400.0]
case("irr_simple", "irr", {"cashflows": cfs2}, npf.irr(cfs2), atol=1e-10)

churn_flags = [1.0 if u < 0.031 else 0.0 for u in uniforms(42, 900)]
case("churn", "churn_rate", {"flags": churn_flags, "mode": "churn"}, np.mean(np.array(churn_flags)))
case("retention", "churn_rate", {"flags": churn_flags, "mode": "retention"},
     1.0 - np.mean(np.array(churn_flags)))

rev = uniforms(43, 150, 100.0, 900.0)
cost = [r * u for r, u in zip(rev, uniforms(44, 150, 0.3, 0.6))]
case("margin_pct", "margin_pct", {"revenue": rev, "cost": cost},
     (np.sum(np.array(rev)) - np.sum(np.array(cost))) / np.sum(np.array(rev)), atol=1e-12)

ledger_b = uniforms(45, 220, 10.0, 400.0)
ledger_a = list(ledger_b)
ledger_a[17] += 12.5   # a deliberate 12.5 mismatch
case("reconciliation_diff", "reconciliation", {"a": ledger_a, "b": ledger_b}, 12.5, atol=1e-9)

# ============================ Pack 6 - forecasting ============================

f_actual = uniforms(46, 120, 50.0, 250.0)
f_pred = [a + e for a, e in zip(f_actual, uniforms(47, 120, -12.0, 12.0))]
case("mape", "mape", {"pred": f_pred, "actual": f_actual, "symmetric": False},
     skm.mean_absolute_percentage_error(f_actual, f_pred), atol=1e-13)
smape_ref = float(np.mean(2.0 * np.abs(np.array(f_pred) - np.array(f_actual))
                          / (np.abs(np.array(f_pred)) + np.abs(np.array(f_actual)))))
case("smape", "mape", {"pred": f_pred, "actual": f_actual, "symmetric": True}, smape_ref, atol=1e-13)


def ref_mase(pred, actual, m):
    a = np.array(actual)
    scale = np.mean(np.abs(a[m:] - a[:-m]))
    return float(np.mean(np.abs(np.array(pred) - a)) / scale)


case("mase_m1", "mase", {"pred": f_pred, "actual": f_actual, "m": 1}, ref_mase(f_pred, f_actual, 1),
     atol=1e-13)
case("mase_m12", "mase", {"pred": f_pred, "actual": f_actual, "m": 12}, ref_mase(f_pred, f_actual, 12),
     atol=1e-13)
for q in (0.1, 0.5, 0.9):
    case("pinball_q%g" % q, "pinball", {"pred": f_pred, "actual": f_actual, "q": q},
         skm.mean_pinball_loss(f_actual, f_pred, alpha=q), atol=1e-13)

# ============================ Pack 7 - quant risk & relative performance ============================

r = np.array(rets)
case("volatility", "volatility", {"rets": rets, "periods": 252},
     np.std(r, ddof=1) * np.sqrt(252.0), atol=1e-12)
dd2 = float(np.mean(np.minimum(r, 0.0) ** 2))
case("downside_dev", "downside_deviation", {"rets": rets, "periods": 252},
     np.sqrt(dd2) * np.sqrt(252.0), atol=1e-12)
case("sortino", "sortino", {"rets": rets, "periods": 252},
     np.mean(r) / np.sqrt(dd2) * np.sqrt(252.0), atol=1e-10)
eqc = np.cumprod(1.0 + r)
mdd_ref = float(np.min(eqc / np.maximum.accumulate(eqc) - 1.0))
ann_ref = float(np.prod(1.0 + r) ** (252.0 / len(r)) - 1.0)
case("calmar", "calmar", {"rets": rets, "periods": 252}, ann_ref / abs(mdd_ref), atol=1e-10)
case("var_95", "value_at_risk", {"rets": rets, "level": 0.95},
     -np.quantile(r, 0.05), atol=1e-12)
case("var_99", "value_at_risk", {"rets": rets, "level": 0.99},
     -np.quantile(r, 0.01), atol=1e-12)
tail = r[r <= np.quantile(r, 0.05)]
case("cvar_95", "cvar", {"rets": rets, "level": 0.95}, -np.mean(tail), atol=1e-13)
case("win_rate", "win_rate", {"rets": rets}, np.count_nonzero(r > 0) / len(r))
case("profit_factor", "profit_factor", {"rets": rets},
     np.sum(r[r > 0]) / -np.sum(r[r < 0]), atol=1e-12)
case("omega_0", "omega_ratio", {"rets": rets, "threshold": 0.0},
     np.sum(np.maximum(r, 0)) / np.sum(np.maximum(-r, 0)), atol=1e-12)
case("omega_001", "omega_ratio", {"rets": rets, "threshold": 0.001},
     np.sum(np.maximum(r - 0.001, 0)) / np.sum(np.maximum(0.001 - r, 0)), atol=1e-12)

bench = [0.6 * x + e for x, e in zip(rets, uniforms(50, 252, -0.012, 0.014))]
bv = np.array(bench)
beta_ref = float(np.cov(r, bv, ddof=1)[0, 1] / np.var(bv, ddof=1))
case("beta", "beta", {"rets": rets, "bench": bench}, beta_ref, atol=1e-12)
case("alpha", "alpha", {"rets": rets, "bench": bench, "periods": 252},
     (np.mean(r) - beta_ref * np.mean(bv)) * 252.0, atol=1e-11)
act = r - bv
case("tracking_error", "tracking_error", {"rets": rets, "bench": bench, "periods": 252},
     np.std(act, ddof=1) * np.sqrt(252.0), atol=1e-12)
case("information_ratio", "information_ratio", {"rets": rets, "bench": bench, "periods": 252},
     np.mean(act) / np.std(act, ddof=1) * np.sqrt(252.0), atol=1e-10)

# ============================ Pack 8 - classification & regression depth II ============================

case("balanced_accuracy", "balanced_accuracy", {"preds": hard, "labels": labels},
     skm.balanced_accuracy_score(labels, hard), atol=1e-12)
case("balanced_accuracy_mc", "balanced_accuracy",
     {"preds": [float(p) for p in mc_preds], "labels": [float(y) for y in mc_labels]},
     skm.balanced_accuracy_score(mc_labels, mc_preds), atol=1e-12)
case("cohen_kappa_mc", "cohen_kappa",
     {"preds": [float(p) for p in mc_preds], "labels": [float(y) for y in mc_labels]},
     skm.cohen_kappa_score(mc_labels, mc_preds), atol=1e-12)
tn_ = sum(1 for p, y in zip(hard, labels) if p == 0 and y == 0)
fp_ = sum(1 for p, y in zip(hard, labels) if p == 1 and y == 0)
case("specificity", "specificity", {"preds": hard, "labels": labels}, tn_ / (tn_ + fp_))
case("fbeta_2", "fbeta", {"preds": hard, "labels": labels, "beta": 2.0},
     skm.fbeta_score(labels, hard, beta=2.0), atol=1e-12)
case("fbeta_05", "fbeta", {"preds": hard, "labels": labels, "beta": 0.5},
     skm.fbeta_score(labels, hard, beta=0.5), atol=1e-12)
case("jaccard", "jaccard", {"preds": hard, "labels": labels},
     skm.jaccard_score(labels, hard), atol=1e-12)
case("weighted_f1", "weighted_f1",
     {"preds": [float(p) for p in mc_preds], "labels": [float(y) for y in mc_labels]},
     skm.f1_score(mc_labels, mc_preds, average="weighted", zero_division=0), atol=1e-12)
pos_scores = [s for s, y in zip(scores, labels) if y == 1]
neg_scores = [s for s, y in zip(scores, labels) if y == 0]
case("ks_statistic", "ks_statistic", {"scores": scores, "labels": labels},
     stats.ks_2samp(pos_scores, neg_scores).statistic, atol=1e-12)
case("gini_norm", "gini_norm", {"scores": scores, "labels": labels},
     2.0 * skm.roc_auc_score(labels, scores) - 1.0, atol=1e-11)

m_actual = uniforms(51, 200, 5.0, 300.0)
m_pred = [a * (1.0 + e) for a, e in zip(m_actual, uniforms(52, 200, -0.25, 0.25))]
case("msle", "msle", {"pred": m_pred, "actual": m_actual, "root": False},
     skm.mean_squared_log_error(m_actual, m_pred), atol=1e-12)
case("rmsle", "msle", {"pred": m_pred, "actual": m_actual, "root": True},
     np.sqrt(skm.mean_squared_log_error(m_actual, m_pred)), atol=1e-12)
case("medae", "medae", {"pred": pred, "actual": target},
     skm.median_absolute_error(target, pred), atol=1e-12)
case("max_error", "max_error", {"pred": pred, "actual": target},
     skm.max_error(target, pred), atol=1e-12)
case("explained_variance", "explained_variance", {"pred": pred, "actual": target},
     skm.explained_variance_score(target, pred), atol=1e-12)
case("wape", "wape", {"pred": f_pred, "actual": f_actual},
     np.sum(np.abs(np.array(f_pred) - np.array(f_actual))) / np.sum(np.abs(np.array(f_actual))),
     atol=1e-13)
case("forecast_bias", "forecast_bias", {"pred": f_pred, "actual": f_actual},
     (np.sum(f_pred) - np.sum(f_actual)) / np.sum(f_actual), atol=1e-13)
r2_ref = skm.r2_score(target, pred)
n_r = len(target)
case("adjusted_r2_p8", "adjusted_r2", {"pred": pred, "actual": target, "p": 8},
     1.0 - (1.0 - r2_ref) * (n_r - 1) / (n_r - 8 - 1), atol=1e-12)
rmse_ref = np.sqrt(skm.mean_squared_error(target, pred))
case("nrmse_mean", "nrmse", {"pred": pred, "actual": target, "mode": "mean"},
     rmse_ref / np.mean(target), atol=1e-12)
case("nrmse_range", "nrmse", {"pred": pred, "actual": target, "mode": "range"},
     rmse_ref / (np.max(target) - np.min(target)), atol=1e-12)
from statsmodels.stats.stattools import durbin_watson as sm_dw  # noqa: E402
resid = np.array(target) - np.array(pred)
case("durbin_watson", "durbin_watson", {"pred": pred, "actual": target},
     sm_dw(resid), atol=1e-12)

# ============================ Pack 9 - analytics & engineering depth II ============================

case("column_min", "column_min", {"xs": vals}, np.min(np.array(vals)))
case("column_max", "column_max", {"xs": vals}, np.max(np.array(vals)))
case("column_std", "column_std", {"xs": vals, "ddof": 1}, np.std(np.array(vals), ddof=1), atol=1e-11)
case("column_std_ddof0", "column_std", {"xs": vals, "ddof": 0}, np.std(np.array(vals)), atol=1e-11)
case("iqr", "iqr", {"xs": vals}, stats.iqr(np.array(vals)), atol=1e-10)
q1_, q3_ = np.quantile(np.array(vals), [0.25, 0.75])
fence = 1.5 * (q3_ - q1_)
case("outlier_count", "outlier_count", {"xs": vals, "k": 1.5},
     float(np.count_nonzero((np.array(vals) < q1_ - fence) | (np.array(vals) > q3_ + fence))))
id_counts = {}
for s_ in raw_ids:
    id_counts[s_.strip()] = id_counts.get(s_.strip(), 0) + 1
case("mode_share", "mode_share", {"raw": raw_ids}, max(id_counts.values()) / len(raw_ids))
amounts_arr = np.sort(np.array(amounts))
n_a = len(amounts_arr)
gini_ref = float(np.sum((2 * np.arange(1, n_a + 1) - n_a - 1) * amounts_arr) / (n_a * np.sum(amounts_arr)))
case("gini_coefficient", "gini_coefficient", {"xs": amounts}, gini_ref, atol=1e-12)
shares = np.array(amounts) / np.sum(amounts)
case("hhi", "hhi", {"xs": amounts}, float(np.sum(shares ** 2)), atol=1e-13)
case("entropy_bits", "entropy", {"raw": raw_ids, "base": "bits"},
     stats.entropy(list(id_counts.values()), base=2), atol=1e-12)
case("entropy_nats", "entropy", {"raw": raw_ids, "base": "nats"},
     stats.entropy(list(id_counts.values())), atol=1e-12)

case("latency_p90", "quantile", {"xs": lat, "q": 0.90}, np.quantile(np.array(lat), 0.90), atol=1e-10)
lat_arr = np.array(lat)
t_ap = 120.0
apdex_ref = (np.count_nonzero(lat_arr <= t_ap) + np.count_nonzero((lat_arr > t_ap) & (lat_arr <= 4 * t_ap)) / 2.0) / len(lat_arr)
case("apdex_t120", "apdex", {"durs": lat, "t": t_ap}, apdex_ref)
up_flags = [0.0 if u < 0.0008 else 1.0 for u in uniforms(53, 5000)]
case("uptime", "ratio_share", {"flags": up_flags}, np.mean(np.array(up_flags)))

# ============================ Pack 10 - statistical tests II ============================

ta = [round(v, 1) for v in sa]   # 1dp -> ties, forcing the tie-corrected asymptotic path
tb = [round(v, 1) for v in sb]
case("mann_whitney_p", "mann_whitney_p", {"a": ta, "b": tb},
     stats.mannwhitneyu(ta, tb, alternative="two-sided", method="asymptotic").pvalue,
     atol=1e-12, rtol=1e-10)
# the classical Kolmogorov asymptotic (kstwobign): the textbook two-sample formula;
# scipy's method='asymp' switched to the finite-n kstwo refinement in 1.5+, so the
# recipe documents and validates the classical limit explicitly
ks_d_ref = stats.ks_2samp(sa, sb).statistic
en_ref = np.sqrt(len(sa) * len(sb) / (len(sa) + len(sb)))
case("ks_p", "ks_p", {"a": sa, "b": sb}, stats.kstwobign.sf(en_ref * ks_d_ref),
     atol=1e-12, rtol=1e-9)
buckets_ref = {}
for g_, v_ in zip(regions, amounts):
    buckets_ref.setdefault(g_, []).append(v_)
f_res = stats.f_oneway(*buckets_ref.values())
case("anova_p", "anova", {"groups": regions, "values": amounts, "output": "p"},
     f_res.pvalue, atol=1e-13, rtol=1e-10)
case("anova_f", "anova", {"groups": regions, "values": amounts, "output": "statistic"},
     f_res.statistic, atol=1e-10)
from statsmodels.stats.proportion import proportions_ztest  # noqa: E402
x1 = sum(1 for v in conv_a if v != 0)
x2 = sum(1 for v in conv_b if v != 0)
_, pz = proportions_ztest([x1, x2], [len(conv_a), len(conv_b)])
case("proportion_z_p", "proportion_z_p", {"a": conv_a, "b": conv_b}, pz, atol=1e-13, rtol=1e-10)
fe_or, fe_p = stats.fisher_exact(t2)
case("fisher_exact_p", "fisher_exact_p", {"groups": g2, "outcomes": o2}, fe_p,
     atol=1e-12, rtol=1e-9)
case("odds_ratio", "odds_ratio_2x2", {"groups": g2, "outcomes": o2, "haldane": False},
     fe_or, atol=1e-12)
rr_ref = (t2[0][0] / (t2[0][0] + t2[0][1])) / (t2[1][0] / (t2[1][0] + t2[1][1]))
case("relative_risk", "relative_risk_2x2", {"groups": g2, "outcomes": o2}, rr_ref, atol=1e-12)
chi2_nc = stats.chi2_contingency(t2, correction=False).statistic
case("cramers_v_2x2", "cramers_v", {"groups": g2, "outcomes": o2},
     np.sqrt(chi2_nc / (len(g2) * 1)), atol=1e-11)
chi3_nc = stats.chi2_contingency(t3, correction=False).statistic
case("cramers_v_3x3", "cramers_v", {"groups": g3, "outcomes": o3},
     np.sqrt(chi3_nc / (len(g3) * 2)), atol=1e-11)
case("skewness", "skewness", {"xs": rets}, stats.skew(np.array(rets)), atol=1e-12)
case("kurtosis", "kurtosis", {"xs": rets}, stats.kurtosis(np.array(rets)), atol=1e-12)
jb_res = stats.jarque_bera(np.array(rets))
case("jarque_bera_p", "jarque_bera", {"xs": rets, "output": "p"}, jb_res.pvalue,
     atol=1e-13, rtol=1e-9)
case("jarque_bera_stat", "jarque_bera", {"xs": rets, "output": "statistic"},
     jb_res.statistic, atol=1e-10)
from statsmodels.tsa.stattools import acf as sm_acf  # noqa: E402
acf_ref = sm_acf(np.array(f_actual), nlags=3, adjusted=False, fft=False)
case("acf_lag1", "autocorrelation", {"xs": f_actual, "lag": 1}, acf_ref[1], atol=1e-12)
case("acf_lag3", "autocorrelation", {"xs": f_actual, "lag": 3}, acf_ref[3], atol=1e-12)

# ============================ Pack 11 - retrieval / LLM evals II ============================


def ref_precision_at_k(k):
    per = {}
    for q, rk, rel in zip(queries, ranks, rels_bin):
        per.setdefault(q, []).append((rk, rel))
    return float(np.mean([sum(1 for _, rel in sorted(rows)[:k] if rel > 0) / k
                          for rows in per.values()]))


def ref_map_at_k(k):
    per, out = {}, []
    for q, rk, rel in zip(queries, ranks, rels_bin):
        per.setdefault(q, []).append((rk, rel))
    for rows in per.values():
        rows = sorted(rows)
        total_rel = sum(1 for _, rel in rows if rel > 0)
        if total_rel == 0:
            continue
        hits, terms = 0, []
        for i, (_, rel) in enumerate(rows[:k], 1):
            if rel > 0:
                hits += 1
                terms.append(hits / i)
        out.append(sum(terms) / min(total_rel, k))
    return float(np.mean(out))


case("precision_at_5", "precision_at_k", dict(RETR, k=5), ref_precision_at_k(5), atol=1e-12)
case("precision_at_10", "precision_at_k", dict(RETR, k=10), ref_precision_at_k(10), atol=1e-12)
case("map_at_5", "map_at_k", dict(RETR, k=5), ref_map_at_k(5), atol=1e-12)
case("map_at_10", "map_at_k", dict(RETR, k=10), ref_map_at_k(10), atol=1e-12)

logprobs = [-(0.2 + u * 4.0) for u in uniforms(54, 600)]
case("perplexity", "perplexity", {"logprobs": logprobs},
     np.exp(-np.mean(np.array(logprobs))), atol=1e-10, rtol=1e-12)

import jiwer  # noqa: E402

VOCAB = ["the", "model", "ran", "fast", "on", "data", "with", "errors", "loss", "clean",
         "tokens", "noise", "result", "good", "bad", "trace"]
wer_refs, wer_hyps = [], []
for i in range(40):
    us = uniforms(300 + i, 12)
    n_words = 5 + int(us[0] * 6)
    ref_words = [VOCAB[int(us[j + 1] * 16) % 16] for j in range(n_words)]
    hyp_words = list(ref_words)
    if us[7] < 0.6 and hyp_words:
        hyp_words[int(us[8] * len(hyp_words))] = VOCAB[int(us[9] * 16) % 16]   # substitution
    if us[10] < 0.3 and len(hyp_words) > 1:
        del hyp_words[int(us[11] * len(hyp_words))]                            # deletion
    wer_refs.append(" ".join(ref_words))
    wer_hyps.append(" ".join(hyp_words))
case("wer", "wer", {"preds": wer_hyps, "refs": wer_refs, "char_level": False},
     jiwer.wer(wer_refs, wer_hyps), atol=1e-12)
case("cer", "wer", {"preds": wer_hyps, "refs": wer_refs, "char_level": True},
     jiwer.cer(wer_refs, wer_hyps), atol=1e-12)

# ============================ special-function kernels ============================

for x in (1e-300, 1e-12, 0.1, 0.5, 1.0, 1.5, 2.0, 2.718281828459045, 10.0, 1e5, 1e150, 1e300):
    case("log_%g" % x, "dlog", {"x": x}, np.log(x), atol=1e-14, rtol=1e-14)
for x in (-700.0, -100.0, -5.0, -1.0, 0.0, 1e-9, 0.5, 1.0, 10.0, 100.0, 709.0):
    case("exp_%g" % x, "dexp", {"x": x}, np.exp(x), atol=1e-300, rtol=5e-15)
for z in (1e-3, 0.1, 0.5, 1.0, 1.5, 2.0, 7.3, 100.5, 252.0, 1e4):
    case("lgamma_%g" % z, "dlgamma", {"z": z}, special.gammaln(z), atol=5e-13, rtol=5e-13)
for a in (0.5, 1.0, 2.5, 5.0, 30.0, 126.0):
    for b in (0.5, 2.0, 27.5):
        for x in (0.01, 0.3, 0.5, 0.7, 0.99):
            case("betainc_%g_%g_%g" % (a, b, x), "betainc", {"a": a, "b": b, "x": x},
                 special.betainc(a, b, x), atol=1e-13, rtol=1e-11)
for s in (0.5, 1.0, 2.5, 7.0, 50.0):
    for x in (0.01, 0.5, 2.0, 10.0, 80.0):
        case("gammaincc_%g_%g" % (s, x), "gammaincc", {"s": s, "x": x},
             special.gammaincc(s, x), atol=1e-15, rtol=1e-11)
for x in (-3.0, -1.0, -0.1, 0.0, 0.5, 1.0, 2.0, 5.0):
    case("erfc_%g" % x, "erfc", {"x": x}, special.erfc(x), atol=1e-15, rtol=1e-11)
for t in (0.5, 1.5, 2.2, 4.0):
    for dfv in (1.0, 2.0, 10.0, 29.0, 100.7):
        case("tsf2_%g_%g" % (t, dfv), "t_sf2", {"t": t, "df": dfv},
             2.0 * stats.t.sf(t, dfv), atol=1e-15, rtol=1e-11)
for x in (0.5, 3.84, 10.0, 25.0):
    for dfv in (1.0, 2.0, 5.0, 12.0):
        case("chi2sf_%g_%g" % (x, dfv), "chi2_sf", {"x": x, "df": dfv},
             stats.chi2.sf(x, dfv), atol=1e-15, rtol=1e-11)
for alpha in (0.1, 0.05, 0.01, 0.001):
    for dfv in (1.0, 5.0, 10.0, 30.0, 200.0):
        case("tppf2_%g_%g" % (alpha, dfv), "t_ppf2", {"alpha": alpha, "df": dfv},
             stats.t.ppf(1 - alpha / 2, dfv), atol=1e-12, rtol=1e-10)
for alpha in (0.1, 0.05, 0.01):
    case("zppf2_%g" % alpha, "z_ppf2", {"alpha": alpha},
         stats.norm.ppf(1 - alpha / 2), atol=1e-12, rtol=1e-12)

# ============================ write ============================

doc = {
    "comment": "Reference vectors for the SOTA recipe validation suite. Generated by "
               "calibration/gen_reference_vectors.py - do not edit by hand.",
    "generators": {"numpy": np.__version__, "scipy": __import__("scipy").__version__,
                   "sklearn": __import__("sklearn").__version__},
    "n_cases": len(CASES),
    "cases": CASES,
}
with open(os.path.abspath(OUT), "w") as fh:
    json.dump(doc, fh, indent=1)
print("wrote %d cases -> %s" % (len(CASES), os.path.abspath(OUT)))
