"""pr.init - one-command install of the Calma PR merge-gate.

    python -m pr.init [--dir .github/workflows] [--repo rikhinkavuru/calma] [--ref <sha|tag>] [--force]

writes two workflow files that adopt the gate WITHOUT vendoring pr/ or the engine:

  calma-verify-pr.yml   UNPRIVILEGED (pull_request, contents:read, no secrets). Checks out the PR head,
                        then `uses:` the PINNED calma-pr-review composite, which runs the PINNED calma
                        engine on the PR's changed result dirs in its own network-off sandbox and uploads
                        a findings bundle. Posts nothing.
  calma-comment-pr.yml  PRIVILEGED (workflow_run on the first completing; pull-requests:write +
                        checks:write). Downloads the bundle and `uses:` the PINNED calma-pr-comment
                        composite to post the inline review + summary + a GATING check-run.

The pwn-request-proof two-workflow split is preserved verbatim (never `pull_request_target`; the
privileged half never runs PR code). The pinned action @ref IS the base-pin: a PR cannot swap the
engine that grades it, because the engine comes from the immutable calma ref, not the PR head - so
pin --ref to a commit SHA, not a mutable branch. Pure stdlib; writes files, makes no network call.
"""
import argparse
import os
import sys

# SHA-pinned third-party actions (tags are mutable). Kept in lockstep with calma's own workflows.
_CHECKOUT = "actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5"        # v4
_SETUP_PY = "actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065"    # v5
_UPLOAD = "actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02"   # v4
_DOWNLOAD = "actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093"  # v4

VERIFY_NAME = "calma-verify-pr.yml"
COMMENT_NAME = "calma-comment-pr.yml"


def _pin_note(repo, ref):
    looks_like_sha = len(ref) >= 7 and all(c in "0123456789abcdef" for c in ref.lower())
    if looks_like_sha:
        return "# %s pinned to an immutable commit SHA (the @ref is the base-pin a PR can't forge)." % repo
    return ("# SECURITY: pin %s to an immutable commit SHA, not '%s' (a mutable ref lets the engine "
            "that grades a PR change under you)." % (repo, ref))


def render_verify(repo, ref):
    """The UNPRIVILEGED workflow. Read-only; checks out the PR head; runs the PINNED calma engine via the
    composite; uploads the bundle; posts nothing. No `run:` line carries a PR-controlled expansion."""
    return """# Calma merge-gate - UNPRIVILEGED half (pwn-request-proof). Generated by `python -m pr.init`.
# pull_request -> a fork PR gets a READ-ONLY token and NO secrets; re-executing its code is safe because
# the calma engine sandboxes it network-off. This job posts NOTHING; the privileged comment job does.
# NEVER switch this to pull_request_target + a head checkout (that is the pwn request).
{pin}
name: calma-verify-pr

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read          # read-only; a fork PR gets no secrets and cannot write with this token

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 45     # backstop on a job that RE-EXECUTES untrusted PR code (engine per-target
    steps:                  # timeout + the changed-target cap are the primary bounds)
      - uses: {checkout} # SHA-pinned
        with:
          persist-credentials: false                      # the PR's code can never use the token
          ref: ${{{{ github.event.pull_request.head.sha }}}}  # the PR head (the code under test)
          fetch-depth: 0                                  # need base..head for the diff
      - uses: {setup_py} # SHA-pinned
        with:
          python-version: '3.x'
      # the engine + driver come from {repo}@{ref} (PINNED), NOT the PR tree -> a PR cannot swap in its
      # own verifier; only its RESULT DIRS (the default workspace checkout) are PR-controlled.
      - uses: {repo}/.github/actions/calma-pr-review@{ref}
        with:
          base_sha: ${{{{ github.event.pull_request.base.sha }}}}
          head_sha: ${{{{ github.event.pull_request.head.sha }}}}
          pr_number: ${{{{ github.event.pull_request.number }}}}
      - uses: {upload} # SHA-pinned
        with:
          name: calma-findings
          path: ${{{{ runner.temp }}}}/calma-findings.json
          if-no-files-found: error
          retention-days: 1
""".format(pin=_pin_note(repo, ref), checkout=_CHECKOUT, setup_py=_SETUP_PY,
           upload=_UPLOAD, repo=repo, ref=ref)


def render_comment(repo, ref):
    """The PRIVILEGED workflow. workflow_run on the verify job; holds the write token; never runs PR code;
    downloads the bundle and posts the review + summary + a GATING check-run via the PINNED composite."""
    return """# Calma merge-gate - PRIVILEGED half (pwn-request-proof). Generated by `python -m pr.init`.
# workflow_run on calma-verify-pr completing -> runs in the BASE repo's trusted context (NOT the PR's
# code), so it can safely hold the write token. It treats the findings bundle as UNTRUSTED DATA. A fork
# PR never reaches these permissions.
{pin}
name: calma-comment-pr

on:
  workflow_run:
    workflows: ["calma-verify-pr"]
    types: [completed]

permissions:
  pull-requests: write    # the inline review + the summary comment
  checks: write           # the GATING check-run (failure on REFUTED / INVALIDATED / MIXED)
  contents: read

jobs:
  comment:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{{{ github.event.workflow_run.conclusion != 'cancelled' }}}}
    steps:
      - uses: {checkout} # SHA-pinned; the trusted base context, never the PR head
        with:
          persist-credentials: false
      - uses: {setup_py} # SHA-pinned
        with:
          python-version: '3.x'
      - uses: {download} # SHA-pinned
        with:
          name: calma-findings
          run-id: ${{{{ github.event.workflow_run.id }}}}
          github-token: ${{{{ secrets.GITHUB_TOKEN }}}}
          path: ${{{{ runner.temp }}}}/findings
      # expected_head is the TRUSTED head SHA of the triggering run: comment_pr REFUSES any bundle whose
      # head_sha differs, so a forged/cross-PR artifact can't steer this check-run onto another commit.
      - uses: {repo}/.github/actions/calma-pr-comment@{ref}
        with:
          bundle: ${{{{ runner.temp }}}}/findings/calma-findings.json
          expected_head: ${{{{ github.event.workflow_run.head_sha }}}}
          github_token: ${{{{ secrets.GITHUB_TOKEN }}}}
""".format(pin=_pin_note(repo, ref), checkout=_CHECKOUT, setup_py=_SETUP_PY,
           download=_DOWNLOAD, repo=repo, ref=ref)


def render(repo, ref):
    """Both workflow file bodies as {filename: text}. Pure (no I/O) so tests can assert the invariants."""
    return {VERIFY_NAME: render_verify(repo, ref), COMMENT_NAME: render_comment(repo, ref)}


def write(out_dir, repo, ref, force=False):
    """Write the two workflow files into out_dir. Refuses to clobber an existing file unless force.
    Returns (written, skipped)."""
    os.makedirs(out_dir, exist_ok=True)
    written, skipped = [], []
    for name, text in render(repo, ref).items():
        path = os.path.join(out_dir, name)
        if os.path.exists(path) and not force:
            skipped.append(path)
            continue
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text)
        written.append(path)
    return written, skipped


def main(argv=None):
    ap = argparse.ArgumentParser(prog="python -m pr.init",
                                 description="Scaffold the Calma PR merge-gate (two-workflow, pwn-request-proof).")
    ap.add_argument("--dir", default=".github/workflows", help="where to write the workflows")
    ap.add_argument("--repo", default="rikhinkavuru/calma", help="the calma repo hosting the composite actions")
    ap.add_argument("--ref", default="main",
                    help="the calma ref for the @pin - USE A COMMIT SHA (a mutable branch is unsafe)")
    ap.add_argument("--force", action="store_true", help="overwrite existing workflow files")
    a = ap.parse_args(argv)
    written, skipped = write(a.dir, a.repo, a.ref, a.force)
    for p in written:
        print("wrote %s" % p)
    for p in skipped:
        print("skipped %s (exists; pass --force to overwrite)" % p)
    pinned = _pin_note(a.repo, a.ref).startswith("# %s pinned" % a.repo)
    if not pinned:
        print("WARNING: --ref %r is a mutable ref; re-run with a commit SHA so the engine that "
              "grades a PR can't change under you." % a.ref, file=sys.stderr)
    print("\nNEXT: commit the two files, then mark the `calma` check **Required** in branch "
          "protection so a REFUTED/INVALIDATED number blocks the merge.", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
