/* The recipe catalog, mirrored from the skill registry
   (.claude/skills/calma/scripts/recipes.py — 59 recipes, every one validated against the
   published reference implementation; see references/recipes.md). A test in the skill suite
   asserts this file's ids stay in sync with the registry. */

export type Recipe = {
  id: string;
  name: string;
  claim: string; // an example claim it verifies, as a person would say it
  what: string; // what it checks, one sentence
  how: string; // how the number is rebuilt from raw outputs
  ref: string; // the reference implementation it is validated against
  conv?: string; // conventions it understands
};

export type Family = {
  key: string;
  title: string;
  blurb: string;
  recipes: Recipe[];
};

export const FAMILIES: Family[] = [
  {
    key: "trading",
    title: "Trading & backtests",
    blurb:
      "The original family: a backtest's headline numbers, rebuilt from the raw return series — never from the chart or the summary cell.",
    recipes: [
      {
        id: "total_return",
        name: "Total return",
        claim: "“+14,698% backtest”",
        what: "The compounded return of a strategy, from its raw per-period returns.",
        how: "prod(1+r) − 1 over the return column, computed with a pairwise product for bit-stable accuracy.",
        ref: "NumPy cumulative product",
      },
      {
        id: "sharpe",
        name: "Sharpe ratio",
        claim: "“Sharpe 2.1”",
        what: "Risk-adjusted return, annualized, with a sampling standard error attached.",
        how: "mean / std (ddof=1) × √periods; near-zero volatility degrades the verdict instead of dividing by noise.",
        ref: "NumPy",
        conv: "periods: 252 / 365 / 52",
      },
      {
        id: "max_drawdown",
        name: "Max drawdown",
        claim: "“max drawdown −12%”",
        what: "The worst peak-to-trough loss on the equity curve.",
        how: "Running peak vs. equity from the compounded return path; flagged path-dependent so a near-tie can never refute.",
        ref: "NumPy",
      },
    ],
  },
  {
    key: "classification",
    title: "ML classification",
    blurb:
      "The metrics every model card claims, recomputed from the raw predictions file — including the calibration and imbalance metrics that hide the most sins.",
    recipes: [
      {
        id: "accuracy",
        name: "Accuracy",
        claim: "“accuracy 0.87”",
        what: "Fraction of predictions that match the labels.",
        how: "Exact match count over n, from the prediction and label columns.",
        ref: "scikit-learn accuracy_score",
      },
      {
        id: "auc",
        name: "ROC-AUC",
        claim: "“AUC 0.91”",
        what: "Probability a positive outranks a negative, with tie handling.",
        how: "Mann–Whitney statistic with ties = 0.5, plus a DeLong sampling standard error for the tolerance budget.",
        ref: "scikit-learn roc_auc_score",
      },
      {
        id: "precision",
        name: "Precision",
        claim: "“precision 0.92”",
        what: "Of everything flagged positive, how much actually was.",
        how: "TP / (TP + FP) from exact integer confusion counts.",
        ref: "scikit-learn precision_score",
      },
      {
        id: "recall",
        name: "Recall",
        claim: "“recall 0.85”",
        what: "Of everything actually positive, how much was found.",
        how: "TP / (TP + FN) from exact integer confusion counts.",
        ref: "scikit-learn recall_score",
      },
      {
        id: "f1",
        name: "F1",
        claim: "“F1 0.84”",
        what: "Harmonic mean of precision and recall.",
        how: "2PR / (P + R) from the same exact confusion counts.",
        ref: "scikit-learn f1_score",
      },
      {
        id: "macro_f1",
        name: "Macro-F1",
        claim: "“macro F1 0.55”",
        what: "Multiclass F1 averaged equally across classes — the one that exposes a model coasting on the majority class.",
        how: "Per-class binary F1 over the union of observed classes, zero when undefined, unweighted mean.",
        ref: "scikit-learn f1_score (macro)",
      },
      {
        id: "micro_f1",
        name: "Micro-F1",
        claim: "“micro F1 0.78”",
        what: "Multiclass F1 from globally pooled counts.",
        how: "Global TP/FP/FN over all classes, one F1 from the pooled totals.",
        ref: "scikit-learn f1_score (micro)",
      },
      {
        id: "pr_auc",
        name: "PR-AUC",
        claim: "“average precision 0.62”",
        what: "Area under the precision–recall curve — the honest metric for imbalanced classes.",
        how: "Step-wise average precision with tied scores grouped at each threshold.",
        ref: "scikit-learn average_precision_score",
        conv: "average_precision / trapezoid",
      },
      {
        id: "log_loss",
        name: "Log loss",
        claim: "“log loss 0.31”",
        what: "How well the predicted probabilities fit the outcomes.",
        how: "−mean(y ln p + (1−y) ln(1−p)) on deterministic log kernels; a hard 0/1 on the wrong side degrades rather than silently clipping.",
        ref: "scikit-learn log_loss",
        conv: "exact / clip",
      },
      {
        id: "brier",
        name: "Brier score",
        claim: "“Brier 0.09”",
        what: "Mean squared error of the predicted probabilities.",
        how: "mean((p − y)²) over the probability column.",
        ref: "scikit-learn brier_score_loss",
      },
      {
        id: "mcc",
        name: "Matthews correlation",
        claim: "“MCC 0.61”",
        what: "The single correlation coefficient between predictions and truth — robust to imbalance, binary or multiclass.",
        how: "Gorodkin's multiclass MCC from exact integer sums; zero denominator returns 0.",
        ref: "scikit-learn matthews_corrcoef",
      },
      {
        id: "ece",
        name: "Calibration error (ECE)",
        claim: "“ECE 3.2%”",
        what: "Whether “90% confident” actually means right 90% of the time.",
        how: "Equal-width confidence bins; Σ (n_b/n) · |accuracy_b − confidence_b|.",
        ref: "Guo et al. 2017",
        conv: "bins=<n> (15)",
      },
    ],
  },
  {
    key: "regression",
    title: "Regression & forecasting",
    blurb:
      "Fit metrics from the raw prediction/actual pairs, plus the forecasting set — where a zero actual degrades honestly instead of being epsilon-fudged.",
    recipes: [
      {
        id: "rmse",
        name: "RMSE",
        claim: "“RMSE 4.2”",
        what: "Root mean squared prediction error.",
        how: "√(mean((p − a)²)) under correctly-rounded summation.",
        ref: "scikit-learn mean_squared_error",
      },
      {
        id: "mae",
        name: "MAE",
        claim: "“MAE 2.8”",
        what: "Mean absolute prediction error.",
        how: "mean(|p − a|) under correctly-rounded summation.",
        ref: "scikit-learn mean_absolute_error",
      },
      {
        id: "r2",
        name: "R²",
        claim: "“R² 0.93”",
        what: "Variance explained by the predictions.",
        how: "1 − SS_res / SS_tot; zero-variance targets degrade instead of dividing by zero.",
        ref: "scikit-learn r2_score",
      },
      {
        id: "mape",
        name: "MAPE / sMAPE",
        claim: "“MAPE 8.2%”",
        what: "Percentage forecast error, plain or symmetric.",
        how: "mean(|p − a| / |a|); any zero actual is a degenerate verdict, never an epsilon fudge. sMAPE: mean(2|p − a| / (|p| + |a|)).",
        ref: "scikit-learn mean_absolute_percentage_error",
        conv: "mape / smape",
      },
      {
        id: "mase",
        name: "MASE",
        claim: "“MASE 0.84”",
        what: "Forecast error scaled by the naive seasonal forecast — the scale-free standard.",
        how: "MAE / mean(|a_t − a_{t−m}|), the in-sample naive-m benchmark.",
        ref: "Hyndman & Koehler 2006",
        conv: "m=<season> (1)",
      },
      {
        id: "pinball_loss",
        name: "Pinball loss",
        claim: "“pinball loss 1.3 at q=0.9”",
        what: "Quantile forecast accuracy.",
        how: "mean(max(q(a−p), (q−1)(a−p))) at the claimed quantile.",
        ref: "scikit-learn mean_pinball_loss",
        conv: "q=<quantile> (0.5)",
      },
    ],
  },
  {
    key: "analytics",
    title: "Data & analytics",
    blurb:
      "What every data agent claims after a pipeline run: totals, medians, group-bys, distincts, nulls — and whether the merge silently dropped rows.",
    recipes: [
      {
        id: "column_sum",
        name: "Column sum",
        claim: "“total $4.2M”",
        what: "A column total — revenue, amounts, quantities.",
        how: "Correctly-rounded fsum over the raw column; the claim's own reported precision ($4.2M = ±50k) sets the tolerance.",
        ref: "NumPy sum",
      },
      {
        id: "column_mean",
        name: "Column mean",
        claim: "“average order $54”",
        what: "A column average.",
        how: "fsum / n over the raw column.",
        ref: "NumPy mean",
      },
      {
        id: "column_median",
        name: "Column median",
        claim: "“median 42”",
        what: "The 50th percentile of a column.",
        how: "NumPy's default linear-interpolation quantile at q = 0.5.",
        ref: "NumPy median",
      },
      {
        id: "percentile",
        name: "Percentile",
        claim: "“90th percentile 120”",
        what: "Any quantile of a column.",
        how: "Linear-interpolation quantile (NumPy method 7) at the claimed q.",
        ref: "NumPy quantile",
        conv: "p95 / p99.9 / q=0.9",
      },
      {
        id: "row_count",
        name: "Row count",
        claim: "“processed 10,000 rows”",
        what: "How many rows a pipeline actually produced.",
        how: "A literal count of the artifact's rows.",
        ref: "definitional",
      },
      {
        id: "groupby_aggregate",
        name: "Group-by aggregate",
        claim: "“revenue in the West was $310k”",
        what: "A per-group sum or mean.",
        how: "fsum/mean per group key from the raw rows; without a named group there is no scalar to verify, so it degrades.",
        ref: "NumPy per-group",
        conv: "sum:<group> / mean:<group>",
      },
      {
        id: "distinct_count",
        name: "Distinct count",
        claim: "“12,402 distinct users”",
        what: "Unique values in a column.",
        how: "Distinct stripped cell values, nulls dropped by default.",
        ref: "pandas nunique convention",
        conv: "drop_null / include_null",
      },
      {
        id: "duplicate_count",
        name: "Duplicate count",
        claim: "“only 3 duplicates”",
        what: "Rows that duplicate an earlier row.",
        how: "n − distinct, the pandas duplicated(keep='first') convention.",
        ref: "pandas convention",
      },
      {
        id: "null_fraction",
        name: "Null fraction",
        claim: "“missing data under 2%”",
        what: "How much of a column is actually empty.",
        how: "Fraction of cells that are empty / NaN / null tokens, from the raw strings.",
        ref: "definitional",
      },
      {
        id: "growth_rate",
        name: "Growth rate",
        claim: "“up 23% MoM”",
        what: "Period-over-period or total growth of a time-ordered column.",
        how: "last/prev − 1 (or last/first − 1 for total growth).",
        ref: "definitional",
        conv: "period / total",
      },
      {
        id: "ratio_share",
        name: "Share / ratio",
        claim: "“42% of users converted”",
        what: "The fraction of rows meeting a flag.",
        how: "Count of truthy flags over n.",
        ref: "definitional",
      },
      {
        id: "join_row_loss",
        name: "Join row loss",
        claim: "“merged without losing rows”",
        what: "Whether a merge dropped (or fanned out) rows.",
        how: "len(left) − len(joined) across two artifacts; 0 is lossless, negative is fan-out.",
        ref: "definitional",
      },
    ],
  },
  {
    key: "engineering",
    title: "Performance & engineering",
    blurb:
      "The coding-agent pack: “2.3× faster”, latency percentiles, coverage — recomputed from the raw benchmark timings and reports, not the summary line.",
    recipes: [
      {
        id: "speedup_ratio",
        name: "Speedup ratio",
        claim: "“2.3× faster”",
        what: "Before/after speedup from the raw timing runs.",
        how: "mean(before) / mean(after) — or medians — from the two timing columns.",
        ref: "NumPy",
        conv: "mean / median",
      },
      {
        id: "latency_p50",
        name: "Latency p50",
        claim: "“median latency 48ms”",
        what: "Median latency from the raw per-request durations.",
        how: "Linear-interpolation quantile at 0.50.",
        ref: "NumPy quantile",
      },
      {
        id: "latency_p95",
        name: "Latency p95",
        claim: "“p95 latency 120ms”",
        what: "Tail latency at the 95th percentile.",
        how: "Linear-interpolation quantile at 0.95.",
        ref: "NumPy quantile",
      },
      {
        id: "latency_p99",
        name: "Latency p99",
        claim: "“p99 under 250ms”",
        what: "Tail latency at the 99th percentile.",
        how: "Linear-interpolation quantile at 0.99.",
        ref: "NumPy quantile",
      },
      {
        id: "throughput",
        name: "Throughput",
        claim: "“4,200 rps”",
        what: "Operations per unit time.",
        how: "n / fsum(durations) over the raw per-op timings.",
        ref: "definitional",
      },
      {
        id: "peak_memory",
        name: "Peak memory",
        claim: "“peak memory 1.2GB”",
        what: "The maximum of a sampled memory series.",
        how: "max over the raw samples, NaN-propagating.",
        ref: "definitional",
      },
      {
        id: "test_coverage",
        name: "Test coverage",
        claim: "“coverage 87%”",
        what: "Line coverage recomputed from the report's raw per-line hit counts — not the percentage it printed.",
        how: "lines with hits > 0 over total lines.",
        ref: "coverage.py semantics",
      },
      {
        id: "error_rate",
        name: "Error rate",
        claim: "“5xx error rate 0.3%”",
        what: "Failures over totals, from the raw log rows.",
        how: "Count of error flags (or HTTP ≥400/≥500 statuses) over n.",
        ref: "definitional",
        conv: "flag / http4xx / http5xx",
      },
    ],
  },
  {
    key: "retrieval",
    title: "Retrieval, RAG & LLM evals",
    blurb:
      "Modern eval claims, from raw ranked results and per-sample grades — including the exact unbiased pass@k estimator from the HumanEval paper.",
    recipes: [
      {
        id: "recall_at_k",
        name: "Recall@k",
        claim: "“recall@10 0.84”",
        what: "How much of the relevant material the retriever surfaced in the top k.",
        how: "Per query: relevant-in-top-k over all-relevant; averaged, zero-relevant queries skipped.",
        ref: "standard IR definition",
        conv: "k=<n> (10)",
      },
      {
        id: "ndcg_at_k",
        name: "NDCG@k",
        claim: "“NDCG@10 0.71”",
        what: "Rank-discounted gain against the ideal ordering.",
        how: "DCG with 1/log₂(i+1) discounts over IDCG, linear or exponential gains, on deterministic log kernels.",
        ref: "scikit-learn ndcg_score",
        conv: "k=<n>, optional exp",
      },
      {
        id: "mrr",
        name: "MRR",
        claim: "“MRR 0.62”",
        what: "How early the first relevant result appears.",
        how: "Mean of 1/rank of the first relevant result per query; 0 when none.",
        ref: "standard IR definition",
        conv: "k=<n> (uncapped)",
      },
      {
        id: "top_k_accuracy",
        name: "Top-k accuracy",
        claim: "“top-5 accuracy 0.91”",
        what: "Hit rate: queries with at least one relevant result in the top k.",
        how: "Per-query any-relevant-in-top-k, averaged.",
        ref: "standard definition",
        conv: "k=<n> (5)",
      },
      {
        id: "exact_match",
        name: "Exact match",
        claim: "“exact match 71%”",
        what: "String-level answer accuracy, strict or SQuAD-normalized.",
        how: "Mean exact match; normalized mode lowercases, strips punctuation and articles, collapses whitespace.",
        ref: "SQuAD evaluation script",
        conv: "strict / normalized",
      },
      {
        id: "pass_at_k",
        name: "pass@k",
        claim: "“pass@1 0.47”",
        what: "Code-generation success with the unbiased estimator — not the naive fraction.",
        how: "Per problem 1 − C(n−c,k)/C(n,k) in exact integer arithmetic; fewer than k samples degrades.",
        ref: "Chen et al. 2021 (HumanEval)",
        conv: "k=<n> (1)",
      },
    ],
  },
  {
    key: "stats",
    title: "Statistical claims",
    blurb:
      "“The experiment was significant” — recomputed from the raw samples on deterministic special-function kernels that match SciPy to better than 1e-11.",
    recipes: [
      {
        id: "p_value",
        name: "p-value",
        claim: "“p = 0.003”",
        what: "Two-sided two-sample significance, recomputed from the raw observations.",
        how: "Welch (default), pooled, or z statistic; p via a deterministic incomplete-beta kernel.",
        ref: "SciPy ttest_ind",
        conv: "welch / pooled / z",
      },
      {
        id: "confidence_interval",
        name: "Confidence interval",
        claim: "“95% CI ± 0.4”",
        what: "The margin of error of a mean.",
        how: "Critical t (or z) × s/√n, with critical values from deterministic bisection inverses.",
        ref: "SciPy t.ppf",
        conv: "t95 / t99 / z95",
      },
      {
        id: "lift",
        name: "A/B lift",
        claim: "“the variant lifted conversion 12%”",
        what: "Treatment uplift over control, relative or absolute.",
        how: "(mean_B − mean_A) / mean_A from the raw per-user outcomes.",
        ref: "definitional",
        conv: "relative / absolute",
      },
      {
        id: "chi_square",
        name: "Chi-square",
        claim: "“χ² = 5.99, p < 0.05”",
        what: "Independence of two categorical variables, from the raw observation pairs — the contingency table is rebuilt, not trusted.",
        how: "Expected counts from marginals, Yates correction only at df = 1, p from a deterministic incomplete-gamma kernel.",
        ref: "SciPy chi2_contingency",
        conv: "p / statistic, ±yates",
      },
      {
        id: "correlation",
        name: "Correlation",
        claim: "“Spearman correlation 0.8”",
        what: "Pearson or Spearman association between two columns.",
        how: "fsum-centered Pearson; Spearman ranks first with ties midranked.",
        ref: "SciPy pearsonr / spearmanr",
        conv: "pearson / spearman",
      },
      {
        id: "effect_size",
        name: "Effect size",
        claim: "“Cohen's d 0.4”",
        what: "Standardized mean difference between two groups.",
        how: "Pooled-SD d, exact-gamma Hedges' g, or Glass's Δ.",
        ref: "standard formulas, exact Hedges J",
        conv: "cohen_d / hedges_g / glass_delta",
      },
    ],
  },
  {
    key: "finance",
    title: "Business & finance",
    blurb:
      "Beyond trading: the numbers that go in board decks and term sheets, rebuilt from the raw ledgers and cash flows.",
    recipes: [
      {
        id: "cagr",
        name: "CAGR",
        claim: "“monthly CAGR 23.9%”",
        what: "Compound annual growth from a time-ordered value series.",
        how: "(last/first)^(1/years) − 1 on deterministic power kernels; the period convention comes from the claim itself.",
        ref: "definitional",
        conv: "periods=<per-year>",
      },
      {
        id: "npv",
        name: "NPV",
        claim: "“NPV $310k at 8%”",
        what: "Net present value of a raw cash-flow column.",
        how: "Σ cf_t/(1+r)^t with exact integer-power expansion; no rate claimed means no verdict.",
        ref: "numpy-financial npv",
        conv: "rate=<frac>",
      },
      {
        id: "irr",
        name: "IRR",
        claim: "“IRR 18%”",
        what: "The discount rate where the cash flows break even.",
        how: "Deterministic bisection on NPV; no sign change in the flows degrades instead of guessing.",
        ref: "numpy-financial irr",
      },
      {
        id: "churn_rate",
        name: "Churn / retention",
        claim: "“churn 3.1%”",
        what: "Churned over total from the raw per-customer flags.",
        how: "Count of churn flags over n; retention is its complement.",
        ref: "definitional",
        conv: "churn / retention",
      },
      {
        id: "margin_pct",
        name: "Margin",
        claim: "“gross margin 61%”",
        what: "Margin recomputed from the raw revenue and cost rows.",
        how: "(Σ revenue − Σ cost) / Σ revenue under correctly-rounded summation.",
        ref: "definitional",
      },
      {
        id: "reconciliation_total",
        name: "Reconciliation",
        claim: "“the totals match the ledger”",
        what: "Whether two totals actually reconcile — across two files.",
        how: "fsum(A) − fsum(B) with cross-artifact bindings; 0 is reconciled, anything else is the exact discrepancy.",
        ref: "definitional",
      },
    ],
  },
];

export const RECIPE_COUNT = FAMILIES.reduce((n, f) => n + f.recipes.length, 0);
