/* The recipe catalog, mirrored from the skill registry
   (.claude/skills/calma/scripts/recipes.py — 120 recipes, every one validated against the
   published reference implementation; see references/recipes.md). A test in the skill suite
   asserts this file's ids stay in sync with the registry. */

export type Recipe = {
  id: string;
  name: string;
  claim: string; // an example claim it verifies, as a person would say it
  what: string; // what it checks, one sentence
  how: string; // how the number is rebuilt from raw outputs
  ref: string; // the reference implementation it is validated against
  conv?: string; // conventions it understands
};

export type Family = {
  key: string;
  title: string;
  blurb: string;
  recipes: Recipe[];
};

export const FAMILIES: Family[] = [
  {
    key: "trading",
    title: "Trading & backtests",
    blurb:
      "The original family: a backtest's headline numbers, rebuilt from the raw return series — never from the chart or the summary cell.",
    recipes: [
      {
        id: "total_return",
        name: "Total return",
        claim: "“+14,698% backtest”",
        what: "The compounded return of a strategy, from its raw per-period returns.",
        how: "prod(1+r) − 1 over the return column, computed with a pairwise product for bit-stable accuracy.",
        ref: "NumPy cumulative product",
      },
      {
        id: "sharpe",
        name: "Sharpe ratio",
        claim: "“Sharpe 2.1”",
        what: "Risk-adjusted return, annualized, with a sampling standard error attached.",
        how: "mean / std (ddof=1) × √periods; near-zero volatility degrades the verdict instead of dividing by noise.",
        ref: "NumPy",
        conv: "periods: 252 / 365 / 52",
      },
      {
        id: "max_drawdown",
        name: "Max drawdown",
        claim: "“max drawdown −12%”",
        what: "The worst peak-to-trough loss on the equity curve.",
        how: "Running peak vs. equity from the compounded return path; flagged path-dependent so a near-tie can never refute.",
        ref: "NumPy",
      },
      {
        id: "volatility",
        name: "Volatility",
        claim: "“annualized vol 18%”",
        what: "Annualized standard deviation of returns.",
        how: "std(ddof=1) × √periods over the raw return column.",
        ref: "NumPy",
        conv: "periods: 252 / 365 / 52",
      },
      {
        id: "sortino",
        name: "Sortino ratio",
        claim: "“Sortino 2.4”",
        what: "Return per unit of downside risk — upside volatility doesn't count against you.",
        how: "mean / √(mean(min(r,0)²)) × √periods, target 0, full-sample denominator.",
        ref: "standard definition (documented convention)",
        conv: "periods: 252 / 365 / 52",
      },
      {
        id: "calmar",
        name: "Calmar ratio",
        claim: "“Calmar 1.1”",
        what: "Annualized return against the worst drawdown.",
        how: "CAGR-style annualized return / |max drawdown|; path-dependent flagged.",
        ref: "standard definition",
      },
      {
        id: "downside_deviation",
        name: "Downside deviation",
        claim: "“downside deviation 9%”",
        what: "Volatility of only the losing periods.",
        how: "√(mean(min(r,0)²)) × √periods.",
        ref: "standard definition",
      },
      {
        id: "value_at_risk",
        name: "Value at risk",
        claim: "“95% VaR 2.1%”",
        what: "The loss the portfolio shouldn't exceed at the stated confidence — historical method.",
        how: "−quantile(returns, 1−level), reported as a positive loss; level parsed from the claim.",
        ref: "NumPy quantile (historical VaR)",
        conv: "p95 (default) / p99",
      },
      {
        id: "cvar",
        name: "CVaR / expected shortfall",
        claim: "“CVaR 3.0%”",
        what: "The average loss in the tail beyond VaR — what actually happens on the bad days.",
        how: "−mean(returns ≤ VaR cut), reported positive.",
        ref: "historical expected shortfall",
        conv: "p95 (default) / p99",
      },
      {
        id: "win_rate",
        name: "Win rate",
        claim: "“win rate 58%”",
        what: "Fraction of strictly positive periods.",
        how: "count(r > 0) / n from the raw returns.",
        ref: "definitional",
      },
      {
        id: "profit_factor",
        name: "Profit factor",
        claim: "“profit factor 1.8”",
        what: "Gross gains over gross losses.",
        how: "Σ gains / |Σ losses|; a series with no losses degrades rather than dividing by zero.",
        ref: "definitional",
      },
      {
        id: "omega_ratio",
        name: "Omega ratio",
        claim: "“omega 1.4”",
        what: "Probability-weighted gains over losses around a threshold.",
        how: "Σ max(r−θ, 0) / Σ max(θ−r, 0).",
        ref: "Keating & Shadwick",
        conv: "threshold=<frac> (0)",
      },
      {
        id: "beta",
        name: "Beta",
        claim: "“beta 1.2”",
        what: "Sensitivity to the benchmark.",
        how: "cov(r, b) / var(b), sample (ddof=1), from the two raw return columns.",
        ref: "NumPy cov",
      },
      {
        id: "alpha",
        name: "Alpha",
        claim: "“alpha 4% annualized”",
        what: "Return unexplained by benchmark exposure (simple CAPM, rf = 0).",
        how: "(mean(r) − β·mean(b)) × periods.",
        ref: "CAPM definition (documented)",
        conv: "periods: 252 / 365 / 52",
      },
      {
        id: "information_ratio",
        name: "Information ratio",
        claim: "“IR 0.7”",
        what: "Active return per unit of tracking error.",
        how: "mean(r−b) / std(r−b, ddof=1) × √periods.",
        ref: "standard definition",
      },
      {
        id: "tracking_error",
        name: "Tracking error",
        claim: "“tracking error 3.1%”",
        what: "Annualized volatility of the active return.",
        how: "std(r−b, ddof=1) × √periods.",
        ref: "standard definition",
      },
      {
        id: "ulcer_index",
        name: "Ulcer index",
        claim: "“Ulcer index 5.8%”",
        what: "Drawdown depth and duration combined — the RMS of the underwater equity curve.",
        how: "√(mean(ddₜ²)) over the per-period drawdown series, peak floored at initial capital.",
        ref: "Martin & McCann (documented convention)",
      },
      {
        id: "pain_index",
        name: "Pain index",
        claim: "“pain index 4.3%”",
        what: "Average depth of the drawdown — mean time spent, and how far, underwater.",
        how: "mean(|ddₜ|) over the per-period drawdown series.",
        ref: "Becker / Zephyr (documented convention)",
      },
      {
        id: "martin_ratio",
        name: "Martin ratio (UPI)",
        claim: "“Martin ratio 13.1”",
        what: "Return per unit of ulcer — annualized return against drawdown pain.",
        how: "CAGR-style annualized return / ulcer index; path-dependent flagged.",
        ref: "Martin & McCann",
        conv: "periods: 252 / 365 / 52",
      },
      {
        id: "recovery_factor",
        name: "Recovery factor",
        claim: "“recovery factor 3.4”",
        what: "Total return earned per unit of worst drawdown.",
        how: "total return / |max drawdown|; path-dependent flagged.",
        ref: "standard definition",
      },
      {
        id: "gain_to_pain_ratio",
        name: "Gain-to-pain ratio",
        claim: "“gain-to-pain 1.8”",
        what: "Schwager's sum of returns against the sum of losses.",
        how: "sum(r) / |sum(r where r<0)|.",
        ref: "Schwager (documented convention)",
      },
      {
        id: "tail_ratio",
        name: "Tail ratio",
        claim: "“tail ratio 1.05”",
        what: "Right-tail size against left-tail size of the return distribution.",
        how: "|95th percentile| / |5th percentile| (NumPy linear quantile).",
        ref: "NumPy quantile",
      },
      {
        id: "gain_loss_ratio",
        name: "Gain/loss ratio",
        claim: "“gain/loss 1.2”",
        what: "Average winning period against the average losing period.",
        how: "mean(r>0) / |mean(r<0)|.",
        ref: "standard definition",
      },
      {
        id: "win_loss_ratio",
        name: "Win/loss ratio",
        claim: "“win/loss 1.4”",
        what: "Count of winning periods against losing periods.",
        how: "count(r>0) / count(r<0).",
        ref: "standard definition",
      },
      {
        id: "kelly_criterion",
        name: "Kelly criterion",
        claim: "“Kelly 0.18”",
        what: "Growth-optimal bet fraction implied by the win rate and payoff.",
        how: "W − (1−W)/R; W = wins/(wins+losses), R = avg win / |avg loss|.",
        ref: "standard definition (documented convention)",
      },
      {
        id: "upside_deviation",
        name: "Upside deviation",
        claim: "“upside deviation 14%”",
        what: "Annualized dispersion of the positive returns, target 0.",
        how: "√(mean(max(r,0)²)) × √periods.",
        ref: "standard definition",
        conv: "periods: 252 / 365 / 52",
      },
      {
        id: "upside_potential_ratio",
        name: "Upside potential ratio",
        claim: "“UPR 0.9”",
        what: "Upside reward per unit of downside risk, target 0.",
        how: "mean(max(r,0)) / √(mean(min(r,0)²)).",
        ref: "Sortino-van der Meer-Plantinga",
      },
      {
        id: "kappa_three",
        name: "Kappa-3",
        claim: "“Kappa-3 0.7”",
        what: "Return over the third-order lower partial moment — penalizes left-skew.",
        how: "mean(r) / (mean(max(−r,0)³))^(1/3), target 0.",
        ref: "Kaplan & Knowles",
      },
      {
        id: "cdar",
        name: "Conditional drawdown at risk",
        claim: "“CDaR 95% = 9%”",
        what: "Mean of the worst-tail drawdowns beyond the drawdown-at-risk threshold.",
        how: "mean of the drawdown series at or beyond its (1−level) quantile; loss-positive, path-dependent.",
        ref: "Chekhlov, Uryasev & Zabarankin",
        conv: "p95 / p99",
      },
      {
        id: "max_drawdown_duration",
        name: "Max drawdown duration",
        claim: "“longest drawdown 47 days”",
        what: "Longest stretch the equity curve spends below a prior peak.",
        how: "longest run of consecutive periods below the running peak; reported in periods.",
        ref: "standard definition",
      },
      {
        id: "parametric_var",
        name: "Parametric VaR",
        claim: "“1-day 95% VaR 2.4%”",
        what: "Gaussian (variance-covariance) value at risk.",
        how: "−(μ + Φ⁻¹(1−level)·σ); reported as a positive loss. Deterministic inverse-normal kernel.",
        ref: "RiskMetrics / SciPy norm",
        conv: "p95 / p99",
      },
      {
        id: "parametric_es",
        name: "Parametric expected shortfall",
        claim: "“95% ES 3.1%”",
        what: "Gaussian expected shortfall (CVaR) — average loss beyond the VaR.",
        how: "−(μ − σ·φ(z)/(1−level)), z = Φ⁻¹(1−level); loss-positive.",
        ref: "SciPy norm",
        conv: "p95 / p99",
      },
      {
        id: "cornish_fisher_var",
        name: "Cornish-Fisher VaR",
        claim: "“modified VaR 2.8%”",
        what: "Value at risk with the normal quantile expanded for skewness and kurtosis.",
        how: "Gaussian VaR with the Cornish-Fisher z-expansion in skew S and excess kurtosis K.",
        ref: "Zangari / Favre-Galeano (SciPy moments)",
        conv: "p95 / p99",
      },
      {
        id: "adjusted_sharpe_ratio",
        name: "Adjusted Sharpe ratio",
        claim: "“adjusted Sharpe 0.14”",
        what: "Per-period Sharpe penalized for negative skew and excess kurtosis.",
        how: "SR·(1 + (S/6)·SR − (K/24)·SR²), per-period; S skew, K excess kurtosis.",
        ref: "Pézier & White (SciPy moments)",
      },
      {
        id: "probabilistic_sharpe_ratio",
        name: "Probabilistic Sharpe ratio",
        claim: "“PSR 0.97”",
        what: "Probability the true Sharpe exceeds a benchmark, given track length, skew and kurtosis.",
        how: "Φ((SR−SR*)·√(T−1) / √(1 − g₃·SR + ((g₄−1)/4)·SR²)), per-period.",
        ref: "Bailey & López de Prado (SciPy)",
      },
      {
        id: "up_capture_ratio",
        name: "Up-capture ratio",
        claim: "“up-capture 105%”",
        what: "How much of the benchmark's up-market return the strategy captures.",
        how: "mean(strategy | bench>0) / mean(bench | bench>0).",
        ref: "standard definition (documented convention)",
      },
      {
        id: "down_capture_ratio",
        name: "Down-capture ratio",
        claim: "“down-capture 82%”",
        what: "How much of the benchmark's down-market loss the strategy suffers.",
        how: "mean(strategy | bench<0) / mean(bench | bench<0).",
        ref: "standard definition (documented convention)",
      },
      {
        id: "capture_ratio",
        name: "Capture ratio",
        claim: "“capture ratio 1.28”",
        what: "Up-capture relative to down-capture — asymmetry of participation.",
        how: "up-capture / down-capture.",
        ref: "standard definition",
      },
      {
        id: "treynor_ratio",
        name: "Treynor ratio",
        claim: "“Treynor 0.11”",
        what: "Annualized excess return per unit of market (systematic) risk.",
        how: "annualized mean return / β (rf=0); β = cov(r,b)/var(b), ddof=1.",
        ref: "Treynor (documented convention)",
        conv: "periods: 252 / 365 / 52",
      },
      {
        id: "r_squared",
        name: "R² vs benchmark",
        claim: "“R² 0.83 to the index”",
        what: "Share of the strategy's variance explained by the benchmark.",
        how: "Pearson correlation(r, b)².",
        ref: "NumPy",
      },
      {
        id: "active_return",
        name: "Active return",
        claim: "“active return +4.2%”",
        what: "Annualized return earned above the benchmark.",
        how: "mean(r − b) × periods.",
        ref: "standard definition",
        conv: "periods: 252 / 365 / 52",
      },
    ],
  },
  {
    key: "classification",
    title: "ML classification",
    blurb:
      "The metrics every model card claims, recomputed from the raw predictions file — including the calibration and imbalance metrics that hide the most sins.",
    recipes: [
      {
        id: "accuracy",
        name: "Accuracy",
        claim: "“accuracy 0.87”",
        what: "Fraction of predictions that match the labels.",
        how: "Exact match count over n, from the prediction and label columns.",
        ref: "scikit-learn accuracy_score",
      },
      {
        id: "auc",
        name: "ROC-AUC",
        claim: "“AUC 0.91”",
        what: "Probability a positive outranks a negative, with tie handling.",
        how: "Mann–Whitney statistic with ties = 0.5, plus a DeLong sampling standard error for the tolerance budget.",
        ref: "scikit-learn roc_auc_score",
      },
      {
        id: "precision",
        name: "Precision",
        claim: "“precision 0.92”",
        what: "Of everything flagged positive, how much actually was.",
        how: "TP / (TP + FP) from exact integer confusion counts.",
        ref: "scikit-learn precision_score",
      },
      {
        id: "recall",
        name: "Recall",
        claim: "“recall 0.85”",
        what: "Of everything actually positive, how much was found.",
        how: "TP / (TP + FN) from exact integer confusion counts.",
        ref: "scikit-learn recall_score",
      },
      {
        id: "f1",
        name: "F1",
        claim: "“F1 0.84”",
        what: "Harmonic mean of precision and recall.",
        how: "2PR / (P + R) from the same exact confusion counts.",
        ref: "scikit-learn f1_score",
      },
      {
        id: "macro_f1",
        name: "Macro-F1",
        claim: "“macro F1 0.55”",
        what: "Multiclass F1 averaged equally across classes — the one that exposes a model coasting on the majority class.",
        how: "Per-class binary F1 over the union of observed classes, zero when undefined, unweighted mean.",
        ref: "scikit-learn f1_score (macro)",
      },
      {
        id: "micro_f1",
        name: "Micro-F1",
        claim: "“micro F1 0.78”",
        what: "Multiclass F1 from globally pooled counts.",
        how: "Global TP/FP/FN over all classes, one F1 from the pooled totals.",
        ref: "scikit-learn f1_score (micro)",
      },
      {
        id: "pr_auc",
        name: "PR-AUC",
        claim: "“average precision 0.62”",
        what: "Area under the precision–recall curve — the honest metric for imbalanced classes.",
        how: "Step-wise average precision with tied scores grouped at each threshold.",
        ref: "scikit-learn average_precision_score",
        conv: "average_precision / trapezoid",
      },
      {
        id: "log_loss",
        name: "Log loss",
        claim: "“log loss 0.31”",
        what: "How well the predicted probabilities fit the outcomes.",
        how: "−mean(y ln p + (1−y) ln(1−p)) on deterministic log kernels; a hard 0/1 on the wrong side degrades rather than silently clipping.",
        ref: "scikit-learn log_loss",
        conv: "exact / clip",
      },
      {
        id: "brier",
        name: "Brier score",
        claim: "“Brier 0.09”",
        what: "Mean squared error of the predicted probabilities.",
        how: "mean((p − y)²) over the probability column.",
        ref: "scikit-learn brier_score_loss",
      },
      {
        id: "mcc",
        name: "Matthews correlation",
        claim: "“MCC 0.61”",
        what: "The single correlation coefficient between predictions and truth — robust to imbalance, binary or multiclass.",
        how: "Gorodkin's multiclass MCC from exact integer sums; zero denominator returns 0.",
        ref: "scikit-learn matthews_corrcoef",
      },
      {
        id: "ece",
        name: "Calibration error (ECE)",
        claim: "“ECE 3.2%”",
        what: "Whether “90% confident” actually means right 90% of the time.",
        how: "Equal-width confidence bins; Σ (n_b/n) · |accuracy_b − confidence_b|.",
        ref: "Guo et al. 2017",
        conv: "bins=<n> (15)",
      },
      {
        id: "balanced_accuracy",
        name: "Balanced accuracy",
        claim: "“balanced accuracy 0.71”",
        what: "Accuracy that a majority-class model can't fake — mean per-class recall.",
        how: "Recall computed per class over the observed classes, unweighted mean.",
        ref: "scikit-learn balanced_accuracy_score",
      },
      {
        id: "cohen_kappa",
        name: "Cohen's kappa",
        claim: "“kappa 0.64”",
        what: "Agreement beyond what chance would produce, binary or multiclass.",
        how: "(p_observed − p_expected) / (1 − p_expected) with exact integer marginals.",
        ref: "scikit-learn cohen_kappa_score",
      },
      {
        id: "specificity",
        name: "Specificity",
        claim: "“specificity 0.95”",
        what: "Of everything actually negative, how much was correctly left alone.",
        how: "TN / (TN + FP) from exact confusion counts.",
        ref: "definitional (confusion matrix)",
      },
      {
        id: "fbeta",
        name: "F-beta",
        claim: "“F2 score 0.66”",
        what: "F-score weighted toward recall (F2) or precision (F0.5) — beta parsed from the claim.",
        how: "(1+β²)PR / (β²P + R) from exact confusion counts.",
        ref: "scikit-learn fbeta_score",
        conv: "beta=<v> (1)",
      },
      {
        id: "jaccard",
        name: "Jaccard / IoU",
        claim: "“IoU 0.58”",
        what: "Overlap between predicted and actual positives.",
        how: "TP / (TP + FP + FN).",
        ref: "scikit-learn jaccard_score",
      },
      {
        id: "weighted_f1",
        name: "Weighted F1",
        claim: "“weighted F1 0.69”",
        what: "Multiclass F1 weighted by class support.",
        how: "Per-class F1 × support share, summed; zero_division=0.",
        ref: "scikit-learn f1_score (weighted)",
      },
      {
        id: "ks_statistic",
        name: "KS statistic",
        claim: "“KS 0.31”",
        what: "The credit-scoring KS: how separated the score distributions of goods and bads are.",
        how: "max |ECDF_pos − ECDF_neg| over the pooled score thresholds.",
        ref: "SciPy ks_2samp statistic",
      },
      {
        id: "gini_norm",
        name: "Gini (accuracy ratio)",
        claim: "“Gini 0.42”",
        what: "The credit-model Gini — a rescaled AUC.",
        how: "2·AUC − 1 from the Mann-Whitney AUC.",
        ref: "scikit-learn roc_auc_score (rescaled)",
      },
      {
        id: "g_mean",
        name: "Geometric mean (G-mean)",
        claim: "“G-mean 0.81”",
        what: "Balance of sensitivity and specificity — the imbalanced-data score.",
        how: "√(TPR · TNR) from the confusion counts.",
        ref: "sklearn confusion_matrix + definition",
      },
      {
        id: "youden_j",
        name: "Youden's J",
        claim: "“Youden's J 0.55”",
        what: "Informedness — the optimal-threshold criterion.",
        how: "TPR + TNR − 1.",
        ref: "sklearn confusion_matrix + definition",
      },
      {
        id: "markedness",
        name: "Markedness",
        claim: "“markedness 0.49”",
        what: "Precision-side complement of informedness.",
        how: "PPV + NPV − 1.",
        ref: "sklearn confusion_matrix + definition",
      },
      {
        id: "negative_predictive_value",
        name: "Negative predictive value",
        claim: "“NPV 0.94”",
        what: "Share of negative predictions that are truly negative.",
        how: "TN / (TN + FN).",
        ref: "sklearn confusion_matrix + definition",
      },
      {
        id: "false_positive_rate",
        name: "False positive rate",
        claim: "“FPR 0.08”",
        what: "Share of true negatives flagged positive.",
        how: "FP / (FP + TN).",
        ref: "sklearn confusion_matrix + definition",
      },
      {
        id: "false_negative_rate",
        name: "False negative rate",
        claim: "“FNR 0.12”",
        what: "Share of true positives missed.",
        how: "FN / (FN + TP).",
        ref: "sklearn confusion_matrix + definition",
      },
      {
        id: "false_discovery_rate",
        name: "False discovery rate",
        claim: "“FDR 0.15”",
        what: "Share of positive predictions that are wrong.",
        how: "FP / (FP + TP).",
        ref: "sklearn confusion_matrix + definition",
      },
      {
        id: "positive_likelihood_ratio",
        name: "Positive likelihood ratio (LR+)",
        claim: "“LR+ 7.2”",
        what: "How much a positive result raises the odds of the condition.",
        how: "TPR / FPR.",
        ref: "sklearn class_likelihood_ratios",
      },
      {
        id: "negative_likelihood_ratio",
        name: "Negative likelihood ratio (LR−)",
        claim: "“LR− 0.13”",
        what: "How much a negative result lowers the odds of the condition.",
        how: "FNR / TNR.",
        ref: "sklearn class_likelihood_ratios",
      },
      {
        id: "diagnostic_odds_ratio",
        name: "Diagnostic odds ratio",
        claim: "“DOR 55”",
        what: "Single-number discrimination — LR+ over LR−.",
        how: "(TP·TN) / (FP·FN).",
        ref: "sklearn confusion_matrix + definition",
      },
      {
        id: "threat_score",
        name: "Threat score (CSI)",
        claim: "“CSI 0.62”",
        what: "Critical success index — overlap ignoring true negatives.",
        how: "TP / (TP + FN + FP).",
        ref: "sklearn confusion_matrix + definition",
      },
      {
        id: "fowlkes_mallows",
        name: "Fowlkes-Mallows index",
        claim: "“FM 0.79”",
        what: "Geometric mean of precision and recall.",
        how: "√(PPV · TPR).",
        ref: "sklearn confusion_matrix + definition",
      },
      {
        id: "demographic_parity_difference",
        name: "Demographic parity difference",
        claim: "“DP difference 0.04”",
        what: "Largest gap in positive-prediction rate across a protected group.",
        how: "max − min selection rate over groups.",
        ref: "fairlearn demographic_parity_difference",
      },
      {
        id: "demographic_parity_ratio",
        name: "Demographic parity ratio",
        claim: "“DP ratio 0.88 (80% rule)”",
        what: "Selection-rate ratio — the four-fifths rule check.",
        how: "min / max selection rate over groups.",
        ref: "fairlearn demographic_parity_ratio",
      },
      {
        id: "equalized_odds_difference",
        name: "Equalized odds difference",
        claim: "“EO difference 0.06”",
        what: "Worst TPR-or-FPR gap across groups — error-rate fairness.",
        how: "max(TPR range, FPR range) over groups.",
        ref: "fairlearn equalized_odds_difference",
      },
      {
        id: "equalized_odds_ratio",
        name: "Equalized odds ratio",
        claim: "“EO ratio 0.82”",
        what: "Worst TPR-or-FPR ratio across groups.",
        how: "min(TPR ratio, FPR ratio) over groups.",
        ref: "fairlearn equalized_odds_ratio",
      },
      {
        id: "equal_opportunity_difference",
        name: "Equal opportunity difference",
        claim: "“EO opportunity gap 0.05”",
        what: "True-positive-rate gap across groups (recall fairness).",
        how: "max − min TPR over groups.",
        ref: "standard definition",
      },
      {
        id: "predictive_parity_difference",
        name: "Predictive parity difference",
        claim: "“predictive parity gap 0.07”",
        what: "Precision (PPV) gap across groups.",
        how: "max − min PPV over groups.",
        ref: "standard definition",
      },
      {
        id: "fpr_parity_difference",
        name: "FPR parity difference",
        claim: "“FPR gap 0.04”",
        what: "False-positive-rate gap across groups.",
        how: "max − min FPR over groups.",
        ref: "standard definition",
      },
      {
        id: "accuracy_parity_difference",
        name: "Accuracy parity difference",
        claim: "“accuracy gap 0.03”",
        what: "Accuracy gap across groups.",
        how: "max − min accuracy over groups.",
        ref: "standard definition",
      },
    ],
  },
  {
    key: "regression",
    title: "Regression & forecasting",
    blurb:
      "Fit metrics from the raw prediction/actual pairs, plus the forecasting set — where a zero actual degrades honestly instead of being epsilon-fudged.",
    recipes: [
      {
        id: "rmse",
        name: "RMSE",
        claim: "“RMSE 4.2”",
        what: "Root mean squared prediction error.",
        how: "√(mean((p − a)²)) under correctly-rounded summation.",
        ref: "scikit-learn mean_squared_error",
      },
      {
        id: "mae",
        name: "MAE",
        claim: "“MAE 2.8”",
        what: "Mean absolute prediction error.",
        how: "mean(|p − a|) under correctly-rounded summation.",
        ref: "scikit-learn mean_absolute_error",
      },
      {
        id: "r2",
        name: "R²",
        claim: "“R² 0.93”",
        what: "Variance explained by the predictions.",
        how: "1 − SS_res / SS_tot; zero-variance targets degrade instead of dividing by zero.",
        ref: "scikit-learn r2_score",
      },
      {
        id: "mape",
        name: "MAPE / sMAPE",
        claim: "“MAPE 8.2%”",
        what: "Percentage forecast error, plain or symmetric.",
        how: "mean(|p − a| / |a|); any zero actual is a degenerate verdict, never an epsilon fudge. sMAPE: mean(2|p − a| / (|p| + |a|)).",
        ref: "scikit-learn mean_absolute_percentage_error",
        conv: "mape / smape",
      },
      {
        id: "mase",
        name: "MASE",
        claim: "“MASE 0.84”",
        what: "Forecast error scaled by the naive seasonal forecast — the scale-free standard.",
        how: "MAE / mean(|a_t − a_{t−m}|), the in-sample naive-m benchmark.",
        ref: "Hyndman & Koehler 2006",
        conv: "m=<season> (1)",
      },
      {
        id: "pinball_loss",
        name: "Pinball loss",
        claim: "“pinball loss 1.3 at q=0.9”",
        what: "Quantile forecast accuracy.",
        how: "mean(max(q(a−p), (q−1)(a−p))) at the claimed quantile.",
        ref: "scikit-learn mean_pinball_loss",
        conv: "q=<quantile> (0.5)",
      },
      {
        id: "msle",
        name: "MSLE / RMSLE",
        claim: "“RMSLE 0.12”",
        what: "Log-scale squared error — the Kaggle standard for skewed targets.",
        how: "mean((ln(1+p) − ln(1+a))²) on deterministic log kernels; values ≤ −1 degrade.",
        ref: "scikit-learn mean_squared_log_error",
        conv: "msle / rmsle",
      },
      {
        id: "medae",
        name: "Median absolute error",
        claim: "“median absolute error 1.9”",
        what: "The robust error metric outliers can't inflate.",
        how: "median(|p − a|) with linear-interpolation quantiles.",
        ref: "scikit-learn median_absolute_error",
      },
      {
        id: "max_error",
        name: "Max error",
        claim: "“max error 4.2”",
        what: "The single worst prediction.",
        how: "max(|p − a|).",
        ref: "scikit-learn max_error",
      },
      {
        id: "explained_variance",
        name: "Explained variance",
        claim: "“explained variance 0.90”",
        what: "Variance captured, ignoring constant bias.",
        how: "1 − var(a−p) / var(a), population variances.",
        ref: "scikit-learn explained_variance_score",
      },
      {
        id: "adjusted_r2",
        name: "Adjusted R²",
        claim: "“adjusted R² 0.91 with 8 predictors”",
        what: "R² penalized for the number of predictors — kills the add-features-until-it-fits trick.",
        how: "1 − (1−R²)(n−1)/(n−p−1); predictor count from the claim, or no verdict.",
        ref: "standard formula over sklearn R²",
        conv: "p=<predictors> (required)",
      },
      {
        id: "nrmse",
        name: "Normalized RMSE",
        claim: "“NRMSE 7%”",
        what: "RMSE made scale-free.",
        how: "RMSE / mean(actual), or / range by convention.",
        ref: "standard definition",
        conv: "mean (default) / range",
      },
      {
        id: "wape",
        name: "WAPE",
        claim: "“WAPE 9.3%”",
        what: "The retail-forecasting error standard — robust where MAPE explodes.",
        how: "Σ|p − a| / Σ|a|.",
        ref: "standard definition",
      },
      {
        id: "forecast_bias",
        name: "Forecast bias",
        claim: "“2% over-forecast”",
        what: "Systematic over- or under-forecasting.",
        how: "(Σp − Σa) / Σa; positive = over-forecast.",
        ref: "standard definition",
      },
      {
        id: "durbin_watson",
        name: "Durbin-Watson",
        claim: "“DW 1.9”",
        what: "Autocorrelation left in the residuals — the classic misspecification tell.",
        how: "Σ(e_t − e_{t−1})² / Σe² on the raw residuals.",
        ref: "statsmodels durbin_watson",
      },
      {
        id: "concordance_correlation",
        name: "Concordance correlation (CCC)",
        claim: "“Lin's CCC 0.91”",
        what: "Agreement that penalizes both correlation and bias (not just fit).",
        how: "2·cov / (σ²ₚ + σ²ₐ + (μₚ − μₐ)²).",
        ref: "Lin (1989) definition",
      },
      {
        id: "huber_loss",
        name: "Huber loss",
        claim: "“Huber loss 0.42”",
        what: "Robust regression loss — quadratic near zero, linear in the tails.",
        how: "mean of ½e² for |e|≤δ, else δ(|e|−½δ).",
        ref: "standard Huber definition",
        conv: "delta=<v> (1.0)",
      },
      {
        id: "poisson_deviance",
        name: "Mean Poisson deviance",
        claim: "“Poisson deviance 0.6”",
        what: "Goodness-of-fit for count / rate models.",
        how: "2·mean(a·ln(a/p) − (a − p)).",
        ref: "scikit-learn mean_poisson_deviance",
      },
      {
        id: "gamma_deviance",
        name: "Mean Gamma deviance",
        claim: "“Gamma deviance 0.21”",
        what: "Goodness-of-fit for positive, right-skewed targets (severity models).",
        how: "2·mean(ln(p/a) + a/p − 1).",
        ref: "scikit-learn mean_gamma_deviance",
      },
      {
        id: "d2_absolute_error",
        name: "D² absolute-error score",
        claim: "“D² 0.47”",
        what: "Fraction of MAE explained over a median-only baseline (an R² for MAE).",
        how: "1 − MAE(model) / MAE(median).",
        ref: "scikit-learn d2_absolute_error_score",
      },
      {
        id: "theil_u1",
        name: "Theil's U1",
        claim: "“Theil U1 0.04”",
        what: "Bounded forecast-accuracy coefficient (0 = perfect).",
        how: "RMSE / (rms(pred) + rms(actual)).",
        ref: "standard Theil U1 definition",
      },
      {
        id: "theil_u2",
        name: "Theil's U2",
        claim: "“Theil U2 0.8”",
        what: "Forecast vs naive — below 1 beats the random walk.",
        how: "√Σ((p−a)/a₋₁)² / √Σ((a−a₋₁)/a₋₁)².",
        ref: "standard Theil U2 definition",
      },
      {
        id: "rmsse",
        name: "RMSSE",
        claim: "“RMSSE 0.6”",
        what: "Root mean squared scaled error — the M5 competition metric.",
        how: "√(mean((a−p)²) / mean((aₜ−aₜ₋₁)²)).",
        ref: "M5 (Makridakis) definition",
      },
      {
        id: "tracking_signal",
        name: "Tracking signal",
        claim: "“tracking signal 1.2”",
        what: "Cumulative bias relative to typical error — drift detector.",
        how: "Σ(p−a) / mean(|p−a|).",
        ref: "standard definition",
      },
      {
        id: "mean_directional_accuracy",
        name: "Mean directional accuracy",
        claim: "“MDA 0.68”",
        what: "How often the forecast gets the direction right.",
        how: "fraction where sign(aₜ−aₜ₋₁) = sign(pₜ−aₜ₋₁).",
        ref: "standard definition",
      },
      {
        id: "relative_absolute_error",
        name: "Relative absolute error",
        claim: "“RAE 0.41”",
        what: "Absolute error against a mean-forecast baseline.",
        how: "Σ|p−a| / Σ|a − mean(a)|.",
        ref: "standard definition",
      },
      {
        id: "relative_squared_error",
        name: "Relative squared error",
        claim: "“RSE 0.18”",
        what: "Squared error against a mean baseline (= 1 − R²).",
        how: "Σ(p−a)² / Σ(a − mean(a))².",
        ref: "standard definition",
      },
      {
        id: "mean_percentage_error",
        name: "Mean percentage error",
        claim: "“MPE −2.1%”",
        what: "Signed percentage bias — over- or under-forecasting.",
        how: "mean((a − p) / a).",
        ref: "standard definition",
      },
      {
        id: "median_absolute_percentage_error",
        name: "Median absolute % error (MdAPE)",
        claim: "“MdAPE 4.3%”",
        what: "Outlier-robust percentage error.",
        how: "median(|p − a| / |a|).",
        ref: "standard definition",
      },
    ],
  },
  {
    key: "analytics",
    title: "Data & analytics",
    blurb:
      "What every data agent claims after a pipeline run: totals, medians, group-bys, distincts, nulls — and whether the merge silently dropped rows.",
    recipes: [
      {
        id: "column_sum",
        name: "Column sum",
        claim: "“total $4.2M”",
        what: "A column total — revenue, amounts, quantities.",
        how: "Correctly-rounded fsum over the raw column; the claim's own reported precision ($4.2M = ±50k) sets the tolerance.",
        ref: "NumPy sum",
      },
      {
        id: "column_mean",
        name: "Column mean",
        claim: "“average order $54”",
        what: "A column average.",
        how: "fsum / n over the raw column.",
        ref: "NumPy mean",
      },
      {
        id: "column_median",
        name: "Column median",
        claim: "“median 42”",
        what: "The 50th percentile of a column.",
        how: "NumPy's default linear-interpolation quantile at q = 0.5.",
        ref: "NumPy median",
      },
      {
        id: "percentile",
        name: "Percentile",
        claim: "“90th percentile 120”",
        what: "Any quantile of a column.",
        how: "Linear-interpolation quantile (NumPy method 7) at the claimed q.",
        ref: "NumPy quantile",
        conv: "p95 / p99.9 / q=0.9",
      },
      {
        id: "row_count",
        name: "Row count",
        claim: "“processed 10,000 rows”",
        what: "How many rows a pipeline actually produced.",
        how: "A literal count of the artifact's rows.",
        ref: "definitional",
      },
      {
        id: "groupby_aggregate",
        name: "Group-by aggregate",
        claim: "“revenue in the West was $310k”",
        what: "A per-group sum or mean.",
        how: "fsum/mean per group key from the raw rows; without a named group there is no scalar to verify, so it degrades.",
        ref: "NumPy per-group",
        conv: "sum:<group> / mean:<group>",
      },
      {
        id: "distinct_count",
        name: "Distinct count",
        claim: "“12,402 distinct users”",
        what: "Unique values in a column.",
        how: "Distinct stripped cell values, nulls dropped by default.",
        ref: "pandas nunique convention",
        conv: "drop_null / include_null",
      },
      {
        id: "duplicate_count",
        name: "Duplicate count",
        claim: "“only 3 duplicates”",
        what: "Rows that duplicate an earlier row.",
        how: "n − distinct, the pandas duplicated(keep='first') convention.",
        ref: "pandas convention",
      },
      {
        id: "null_fraction",
        name: "Null fraction",
        claim: "“missing data under 2%”",
        what: "How much of a column is actually empty.",
        how: "Fraction of cells that are empty / NaN / null tokens, from the raw strings.",
        ref: "definitional",
      },
      {
        id: "growth_rate",
        name: "Growth rate",
        claim: "“up 23% MoM”",
        what: "Period-over-period or total growth of a time-ordered column.",
        how: "last/prev − 1 (or last/first − 1 for total growth).",
        ref: "definitional",
        conv: "period / total",
      },
      {
        id: "ratio_share",
        name: "Share / ratio",
        claim: "“42% of users converted”",
        what: "The fraction of rows meeting a flag.",
        how: "Count of truthy flags over n.",
        ref: "definitional",
      },
      {
        id: "join_row_loss",
        name: "Join row loss",
        claim: "“merged without losing rows”",
        what: "Whether a merge dropped (or fanned out) rows.",
        how: "len(left) − len(joined) across two artifacts; 0 is lossless, negative is fan-out.",
        ref: "definitional",
      },
      {
        id: "column_min",
        name: "Column min",
        claim: "“minimum order $12”",
        what: "The smallest value in a column.",
        how: "min over the raw column, NaN-propagating.",
        ref: "NumPy min",
      },
      {
        id: "column_max",
        name: "Column max",
        claim: "“maximum $9,400”",
        what: "The largest value in a column.",
        how: "max over the raw column, NaN-propagating.",
        ref: "NumPy max",
      },
      {
        id: "column_std",
        name: "Column std dev",
        claim: "“standard deviation 4.2”",
        what: "Spread of a column.",
        how: "Sample standard deviation (ddof=1; ddof=0 by convention).",
        ref: "NumPy std",
        conv: "ddof=1 (default) / ddof=0",
      },
      {
        id: "iqr",
        name: "Interquartile range",
        claim: "“IQR 12”",
        what: "The middle-50% spread.",
        how: "q75 − q25 with linear-interpolation quartiles.",
        ref: "SciPy iqr",
      },
      {
        id: "outlier_count",
        name: "Outlier count",
        claim: "“only 12 outliers”",
        what: "How many values sit outside the Tukey fences.",
        how: "count outside [q1 − k·IQR, q3 + k·IQR].",
        ref: "Tukey fences",
        conv: "k=<fence> (1.5)",
      },
      {
        id: "mode_share",
        name: "Mode share",
        claim: "“the most common category is 34% of rows”",
        what: "How dominant the most frequent value is.",
        how: "count(most frequent cell) / n on the raw strings.",
        ref: "definitional",
      },
      {
        id: "gini_coefficient",
        name: "Gini coefficient",
        claim: "“revenue Gini 0.38”",
        what: "Inequality of a distribution — how top-heavy the column is.",
        how: "Σ(2i − n − 1)·x₍ᵢ₎ / (n·Σx) over the sorted non-negative values.",
        ref: "standard Gini formula",
      },
      {
        id: "hhi",
        name: "Concentration (HHI)",
        claim: "“HHI 0.18”",
        what: "Herfindahl-Hirschman concentration of amounts.",
        how: "Σ(xᵢ/Σx)², on the 0–1 scale.",
        ref: "standard HHI",
      },
      {
        id: "entropy",
        name: "Entropy",
        claim: "“entropy 2.4 bits”",
        what: "How spread out a categorical column is.",
        how: "Shannon entropy of the value counts on deterministic log kernels.",
        ref: "SciPy entropy",
        conv: "bits (default) / nats",
      },
      {
        id: "variance",
        name: "Variance",
        claim: "“variance 12.4”",
        what: "Sample variance of a column.",
        how: "Σ(x − mean)² / (n − 1).",
        ref: "NumPy var (ddof=1)",
      },
      {
        id: "range_value",
        name: "Range",
        claim: "“range 480”",
        what: "Spread from smallest to largest value.",
        how: "max − min.",
        ref: "NumPy",
      },
      {
        id: "mean_abs_deviation",
        name: "Mean absolute deviation",
        claim: "“MAD 3.1”",
        what: "Average absolute distance from the mean.",
        how: "mean(|x − mean|).",
        ref: "standard definition",
      },
      {
        id: "median_abs_deviation",
        name: "Median absolute deviation",
        claim: "“MAD 2.6”",
        what: "Robust spread around the median.",
        how: "median(|x − median|).",
        ref: "SciPy median_abs_deviation (scale=1)",
      },
      {
        id: "trimmed_mean",
        name: "Trimmed mean",
        claim: "“10% trimmed mean 48”",
        what: "Mean after dropping a tail fraction from each end.",
        how: "mean of the sorted core, cutting `proportion` per tail.",
        ref: "SciPy trim_mean",
        conv: "proportion=<v> (0.1)",
      },
      {
        id: "geometric_mean",
        name: "Geometric mean",
        claim: "“geomean 21.3”",
        what: "Multiplicative average of positive values.",
        how: "exp(mean(ln x)).",
        ref: "SciPy gmean",
      },
      {
        id: "harmonic_mean",
        name: "Harmonic mean",
        claim: "“harmonic mean 18.7”",
        what: "Rate-appropriate average of positive values.",
        how: "n / Σ(1/x).",
        ref: "SciPy hmean",
      },
      {
        id: "weighted_mean",
        name: "Weighted mean",
        claim: "“weighted average 4.8”",
        what: "Average weighted by a second column.",
        how: "Σ(w·x) / Σw.",
        ref: "NumPy average",
      },
      {
        id: "covariance",
        name: "Covariance",
        claim: "“covariance 8.9”",
        what: "Joint variability of two columns.",
        how: "Σ(x − x̄)(y − ȳ) / (n − 1).",
        ref: "NumPy cov (ddof=1)",
      },
      {
        id: "theil_index",
        name: "Theil index",
        claim: "“Theil 0.21”",
        what: "Entropy-based inequality of a positive distribution.",
        how: "(1/n)·Σ(x/μ)·ln(x/μ).",
        ref: "standard Theil-T definition",
      },
      {
        id: "atkinson_index",
        name: "Atkinson index",
        claim: "“Atkinson 0.14”",
        what: "Inequality with aversion parameter ε = 1.",
        how: "1 − geomean/mean.",
        ref: "standard Atkinson definition",
      },
      {
        id: "quartile_coefficient_dispersion",
        name: "Quartile coefficient of dispersion",
        claim: "“QCD 0.18”",
        what: "Robust relative spread from the quartiles.",
        how: "(Q3 − Q1) / (Q3 + Q1).",
        ref: "standard definition",
      },
      {
        id: "index_of_dispersion",
        name: "Index of dispersion (Fano)",
        claim: "“Fano factor 1.3”",
        what: "Variance-to-mean ratio — over/under-dispersion vs Poisson.",
        how: "variance / mean.",
        ref: "standard definition",
      },
      {
        id: "uniqueness_ratio",
        name: "Uniqueness ratio",
        claim: "“uniqueness 0.13”",
        what: "Distinct values as a fraction of rows — a key-quality check.",
        how: "distinct values / total rows.",
        ref: "pandas nunique",
      },
      {
        id: "ljung_box",
        name: "Ljung-Box test",
        claim: "“Ljung-Box p = 0.04”",
        what: "Joint autocorrelation test — is a residual series white noise?",
        how: "Q = n(n+2)·Σρ²ₖ/(n−k); p from χ²(h).",
        ref: "statsmodels acorr_ljungbox",
        conv: "lags=<int> (10)",
      },
    ],
  },
  {
    key: "engineering",
    title: "Performance & engineering",
    blurb:
      "The coding-agent pack: “2.3× faster”, latency percentiles, coverage — recomputed from the raw benchmark timings and reports, not the summary line.",
    recipes: [
      {
        id: "speedup_ratio",
        name: "Speedup ratio",
        claim: "“2.3× faster”",
        what: "Before/after speedup from the raw timing runs.",
        how: "mean(before) / mean(after) — or medians — from the two timing columns.",
        ref: "NumPy",
        conv: "mean / median",
      },
      {
        id: "latency_p50",
        name: "Latency p50",
        claim: "“median latency 48ms”",
        what: "Median latency from the raw per-request durations.",
        how: "Linear-interpolation quantile at 0.50.",
        ref: "NumPy quantile",
      },
      {
        id: "latency_p95",
        name: "Latency p95",
        claim: "“p95 latency 120ms”",
        what: "Tail latency at the 95th percentile.",
        how: "Linear-interpolation quantile at 0.95.",
        ref: "NumPy quantile",
      },
      {
        id: "latency_p99",
        name: "Latency p99",
        claim: "“p99 under 250ms”",
        what: "Tail latency at the 99th percentile.",
        how: "Linear-interpolation quantile at 0.99.",
        ref: "NumPy quantile",
      },
      {
        id: "throughput",
        name: "Throughput",
        claim: "“4,200 rps”",
        what: "Operations per unit time.",
        how: "n / fsum(durations) over the raw per-op timings.",
        ref: "definitional",
      },
      {
        id: "peak_memory",
        name: "Peak memory",
        claim: "“peak memory 1.2GB”",
        what: "The maximum of a sampled memory series.",
        how: "max over the raw samples, NaN-propagating.",
        ref: "definitional",
      },
      {
        id: "test_coverage",
        name: "Test coverage",
        claim: "“coverage 87%”",
        what: "Line coverage recomputed from the report's raw per-line hit counts — not the percentage it printed.",
        how: "lines with hits > 0 over total lines.",
        ref: "coverage.py semantics",
      },
      {
        id: "error_rate",
        name: "Error rate",
        claim: "“5xx error rate 0.3%”",
        what: "Failures over totals, from the raw log rows.",
        how: "Count of error flags (or HTTP ≥400/≥500 statuses) over n.",
        ref: "definitional",
        conv: "flag / http4xx / http5xx",
      },
      {
        id: "latency_p90",
        name: "Latency p90",
        claim: "“p90 latency 95ms”",
        what: "Tail latency at the 90th percentile.",
        how: "Linear-interpolation quantile at 0.90.",
        ref: "NumPy quantile",
      },
      {
        id: "apdex",
        name: "Apdex",
        claim: "“Apdex 0.94 at t=0.5”",
        what: "The application-performance satisfaction index.",
        how: "(satisfied + tolerating/2) / n with satisfied ≤ T, tolerating ≤ 4T; T from the claim.",
        ref: "Apdex standard",
        conv: "t=<seconds> (required)",
      },
      {
        id: "uptime_pct",
        name: "Uptime",
        claim: "“uptime 99.95%”",
        what: "Availability from the raw up/down checks.",
        how: "up checks / total checks.",
        ref: "definitional",
      },
      {
        id: "cache_hit_rate",
        name: "Cache hit rate",
        claim: "“cache hit rate 87%”",
        what: "Hits over lookups, from the raw access log.",
        how: "hit flags / total accesses.",
        ref: "definitional",
      },
      {
        id: "latency_p75",
        name: "Latency p75",
        claim: "“p75 latency 180ms”",
        what: "Upper-quartile latency from raw per-request timings.",
        how: "NumPy linear quantile at 0.75.",
        ref: "NumPy",
      },
      {
        id: "latency_p999",
        name: "Latency p99.9",
        claim: "“p99.9 latency 1.4s”",
        what: "Deep-tail latency — the worst-1-in-1000 request.",
        how: "NumPy linear quantile at 0.999.",
        ref: "NumPy",
      },
      {
        id: "tail_latency_ratio",
        name: "Tail latency ratio",
        claim: "“tail ratio 6.5×”",
        what: "How much worse the tail is than the median.",
        how: "p99 / p50.",
        ref: "NumPy",
      },
      {
        id: "latency_stddev",
        name: "Latency std dev",
        claim: "“latency σ 90ms”",
        what: "Spread of the latency distribution.",
        how: "std(ddof=1) of the raw durations.",
        ref: "NumPy",
      },
      {
        id: "jitter",
        name: "Jitter",
        claim: "“jitter 22ms”",
        what: "Average request-to-request variation in latency.",
        how: "mean(|dₜ − dₜ₋₁|) over the duration series.",
        ref: "definitional",
      },
      {
        id: "slo_attainment",
        name: "SLO attainment",
        claim: "“99.2% under 200ms”",
        what: "Fraction of requests meeting the latency objective.",
        how: "fraction of durations ≤ threshold.",
        ref: "definitional",
        conv: "threshold=<v>",
      },
      {
        id: "error_budget_burn",
        name: "Error budget burn",
        claim: "“burn rate 1.8×”",
        what: "Observed error rate against the SLO target — alerting metric.",
        how: "(errors / total) / target rate.",
        ref: "definitional",
        conv: "target=<frac>",
      },
      {
        id: "compression_ratio",
        name: "Compression ratio",
        claim: "“compression 4.1×”",
        what: "How much smaller the compressed output is.",
        how: "sum(original) / sum(compressed).",
        ref: "definitional",
      },
      {
        id: "availability",
        name: "Availability",
        claim: "“availability 99.95%”",
        what: "Uptime as a fraction of total observed time.",
        how: "uptime / (uptime + downtime).",
        ref: "definitional",
      },
      {
        id: "mtbf",
        name: "Mean time between failures",
        claim: "“MTBF 240 periods”",
        what: "Average run length between failures.",
        how: "n / number of failure flags.",
        ref: "definitional",
      },
    ],
  },
  {
    key: "retrieval",
    title: "Retrieval, RAG & LLM evals",
    blurb:
      "Modern eval claims, from raw ranked results and per-sample grades — including the exact unbiased pass@k estimator from the HumanEval paper.",
    recipes: [
      {
        id: "recall_at_k",
        name: "Recall@k",
        claim: "“recall@10 0.84”",
        what: "How much of the relevant material the retriever surfaced in the top k.",
        how: "Per query: relevant-in-top-k over all-relevant; averaged, zero-relevant queries skipped.",
        ref: "standard IR definition",
        conv: "k=<n> (10)",
      },
      {
        id: "ndcg_at_k",
        name: "NDCG@k",
        claim: "“NDCG@10 0.71”",
        what: "Rank-discounted gain against the ideal ordering.",
        how: "DCG with 1/log₂(i+1) discounts over IDCG, linear or exponential gains, on deterministic log kernels.",
        ref: "scikit-learn ndcg_score",
        conv: "k=<n>, optional exp",
      },
      {
        id: "mrr",
        name: "MRR",
        claim: "“MRR 0.62”",
        what: "How early the first relevant result appears.",
        how: "Mean of 1/rank of the first relevant result per query; 0 when none.",
        ref: "standard IR definition",
        conv: "k=<n> (uncapped)",
      },
      {
        id: "top_k_accuracy",
        name: "Top-k accuracy",
        claim: "“top-5 accuracy 0.91”",
        what: "Hit rate: queries with at least one relevant result in the top k.",
        how: "Per-query any-relevant-in-top-k, averaged.",
        ref: "standard definition",
        conv: "k=<n> (5)",
      },
      {
        id: "exact_match",
        name: "Exact match",
        claim: "“exact match 71%”",
        what: "String-level answer accuracy, strict or SQuAD-normalized.",
        how: "Mean exact match; normalized mode lowercases, strips punctuation and articles, collapses whitespace.",
        ref: "SQuAD evaluation script",
        conv: "strict / normalized",
      },
      {
        id: "pass_at_k",
        name: "pass@k",
        claim: "“pass@1 0.47”",
        what: "Code-generation success with the unbiased estimator — not the naive fraction.",
        how: "Per problem 1 − C(n−c,k)/C(n,k) in exact integer arithmetic; fewer than k samples degrades.",
        ref: "Chen et al. 2021 (HumanEval)",
        conv: "k=<n> (1)",
      },
      {
        id: "precision_at_k",
        name: "Precision@k",
        claim: "“precision@10 0.31”",
        what: "How much of the top k was actually relevant.",
        how: "Per query: relevant-in-top-k / k, averaged over all queries.",
        ref: "standard IR definition",
        conv: "k=<n> (10)",
      },
      {
        id: "map_at_k",
        name: "MAP@k",
        claim: "“MAP@10 0.44”",
        what: "Mean average precision — rank-sensitive retrieval quality.",
        how: "Per query Σ P@i·relᵢ / min(R, k), zero-relevant queries skipped, averaged.",
        ref: "standard definition (min(R,k) denominator, documented)",
        conv: "k=<n> (10)",
      },
      {
        id: "perplexity",
        name: "Perplexity",
        claim: "“perplexity 12.4”",
        what: "Language-model fit, recomputed from the raw per-token log-probabilities.",
        how: "exp(−mean(logprob)) on deterministic exp kernels; positive logprobs degrade.",
        ref: "standard definition",
      },
      {
        id: "wer",
        name: "WER / CER",
        claim: "“WER 8.4%”",
        what: "Word (or character) error rate of transcriptions against references.",
        how: "Corpus-level Levenshtein edits / reference tokens, exact DP.",
        ref: "jiwer",
        conv: "wer (default) / cer",
      },
    ],
  },
  {
    key: "stats",
    title: "Statistical claims",
    blurb:
      "“The experiment was significant” — recomputed from the raw samples on deterministic special-function kernels that match SciPy to better than 1e-11.",
    recipes: [
      {
        id: "p_value",
        name: "p-value",
        claim: "“p = 0.003”",
        what: "Two-sided two-sample significance, recomputed from the raw observations.",
        how: "Welch (default), pooled, or z statistic; p via a deterministic incomplete-beta kernel.",
        ref: "SciPy ttest_ind",
        conv: "welch / pooled / z",
      },
      {
        id: "confidence_interval",
        name: "Confidence interval",
        claim: "“95% CI ± 0.4”",
        what: "The margin of error of a mean.",
        how: "Critical t (or z) × s/√n, with critical values from deterministic bisection inverses.",
        ref: "SciPy t.ppf",
        conv: "t95 / t99 / z95",
      },
      {
        id: "lift",
        name: "A/B lift",
        claim: "“the variant lifted conversion 12%”",
        what: "Treatment uplift over control, relative or absolute.",
        how: "(mean_B − mean_A) / mean_A from the raw per-user outcomes.",
        ref: "definitional",
        conv: "relative / absolute",
      },
      {
        id: "chi_square",
        name: "Chi-square",
        claim: "“χ² = 5.99, p < 0.05”",
        what: "Independence of two categorical variables, from the raw observation pairs — the contingency table is rebuilt, not trusted.",
        how: "Expected counts from marginals, Yates correction only at df = 1, p from a deterministic incomplete-gamma kernel.",
        ref: "SciPy chi2_contingency",
        conv: "p / statistic, ±yates",
      },
      {
        id: "correlation",
        name: "Correlation",
        claim: "“Spearman correlation 0.8”",
        what: "Pearson or Spearman association between two columns.",
        how: "fsum-centered Pearson; Spearman ranks first with ties midranked.",
        ref: "SciPy pearsonr / spearmanr",
        conv: "pearson / spearman",
      },
      {
        id: "effect_size",
        name: "Effect size",
        claim: "“Cohen's d 0.4”",
        what: "Standardized mean difference between two groups.",
        how: "Pooled-SD d, exact-gamma Hedges' g, or Glass's Δ.",
        ref: "standard formulas, exact Hedges J",
        conv: "cohen_d / hedges_g / glass_delta",
      },
      {
        id: "mann_whitney",
        name: "Mann-Whitney U",
        claim: "“Mann-Whitney p 0.03”",
        what: "The non-parametric two-sample test — no normality assumption to hide behind.",
        how: "Tie-corrected, continuity-corrected asymptotic p from midranks.",
        ref: "SciPy mannwhitneyu (asymptotic)",
      },
      {
        id: "ks_test",
        name: "KS test",
        claim: "“KS test p 0.01”",
        what: "Whether two samples come from the same distribution.",
        how: "max ECDF gap, p from the classical Kolmogorov asymptotic on deterministic exp kernels.",
        ref: "Kolmogorov asymptotic (SciPy kstwobign)",
      },
      {
        id: "anova",
        name: "One-way ANOVA",
        claim: "“ANOVA p = 0.01”",
        what: "Whether group means differ, from the raw (group, value) rows.",
        how: "F = between-group / within-group mean squares; p via the deterministic incomplete beta.",
        ref: "SciPy f_oneway",
        conv: "p (default) / statistic",
      },
      {
        id: "proportion_z",
        name: "Two-proportion z-test",
        claim: "“conversion difference significant, p 0.002”",
        what: "Whether two conversion rates actually differ.",
        how: "Pooled two-proportion z from the raw 0/1 outcomes; two-sided p.",
        ref: "statsmodels proportions_ztest",
      },
      {
        id: "fisher_exact",
        name: "Fisher's exact test",
        claim: "“Fisher exact p 0.04”",
        what: "The small-sample 2×2 test — exact, no approximation.",
        how: "Exact hypergeometric arithmetic via integer combinatorics, two-sided.",
        ref: "SciPy fisher_exact",
      },
      {
        id: "odds_ratio",
        name: "Odds ratio",
        claim: "“odds ratio 2.3”",
        what: "Association strength in a 2×2, from the raw observation pairs.",
        how: "(a·d)/(b·c); a zero cell degrades unless the Haldane +0.5 convention is named.",
        ref: "SciPy fisher_exact (sample OR)",
        conv: "sample (default) / haldane",
      },
      {
        id: "relative_risk",
        name: "Relative risk",
        claim: "“relative risk 1.4”",
        what: "Risk ratio between two groups, from the raw pairs.",
        how: "(a/(a+b)) / (c/(c+d)), rows by sorted group key.",
        ref: "standard definition",
      },
      {
        id: "cramers_v",
        name: "Cramér's V",
        claim: "“Cramér's V 0.21”",
        what: "Effect size of a categorical association — significance isn't strength.",
        how: "√(χ²/(n·min(r−1, c−1))) with the uncorrected χ².",
        ref: "standard definition over SciPy χ²",
      },
      {
        id: "skewness",
        name: "Skewness",
        claim: "“skewness −0.8”",
        what: "Asymmetry of a distribution.",
        how: "Biased g₁ = m₃/m₂^1.5 (the SciPy default).",
        ref: "SciPy skew",
      },
      {
        id: "kurtosis",
        name: "Kurtosis",
        claim: "“excess kurtosis 4.1”",
        what: "Tail weight — how often the extreme days happen.",
        how: "Biased excess g₂ = m₄/m₂² − 3 (Fisher).",
        ref: "SciPy kurtosis",
      },
      {
        id: "jarque_bera",
        name: "Jarque-Bera",
        claim: "“JB p < 0.01 — not normal”",
        what: "Normality test from skewness and kurtosis.",
        how: "JB = n/6(S² + K²/4); p from the deterministic χ²(2) kernel.",
        ref: "SciPy jarque_bera",
        conv: "p (default) / statistic",
      },
      {
        id: "autocorrelation",
        name: "Autocorrelation",
        claim: "“lag-1 autocorrelation 0.22”",
        what: "Serial dependence in a series — the thing that invalidates i.i.d. claims.",
        how: "Standard biased ACF at the claimed lag.",
        ref: "statsmodels acf",
        conv: "lag=<k> (1)",
      },
      {
        id: "point_biserial",
        name: "Point-biserial correlation",
        claim: "“point-biserial 0.34”",
        what: "Correlation between a binary group and a continuous outcome.",
        how: "Pearson r between the 0/1 column and the value column.",
        ref: "SciPy pointbiserialr",
      },
      {
        id: "kendall_tau",
        name: "Kendall's tau-b",
        claim: "“Kendall τ 0.41”",
        what: "Rank correlation robust to outliers, tie-corrected.",
        how: "(concordant − discordant) / √((n₀−n₁)(n₀−n₂)) over all pairs.",
        ref: "SciPy kendalltau",
      },
      {
        id: "theil_sen_slope",
        name: "Theil-Sen slope",
        claim: "“slope 1.98 (Theil-Sen)”",
        what: "Robust regression slope — the median of all pairwise slopes.",
        how: "median over i<j of (yⱼ−yᵢ)/(xⱼ−xᵢ), xᵢ≠xⱼ.",
        ref: "SciPy theilslopes",
      },
      {
        id: "cliffs_delta",
        name: "Cliff's delta",
        claim: "“Cliff's δ 0.28”",
        what: "Nonparametric effect size — how often one group exceeds the other.",
        how: "(#(a>b) − #(a<b)) / (nₐ·n_b) over all cross-pairs.",
        ref: "Cliff (1993) definition",
      },
      {
        id: "rank_biserial",
        name: "Rank-biserial correlation",
        claim: "“rank-biserial 0.31”",
        what: "Effect size for the Mann-Whitney U test.",
        how: "1 − 2U/(n₁n₂), U the Mann-Whitney statistic (Wendt).",
        ref: "SciPy mannwhitneyu (U) + Wendt",
      },
      {
        id: "eta_squared",
        name: "Eta-squared (η²)",
        claim: "“η² 0.18”",
        what: "Share of variance explained by group membership (one-way).",
        how: "SS_between / SS_total from the raw (group, value) rows.",
        ref: "standard one-way ANOVA definition",
      },
      {
        id: "g_test",
        name: "G-test of independence",
        claim: "“G-test p = 0.004”",
        what: "Likelihood-ratio alternative to chi-square for a contingency table.",
        how: "G = 2·Σ O·ln(O/E); p from χ²((R−1)(C−1)). No continuity correction.",
        ref: "SciPy chi2_contingency (log-likelihood)",
        conv: "p (default) / statistic",
      },
      {
        id: "mcnemar",
        name: "McNemar's test",
        claim: "“McNemar p = 0.02”",
        what: "Paired-binary test — did two classifiers (or before/after) differ?",
        how: "(|n₁₀−n₀₁|−1)² / (n₁₀+n₀₁) on the discordant pairs; χ²(1).",
        ref: "statsmodels mcnemar (asymptotic, continuity)",
      },
      {
        id: "levene",
        name: "Levene's test",
        claim: "“Levene p = 0.03”",
        what: "Equal-variance test across groups, robust to non-normality (Brown-Forsythe).",
        how: "One-way F on |xᵢ − group median|; p from F((k−1), N−k).",
        ref: "SciPy levene (center=median)",
      },
      {
        id: "bartlett",
        name: "Bartlett's test",
        claim: "“Bartlett p = 0.01”",
        what: "Equal-variance test across groups (sensitive to normality).",
        how: "[(N−k)ln s²ₚ − Σ(nⱼ−1)ln s²ⱼ] / C; p from χ²(k−1).",
        ref: "SciPy bartlett",
      },
      {
        id: "fligner",
        name: "Fligner-Killeen test",
        claim: "“Fligner p = 0.04”",
        what: "Rank-based equal-variance test, robust to non-normality.",
        how: "Normal-score ranks of |xᵢ − group median|; χ²(k−1).",
        ref: "SciPy fligner (center=median)",
      },
      {
        id: "kruskal_wallis",
        name: "Kruskal-Wallis H",
        claim: "“Kruskal-Wallis p = 0.002”",
        what: "Nonparametric one-way ANOVA — do k groups differ in location?",
        how: "Tie-corrected rank-sum H; p from χ²(k−1).",
        ref: "SciPy kruskal",
      },
      {
        id: "wilcoxon_signed_rank",
        name: "Wilcoxon signed-rank",
        claim: "“Wilcoxon p = 0.02”",
        what: "Paired nonparametric test on the differences.",
        how: "Signed-rank W⁺, tie-corrected normal approximation, zeros dropped.",
        ref: "SciPy wilcoxon (method=approx)",
      },
      {
        id: "anderson_darling",
        name: "Anderson-Darling A²",
        claim: "“A² = 0.61”",
        what: "Normality test weighted toward the tails.",
        how: "−N − (1/N)Σ(2i−1)[ln Φ(wᵢ) + ln(1−Φ(w_{N+1−i}))] on standardized sorted data.",
        ref: "SciPy anderson (norm)",
      },
      {
        id: "wilson_lower",
        name: "Wilson CI (lower)",
        claim: "“95% lower bound 0.38”",
        what: "Lower Wilson score bound for a binomial proportion.",
        how: "Score-interval lower bound from the success count, deterministic inverse-normal z.",
        ref: "statsmodels proportion_confint (wilson)",
        conv: "90 / 95 / 99",
      },
      {
        id: "wilson_upper",
        name: "Wilson CI (upper)",
        claim: "“95% upper bound 0.52”",
        what: "Upper Wilson score bound for a binomial proportion.",
        how: "Score-interval upper bound from the success count, deterministic inverse-normal z.",
        ref: "statsmodels proportion_confint (wilson)",
        conv: "90 / 95 / 99",
      },
      {
        id: "bh_rejections",
        name: "Benjamini-Hochberg rejections",
        claim: "“14 discoveries at FDR 5%”",
        what: "How many hypotheses survive FDR control — the multiple-testing deflator.",
        how: "Largest k with p₍ₖ₎ ≤ (k/m)·α over the sorted p-values; count = k.",
        ref: "statsmodels multipletests (fdr_bh)",
        conv: "alpha (0.05)",
      },
      {
        id: "holm_rejections",
        name: "Holm-Bonferroni rejections",
        claim: "“9 rejections (Holm)”",
        what: "Discoveries under Holm's family-wise error control.",
        how: "Step-down: reject p₍ₖ₎ while p₍ₖ₎ ≤ α/(m−k+1); count the run.",
        ref: "statsmodels multipletests (holm)",
        conv: "alpha (0.05)",
      },
      {
        id: "kupiec_pof",
        name: "Kupiec POF (VaR backtest)",
        claim: "“VaR backtest passes (Kupiec p = 0.4)”",
        what: "Unconditional-coverage test: did VaR breaches occur at the expected rate?",
        how: "Proportion-of-failures LR from the exception count; χ²(1).",
        ref: "Kupiec (1995) LR formula + χ²",
        conv: "expected rate (0.01)",
      },
      {
        id: "christoffersen_independence",
        name: "Christoffersen independence",
        claim: "“breaches are independent (p = 0.3)”",
        what: "Are VaR exceptions clustered in time (a worse failure than wrong count)?",
        how: "First-order Markov LR test of exception independence; χ²(1).",
        ref: "Christoffersen (1998) LR formula + χ²",
      },
      {
        id: "christoffersen_cc",
        name: "Christoffersen conditional coverage",
        claim: "“VaR passes conditional coverage”",
        what: "Joint test of correct breach rate and independence.",
        how: "LR_uc + LR_ind; χ²(2).",
        ref: "Christoffersen (1998) + χ²",
        conv: "expected rate (0.01)",
      },
      {
        id: "psi",
        name: "Population Stability Index",
        claim: "“PSI 0.12 (no material shift)”",
        what: "Distribution drift between an expected and an actual binned distribution.",
        how: "Σ(a%−e%)·ln(a%/e%) over normalized bin shares.",
        ref: "standard PSI definition",
      },
      {
        id: "information_value",
        name: "Information Value (IV)",
        claim: "“IV 0.34 (strong predictor)”",
        what: "Predictive strength of a binned feature in a scoring model.",
        how: "Σ(good%−bad%)·WOE over bins, WOE = ln(good%/bad%).",
        ref: "credit-scoring IV/WOE definition",
      },
      {
        id: "kl_divergence",
        name: "KL divergence",
        claim: "“KL 0.08 nats”",
        what: "Directed divergence of one distribution from a reference.",
        how: "Σ p·ln(p/q) over normalized distributions (natural log).",
        ref: "SciPy entropy",
      },
      {
        id: "js_divergence",
        name: "Jensen-Shannon divergence",
        claim: "“JS 0.04”",
        what: "Symmetric, bounded divergence between two distributions.",
        how: "½KL(P‖M) + ½KL(Q‖M), M = (P+Q)/2 (natural log).",
        ref: "SciPy entropy (symmetrized)",
      },
      {
        id: "wasserstein_1d",
        name: "Wasserstein-1 distance",
        claim: "“earth-mover distance 1.7”",
        what: "1-D optimal-transport distance between two samples.",
        how: "∫|F_a − F_b| over the merged empirical CDFs.",
        ref: "SciPy wasserstein_distance",
      },
      {
        id: "energy_distance",
        name: "Energy distance",
        claim: "“energy distance 0.9”",
        what: "Distribution distance sensitive to all moments, two samples.",
        how: "√(2·∫(F_a − F_b)²) over the merged empirical CDFs.",
        ref: "SciPy energy_distance",
      },
      {
        id: "ks_2samp",
        name: "Two-sample KS statistic",
        claim: "“KS D = 0.21”",
        what: "Maximum gap between two empirical distributions.",
        how: "max|F_a − F_b| over the merged support.",
        ref: "SciPy ks_2samp",
      },
      {
        id: "concordance_index",
        name: "Concordance index (C-index)",
        claim: "“C-index 0.78”",
        what: "Harrell's C — discrimination of a survival/risk model (credit, insurance).",
        how: "fraction of comparable pairs the predicted risk orders correctly; ties = 0.5.",
        ref: "lifelines concordance_index",
      },
      {
        id: "mutual_info_score",
        name: "Mutual information",
        claim: "“MI 0.9 nats”",
        what: "Shared information between two labelings / segmentations.",
        how: "Σ (nᵢⱼ/n)·ln(nᵢⱼ·n / aᵢbⱼ) over the contingency table.",
        ref: "scikit-learn mutual_info_score",
      },
      {
        id: "normalized_mutual_info",
        name: "Normalized mutual information",
        claim: "“NMI 0.82”",
        what: "MI scaled to [0,1] by the label entropies.",
        how: "MI / mean(H(true), H(pred)).",
        ref: "scikit-learn normalized_mutual_info_score",
      },
      {
        id: "homogeneity_score",
        name: "Homogeneity",
        claim: "“homogeneity 0.88”",
        what: "Each cluster contains only members of a single true class.",
        how: "MI / H(true).",
        ref: "scikit-learn homogeneity_score",
      },
      {
        id: "completeness_score",
        name: "Completeness",
        claim: "“completeness 0.84”",
        what: "All members of a true class land in the same cluster.",
        how: "MI / H(pred).",
        ref: "scikit-learn completeness_score",
      },
      {
        id: "v_measure_score",
        name: "V-measure",
        claim: "“V-measure 0.86”",
        what: "Harmonic mean of homogeneity and completeness.",
        how: "2·h·c / (h + c).",
        ref: "scikit-learn v_measure_score",
      },
      {
        id: "rand_index",
        name: "Rand index",
        claim: "“Rand index 0.91”",
        what: "Fraction of point-pairs two labelings agree on.",
        how: "(agreeing pairs) / (all pairs).",
        ref: "scikit-learn rand_score",
      },
      {
        id: "adjusted_rand_index",
        name: "Adjusted Rand index",
        claim: "“ARI 0.74”",
        what: "Rand index corrected for chance.",
        how: "(Σ C(nᵢⱼ,2) − expected) / (½(Σ C(aᵢ,2)+Σ C(bⱼ,2)) − expected).",
        ref: "scikit-learn adjusted_rand_score",
      },
      {
        id: "fowlkes_mallows_clustering",
        name: "Fowlkes-Mallows (clustering)",
        claim: "“FM 0.8”",
        what: "Geometric mean of pairwise precision and recall between two labelings.",
        how: "Σ C(nᵢⱼ,2) / √(Σ C(aᵢ,2)·Σ C(bⱼ,2)).",
        ref: "scikit-learn fowlkes_mallows_score",
      },
    ],
  },
  {
    key: "finance",
    title: "Business & finance",
    blurb:
      "Beyond trading: the numbers that go in board decks and term sheets, rebuilt from the raw ledgers and cash flows.",
    recipes: [
      {
        id: "cagr",
        name: "CAGR",
        claim: "“monthly CAGR 23.9%”",
        what: "Compound annual growth from a time-ordered value series.",
        how: "(last/first)^(1/years) − 1 on deterministic power kernels; the period convention comes from the claim itself.",
        ref: "definitional",
        conv: "periods=<per-year>",
      },
      {
        id: "npv",
        name: "NPV",
        claim: "“NPV $310k at 8%”",
        what: "Net present value of a raw cash-flow column.",
        how: "Σ cf_t/(1+r)^t with exact integer-power expansion; no rate claimed means no verdict.",
        ref: "numpy-financial npv",
        conv: "rate=<frac>",
      },
      {
        id: "irr",
        name: "IRR",
        claim: "“IRR 18%”",
        what: "The discount rate where the cash flows break even.",
        how: "Deterministic bisection on NPV; no sign change in the flows degrades instead of guessing.",
        ref: "numpy-financial irr",
      },
      {
        id: "churn_rate",
        name: "Churn / retention",
        claim: "“churn 3.1%”",
        what: "Churned over total from the raw per-customer flags.",
        how: "Count of churn flags over n; retention is its complement.",
        ref: "definitional",
        conv: "churn / retention",
      },
      {
        id: "margin_pct",
        name: "Margin",
        claim: "“gross margin 61%”",
        what: "Margin recomputed from the raw revenue and cost rows.",
        how: "(Σ revenue − Σ cost) / Σ revenue under correctly-rounded summation.",
        ref: "definitional",
      },
      {
        id: "reconciliation_total",
        name: "Reconciliation",
        claim: "“the totals match the ledger”",
        what: "Whether two totals actually reconcile — across two files.",
        how: "fsum(A) − fsum(B) with cross-artifact bindings; 0 is reconciled, anything else is the exact discrepancy.",
        ref: "definitional",
      },
    ],
  },
  {
    key: "compiled",
    title: "Compiled recipes",
    blurb:
      "Drafted offline as compositions of the existing deterministic kernels, then admitted by a " +
      "deterministic gate: differential testing against the named reference implementation, a " +
      "metamorphic property suite, degeneracy checks, and a bit-stability double-run. Frozen under " +
      "a content hash — never improvised at verify time.",
    recipes: [
      {
        id: "sem",
        name: "Standard error of the mean",
        claim: "“mean 4.2 ± 0.3 (SEM)”",
        what: "The ± a mean is reported with: sample dispersion shrunk by √n.",
        how: "Compiled composition: fstd(ddof=1) / √n on the fsum kernels.",
        ref: "SciPy sem",
        conv: "compiled-validated · gate: differential + metamorphic + degeneracy + bit-stability",
      },
      {
        id: "coefficient_of_variation",
        name: "Coefficient of variation",
        claim: "“CV 12%”",
        what: "Relative dispersion — std as a fraction of the mean; scale-invariant.",
        how: "Compiled composition: fstd(ddof=1) / fmean on the fsum kernels.",
        ref: "SciPy variation",
        conv: "compiled-validated · gate: differential + metamorphic + degeneracy + bit-stability",
      },
    ],
  },
];

export const RECIPE_COUNT = FAMILIES.reduce((n, f) => n + f.recipes.length, 0);
