// GENERATED from the product recipe catalogue (app/recipes/data.ts), kept in lockstep with the
// hosted registry seed (control_plane/migrations/0008 + api/recipes_catalogue.py). Every `value`
// is a recipe_id the hosted API accepts, so the picker can never 404 on submit.
export type RecipeOption = { value: string; label: string };
export type RecipeGroup = { title: string; options: RecipeOption[] };

export const RECIPE_CATALOG: RecipeGroup[] = [
  {
    title: "Trading & backtests",
    options: [
      { value: "trading.total_return", label: "Total return" },
      { value: "trading.sharpe", label: "Sharpe ratio" },
      { value: "trading.max_drawdown", label: "Max drawdown" },
      { value: "trading.deflated_sharpe", label: "Deflated Sharpe ratio" },
      { value: "trading.variance_ratio", label: "Variance ratio" },
      { value: "trading.hurst_rs", label: "Hurst exponent (R/S)" },
      { value: "trading.rescaled_range", label: "Rescaled range (R/S)" },
      { value: "trading.volatility", label: "Volatility" },
      { value: "trading.parkinson_volatility", label: "Parkinson volatility" },
      { value: "trading.garman_klass_volatility", label: "Garman-Klass volatility" },
      { value: "trading.rogers_satchell_volatility", label: "Rogers-Satchell volatility" },
      { value: "trading.yang_zhang_volatility", label: "Yang-Zhang volatility" },
      { value: "trading.realized_variance", label: "Realized variance" },
      { value: "trading.realized_volatility", label: "Realized volatility" },
      { value: "trading.bipower_variation", label: "Bipower variation" },
      { value: "trading.jump_variation", label: "Jump variation" },
      { value: "trading.sortino", label: "Sortino ratio" },
      { value: "trading.calmar", label: "Calmar ratio" },
      { value: "trading.downside_deviation", label: "Downside deviation" },
      { value: "trading.value_at_risk", label: "Value at risk" },
      { value: "trading.cvar", label: "CVaR / expected shortfall" },
      { value: "trading.hill_estimator", label: "Hill tail index" },
      { value: "trading.pickands_estimator", label: "Pickands EVI" },
      { value: "trading.max_to_sum_ratio", label: "Max-to-sum ratio" },
      { value: "trading.win_rate", label: "Win rate" },
      { value: "trading.batting_average", label: "Batting average" },
      { value: "trading.bias_ratio", label: "Bias ratio (ODD flag)" },
      { value: "trading.max_consecutive_losses", label: "Max consecutive losses" },
      { value: "trading.profit_factor", label: "Profit factor" },
      { value: "trading.omega_ratio", label: "Omega ratio" },
      { value: "trading.beta", label: "Beta" },
      { value: "trading.alpha", label: "Alpha" },
      { value: "trading.idiosyncratic_volatility", label: "Idiosyncratic volatility" },
      { value: "trading.alpha_tstat", label: "Alpha t-statistic" },
      { value: "trading.beta_tstat", label: "Beta t-statistic" },
      { value: "trading.bull_beta", label: "Bull beta" },
      { value: "trading.bear_beta", label: "Bear beta" },
      { value: "trading.up_down_beta_ratio", label: "Up/down beta ratio" },
      { value: "trading.information_ratio", label: "Information ratio" },
      { value: "trading.tracking_error", label: "Tracking error" },
      { value: "trading.ulcer_index", label: "Ulcer index" },
      { value: "trading.pain_index", label: "Pain index" },
      { value: "trading.time_underwater", label: "Time underwater" },
      { value: "trading.drawdown_at_risk", label: "Drawdown at risk" },
      { value: "trading.drawdown_deviation", label: "Drawdown deviation" },
      { value: "trading.martin_ratio", label: "Martin ratio (UPI)" },
      { value: "trading.recovery_factor", label: "Recovery factor" },
      { value: "trading.gain_to_pain_ratio", label: "Gain-to-pain ratio" },
      { value: "trading.tail_ratio", label: "Tail ratio" },
      { value: "trading.gain_loss_ratio", label: "Gain/loss ratio" },
      { value: "trading.win_loss_ratio", label: "Win/loss ratio" },
      { value: "trading.kelly_criterion", label: "Kelly criterion" },
      { value: "trading.upside_deviation", label: "Upside deviation" },
      { value: "trading.upside_potential_ratio", label: "Upside potential ratio" },
      { value: "trading.kappa_three", label: "Kappa-3" },
      { value: "trading.cdar", label: "Conditional drawdown at risk" },
      { value: "trading.max_drawdown_duration", label: "Max drawdown duration" },
      { value: "trading.parametric_var", label: "Parametric VaR" },
      { value: "trading.parametric_es", label: "Parametric expected shortfall" },
      { value: "trading.cornish_fisher_var", label: "Cornish-Fisher VaR" },
      { value: "trading.reward_to_var_ratio", label: "Reward-to-VaR" },
      { value: "trading.starr_ratio", label: "STARR ratio" },
      { value: "trading.modified_sharpe_ratio", label: "Modified Sharpe" },
      { value: "trading.adjusted_sharpe_ratio", label: "Adjusted Sharpe ratio" },
      { value: "trading.probabilistic_sharpe_ratio", label: "Probabilistic Sharpe ratio" },
      { value: "trading.up_capture_ratio", label: "Up-capture ratio" },
      { value: "trading.down_capture_ratio", label: "Down-capture ratio" },
      { value: "trading.capture_ratio", label: "Capture ratio" },
      { value: "trading.treynor_ratio", label: "Treynor ratio" },
      { value: "trading.r_squared", label: "R\u00b2 vs benchmark" },
      { value: "trading.active_return", label: "Active return" },
      { value: "trading.pain_ratio", label: "Pain ratio" },
      { value: "trading.sterling_ratio", label: "Sterling ratio" },
      { value: "trading.burke_ratio", label: "Burke ratio" },
      { value: "trading.m2_measure", label: "M\u00b2 (Modigliani)" },
      { value: "trading.appraisal_ratio", label: "Appraisal ratio" },
      { value: "trading.common_sense_ratio", label: "Common sense ratio" },
      { value: "trading.rachev_ratio", label: "Rachev ratio" },
      { value: "trading.downside_potential", label: "Downside potential" },
      { value: "trading.upside_potential", label: "Upside potential" },
      { value: "trading.omega_sharpe_ratio", label: "Sharpe-Omega ratio" },
    ],
  },
  {
    title: "ML classification",
    options: [
      { value: "classification.accuracy", label: "Accuracy" },
      { value: "classification.auc", label: "ROC-AUC" },
      { value: "classification.precision", label: "Precision" },
      { value: "classification.recall", label: "Recall" },
      { value: "classification.f1", label: "F1" },
      { value: "classification.macro_f1", label: "Macro-F1" },
      { value: "classification.micro_f1", label: "Micro-F1" },
      { value: "classification.pr_auc", label: "PR-AUC" },
      { value: "classification.log_loss", label: "Log loss" },
      { value: "classification.hinge_loss", label: "Hinge loss" },
      { value: "classification.squared_hinge_loss", label: "Squared hinge loss" },
      { value: "classification.exponential_loss", label: "Exponential loss" },
      { value: "classification.brier", label: "Brier score" },
      { value: "classification.mcc", label: "Matthews correlation" },
      { value: "classification.ece", label: "Calibration error (ECE)" },
      { value: "classification.maximum_calibration_error", label: "Maximum calibration error" },
      { value: "classification.brier_reliability", label: "Brier reliability" },
      { value: "classification.brier_resolution", label: "Brier resolution" },
      { value: "classification.brier_skill_score", label: "Brier skill score" },
      { value: "classification.calibration_in_the_large", label: "Calibration-in-the-large" },
      { value: "classification.spiegelhalter_z", label: "Spiegelhalter z" },
      { value: "classification.sharpness", label: "Sharpness" },
      { value: "classification.balanced_accuracy", label: "Balanced accuracy" },
      { value: "classification.cohen_kappa", label: "Cohen's kappa" },
      { value: "classification.percentage_agreement", label: "Percentage agreement" },
      { value: "classification.scott_pi", label: "Scott's \u03c0" },
      { value: "classification.brennan_prediger", label: "Brennan-Prediger \u03ba" },
      { value: "classification.gwet_ac1", label: "Gwet's AC1" },
      { value: "classification.specificity", label: "Specificity" },
      { value: "classification.fbeta", label: "F-beta" },
      { value: "classification.jaccard", label: "Jaccard / IoU" },
      { value: "classification.weighted_f1", label: "Weighted F1" },
      { value: "classification.ks_statistic", label: "KS statistic" },
      { value: "classification.gini_norm", label: "Gini (accuracy ratio)" },
      { value: "classification.g_mean", label: "Geometric mean (G-mean)" },
      { value: "classification.youden_j", label: "Youden's J" },
      { value: "classification.markedness", label: "Markedness" },
      { value: "classification.negative_predictive_value", label: "Negative predictive value" },
      { value: "classification.false_positive_rate", label: "False positive rate" },
      { value: "classification.false_negative_rate", label: "False negative rate" },
      { value: "classification.false_discovery_rate", label: "False discovery rate" },
      { value: "classification.positive_likelihood_ratio", label: "Positive likelihood ratio (LR+)" },
      { value: "classification.negative_likelihood_ratio", label: "Negative likelihood ratio (LR\u2212)" },
      { value: "classification.diagnostic_odds_ratio", label: "Diagnostic odds ratio" },
      { value: "classification.threat_score", label: "Threat score (CSI)" },
      { value: "classification.fowlkes_mallows", label: "Fowlkes-Mallows index" },
      { value: "classification.demographic_parity_difference", label: "Demographic parity difference" },
      { value: "classification.demographic_parity_ratio", label: "Demographic parity ratio" },
      { value: "classification.equalized_odds_difference", label: "Equalized odds difference" },
      { value: "classification.equalized_odds_ratio", label: "Equalized odds ratio" },
      { value: "classification.equal_opportunity_difference", label: "Equal opportunity difference" },
      { value: "classification.predictive_parity_difference", label: "Predictive parity difference" },
      { value: "classification.fpr_parity_difference", label: "FPR parity difference" },
      { value: "classification.accuracy_parity_difference", label: "Accuracy parity difference" },
      { value: "classification.cohen_kappa_linear", label: "Linear weighted kappa" },
      { value: "classification.cohen_kappa_quadratic", label: "Quadratic weighted kappa (QWK)" },
      { value: "classification.balanced_accuracy_adjusted", label: "Adjusted balanced accuracy" },
      { value: "classification.jaccard_macro", label: "Macro Jaccard" },
      { value: "classification.d2_log_loss_score", label: "D\u00b2 log-loss score" },
      { value: "classification.rms_calibration_error", label: "RMS calibration error" },
      { value: "classification.adaptive_calibration_error", label: "Adaptive calibration error" },
      { value: "classification.net_benefit", label: "Net benefit" },
      { value: "classification.pabak", label: "PABAK" },
      { value: "classification.prevalence_threshold", label: "Prevalence threshold" },
      { value: "classification.fdr_parity_difference", label: "FDR parity difference" },
      { value: "classification.for_parity_difference", label: "FOR parity difference" },
      { value: "classification.average_abs_odds_difference", label: "Average absolute odds difference" },
      { value: "classification.treatment_equality_difference", label: "Treatment equality" },
      { value: "classification.balanced_accuracy_parity_difference", label: "Balanced-accuracy parity" },
      { value: "classification.generalized_entropy_error", label: "Generalized-entropy index (fairness)" },
    ],
  },
  {
    title: "Regression & forecasting",
    options: [
      { value: "regression.rmse", label: "RMSE" },
      { value: "regression.mae", label: "MAE" },
      { value: "regression.r2", label: "R\u00b2" },
      { value: "regression.mape", label: "MAPE / sMAPE" },
      { value: "regression.mase", label: "MASE" },
      { value: "regression.pinball_loss", label: "Pinball loss" },
      { value: "regression.interval_coverage", label: "Interval coverage (PICP)" },
      { value: "regression.mean_interval_width", label: "Mean interval width" },
      { value: "regression.winkler_score", label: "Winkler interval score" },
      { value: "regression.coverage_deviation", label: "Coverage deviation" },
      { value: "regression.msle", label: "MSLE / RMSLE" },
      { value: "regression.medae", label: "Median absolute error" },
      { value: "regression.max_error", label: "Max error" },
      { value: "regression.explained_variance", label: "Explained variance" },
      { value: "regression.adjusted_r2", label: "Adjusted R\u00b2" },
      { value: "regression.aic", label: "AIC" },
      { value: "regression.bic", label: "BIC" },
      { value: "regression.aicc", label: "AICc" },
      { value: "regression.hqic", label: "Hannan-Quinn (HQIC)" },
      { value: "regression.log_likelihood_gaussian", label: "Gaussian log-likelihood" },
      { value: "regression.nrmse", label: "Normalized RMSE" },
      { value: "regression.wape", label: "WAPE" },
      { value: "regression.mean_arctangent_ape", label: "MAAPE" },
      { value: "regression.geometric_mean_absolute_error", label: "Geometric mean abs error" },
      { value: "regression.cumulative_forecast_error", label: "Cumulative forecast error" },
      { value: "regression.nash_sutcliffe_efficiency", label: "Nash-Sutcliffe efficiency" },
      { value: "regression.kling_gupta_efficiency", label: "Kling-Gupta efficiency" },
      { value: "regression.willmott_index", label: "Willmott index of agreement" },
      { value: "regression.forecast_bias", label: "Forecast bias" },
      { value: "regression.durbin_watson", label: "Durbin-Watson" },
      { value: "regression.concordance_correlation", label: "Concordance correlation (CCC)" },
      { value: "regression.huber_loss", label: "Huber loss" },
      { value: "regression.poisson_deviance", label: "Mean Poisson deviance" },
      { value: "regression.gamma_deviance", label: "Mean Gamma deviance" },
      { value: "regression.mean_tweedie_deviance", label: "Mean Tweedie deviance" },
      { value: "regression.d2_tweedie_score", label: "D\u00b2 Tweedie score" },
      { value: "regression.mean_squared_error", label: "Mean squared error" },
      { value: "regression.rmsle", label: "RMSLE" },
      { value: "regression.d2_absolute_error", label: "D\u00b2 absolute-error score" },
      { value: "regression.theil_u1", label: "Theil's U1" },
      { value: "regression.theil_u2", label: "Theil's U2" },
      { value: "regression.rmsse", label: "RMSSE" },
      { value: "regression.tracking_signal", label: "Tracking signal" },
      { value: "regression.mean_directional_accuracy", label: "Mean directional accuracy" },
      { value: "regression.relative_absolute_error", label: "Relative absolute error" },
      { value: "regression.relative_squared_error", label: "Relative squared error" },
      { value: "regression.mean_percentage_error", label: "Mean percentage error" },
      { value: "regression.median_absolute_percentage_error", label: "Median absolute % error (MdAPE)" },
      { value: "regression.root_mean_square_percentage_error", label: "RMSPE" },
      { value: "regression.legates_mccabe_efficiency", label: "Legates-McCabe E1" },
      { value: "regression.refined_willmott_index", label: "Refined index of agreement (dr)" },
      { value: "regression.fractional_bias", label: "Fractional bias" },
      { value: "regression.mean_bias_error", label: "Mean bias error (MBE)" },
      { value: "regression.log_nash_sutcliffe", label: "Log Nash-Sutcliffe (lnNSE)" },
      { value: "regression.d2_pinball_score", label: "D\u00b2 pinball score" },
      { value: "regression.breusch_pagan_lm", label: "Breusch-Pagan LM" },
      { value: "regression.breusch_pagan_fstat", label: "Breusch-Pagan F" },
      { value: "regression.white_lm", label: "White test LM" },
      { value: "regression.goldfeld_quandt_fstat", label: "Goldfeld-Quandt F" },
      { value: "regression.ols_slope", label: "OLS slope" },
      { value: "regression.ols_intercept", label: "OLS intercept" },
      { value: "regression.residual_standard_error", label: "Residual standard error" },
      { value: "regression.regression_f_statistic", label: "Regression F-statistic" },
      { value: "regression.regression_t_statistic", label: "Slope t-statistic" },
    ],
  },
  {
    title: "Data & analytics",
    options: [
      { value: "analytics.column_sum", label: "Column sum" },
      { value: "analytics.column_mean", label: "Column mean" },
      { value: "analytics.column_median", label: "Column median" },
      { value: "analytics.percentile", label: "Percentile" },
      { value: "analytics.row_count", label: "Row count" },
      { value: "analytics.groupby_aggregate", label: "Group-by aggregate" },
      { value: "analytics.distinct_count", label: "Distinct count" },
      { value: "analytics.duplicate_count", label: "Duplicate count" },
      { value: "analytics.null_fraction", label: "Null fraction" },
      { value: "analytics.growth_rate", label: "Growth rate" },
      { value: "analytics.ratio_share", label: "Share / ratio" },
      { value: "analytics.join_row_loss", label: "Join row loss" },
      { value: "analytics.column_min", label: "Column min" },
      { value: "analytics.column_max", label: "Column max" },
      { value: "analytics.column_std", label: "Column std dev" },
      { value: "analytics.iqr", label: "Interquartile range" },
      { value: "analytics.outlier_count", label: "Outlier count" },
      { value: "analytics.mode_share", label: "Mode share" },
      { value: "analytics.gini_coefficient", label: "Gini coefficient" },
      { value: "analytics.gini_mean_difference", label: "Gini mean difference" },
      { value: "analytics.relative_mean_difference", label: "Relative mean difference" },
      { value: "analytics.l_scale", label: "L-scale (L\u2082)" },
      { value: "analytics.l_cv", label: "L-coefficient of variation" },
      { value: "analytics.hhi", label: "Concentration (HHI)" },
      { value: "analytics.concentration_ratio", label: "Concentration ratio (CRk)" },
      { value: "analytics.normalized_hhi", label: "Normalized HHI" },
      { value: "analytics.rosenbluth_index", label: "Rosenbluth index" },
      { value: "analytics.comprehensive_concentration_index", label: "Comprehensive concentration index" },
      { value: "analytics.entropy", label: "Entropy" },
      { value: "analytics.shannon_diversity", label: "Shannon diversity" },
      { value: "analytics.hill_number", label: "Hill number" },
      { value: "analytics.pielou_evenness", label: "Pielou evenness" },
      { value: "analytics.berger_parker", label: "Berger-Parker dominance" },
      { value: "analytics.variance", label: "Variance" },
      { value: "analytics.range_value", label: "Range" },
      { value: "analytics.mean_abs_deviation", label: "Mean absolute deviation" },
      { value: "analytics.median_abs_deviation", label: "Median absolute deviation" },
      { value: "analytics.pearson_median_skewness", label: "Pearson median skewness" },
      { value: "analytics.studentized_range", label: "Studentized range" },
      { value: "analytics.relative_mean_deviation", label: "Relative mean deviation" },
      { value: "analytics.midhinge", label: "Midhinge" },
      { value: "analytics.trimean", label: "Trimean" },
      { value: "analytics.hodges_lehmann_estimator", label: "Hodges-Lehmann estimator" },
      { value: "analytics.gastwirth_location", label: "Gastwirth location" },
      { value: "analytics.trimmed_mean", label: "Trimmed mean" },
      { value: "analytics.winsorized_mean", label: "Winsorized mean" },
      { value: "analytics.winsorized_std", label: "Winsorized std" },
      { value: "analytics.trimmed_std", label: "Trimmed std" },
      { value: "analytics.geometric_mean", label: "Geometric mean" },
      { value: "analytics.harmonic_mean", label: "Harmonic mean" },
      { value: "analytics.weighted_mean", label: "Weighted mean" },
      { value: "analytics.covariance", label: "Covariance" },
      { value: "analytics.theil_index", label: "Theil index" },
      { value: "analytics.atkinson_index", label: "Atkinson index" },
      { value: "analytics.hoover_index", label: "Hoover (Robin Hood) index" },
      { value: "analytics.mean_log_deviation", label: "Mean log deviation" },
      { value: "analytics.generalized_entropy_index", label: "Generalized entropy index" },
      { value: "analytics.percentile_ratio", label: "P90/P10 ratio" },
      { value: "analytics.quartile_coefficient_dispersion", label: "Quartile coefficient of dispersion" },
      { value: "analytics.index_of_dispersion", label: "Index of dispersion (Fano)" },
      { value: "analytics.uniqueness_ratio", label: "Uniqueness ratio" },
      { value: "analytics.ljung_box", label: "Ljung-Box test" },
      { value: "analytics.power_mean", label: "Power mean" },
      { value: "analytics.lehmer_mean", label: "Lehmer mean" },
      { value: "analytics.geometric_std", label: "Geometric standard deviation" },
      { value: "analytics.root_mean_square", label: "Root mean square" },
      { value: "analytics.renyi_entropy", label: "R\u00e9nyi entropy" },
      { value: "analytics.tsallis_entropy", label: "Tsallis entropy" },
      { value: "analytics.margalef_richness", label: "Margalef richness" },
      { value: "analytics.menhinick_richness", label: "Menhinick richness" },
      { value: "analytics.mcintosh_diversity", label: "McIntosh diversity" },
      { value: "analytics.sen_welfare", label: "Sen welfare" },
      { value: "analytics.simpson_evenness", label: "Simpson evenness" },
      { value: "analytics.euclidean_distance", label: "Euclidean distance" },
      { value: "analytics.squared_euclidean_distance", label: "Squared Euclidean distance" },
      { value: "analytics.manhattan_distance", label: "Manhattan distance" },
      { value: "analytics.chebyshev_distance", label: "Chebyshev distance" },
      { value: "analytics.cosine_distance", label: "Cosine distance" },
      { value: "analytics.braycurtis_distance", label: "Bray-Curtis dissimilarity" },
      { value: "analytics.canberra_distance", label: "Canberra distance" },
      { value: "analytics.correlation_distance", label: "Correlation distance" },
      { value: "analytics.minkowski_distance", label: "Minkowski distance" },
      { value: "analytics.dice_distance", label: "Dice distance" },
      { value: "analytics.rogers_tanimoto_distance", label: "Rogers-Tanimoto distance" },
      { value: "analytics.russell_rao_distance", label: "Russell-Rao distance" },
      { value: "analytics.sokal_sneath_distance", label: "Sokal-Sneath distance" },
      { value: "analytics.yule_distance", label: "Yule distance" },
      { value: "analytics.hamming_distance", label: "Hamming distance" },
    ],
  },
  {
    title: "Performance & engineering",
    options: [
      { value: "engineering.speedup_ratio", label: "Speedup ratio" },
      { value: "engineering.latency_p50", label: "Latency p50" },
      { value: "engineering.latency_p95", label: "Latency p95" },
      { value: "engineering.latency_p99", label: "Latency p99" },
      { value: "engineering.throughput", label: "Throughput" },
      { value: "engineering.peak_memory", label: "Peak memory" },
      { value: "engineering.test_coverage", label: "Test coverage" },
      { value: "engineering.error_rate", label: "Error rate" },
      { value: "engineering.latency_p90", label: "Latency p90" },
      { value: "engineering.apdex", label: "Apdex" },
      { value: "engineering.uptime_pct", label: "Uptime" },
      { value: "engineering.cache_hit_rate", label: "Cache hit rate" },
      { value: "engineering.latency_p75", label: "Latency p75" },
      { value: "engineering.latency_p999", label: "Latency p99.9" },
      { value: "engineering.tail_latency_ratio", label: "Tail latency ratio" },
      { value: "engineering.latency_stddev", label: "Latency std dev" },
      { value: "engineering.jitter", label: "Jitter" },
      { value: "engineering.slo_attainment", label: "SLO attainment" },
      { value: "engineering.error_budget_burn", label: "Error budget burn" },
      { value: "engineering.compression_ratio", label: "Compression ratio" },
      { value: "engineering.availability", label: "Availability" },
      { value: "engineering.mtbf", label: "Mean time between failures" },
      { value: "engineering.failure_rate", label: "Failure rate" },
      { value: "engineering.mean_time_to_repair", label: "MTTR" },
      { value: "engineering.mean_time_to_failure", label: "MTTF" },
      { value: "engineering.defect_density", label: "Defect density" },
      { value: "engineering.dpmo", label: "DPMO" },
      { value: "engineering.first_pass_yield", label: "First-pass yield" },
      { value: "engineering.rolled_throughput_yield", label: "Rolled throughput yield" },
    ],
  },
  {
    title: "Retrieval, RAG & LLM evals",
    options: [
      { value: "retrieval.recall_at_k", label: "Recall@k" },
      { value: "retrieval.ndcg_at_k", label: "NDCG@k" },
      { value: "retrieval.mrr", label: "MRR" },
      { value: "retrieval.top_k_accuracy", label: "Top-k accuracy" },
      { value: "retrieval.exact_match", label: "Exact match" },
      { value: "retrieval.pass_at_k", label: "pass@k" },
      { value: "retrieval.precision_at_k", label: "Precision@k" },
      { value: "retrieval.map_at_k", label: "MAP@k" },
      { value: "retrieval.perplexity", label: "Perplexity" },
      { value: "retrieval.wer", label: "WER / CER" },
      { value: "retrieval.r_precision", label: "R-precision" },
      { value: "retrieval.mean_average_precision", label: "MAP (uncapped)" },
      { value: "retrieval.f1_at_k", label: "F1@k" },
      { value: "retrieval.fallout_at_k", label: "Fall-out@k" },
      { value: "retrieval.rbp", label: "Rank-biased precision" },
      { value: "retrieval.err_at_k", label: "Expected reciprocal rank" },
      { value: "retrieval.success_at_k", label: "Success@k" },
      { value: "retrieval.arhr_at_k", label: "Average reciprocal hit rank" },
      { value: "retrieval.token_f1", label: "Token F1" },
      { value: "retrieval.token_jaccard", label: "Token Jaccard" },
      { value: "retrieval.token_dice", label: "Token Dice" },
      { value: "retrieval.levenshtein_similarity", label: "Levenshtein similarity" },
      { value: "retrieval.indel_similarity", label: "Indel (LCS) similarity" },
      { value: "retrieval.jaro_similarity", label: "Jaro similarity" },
      { value: "retrieval.jaro_winkler_similarity", label: "Jaro-Winkler similarity" },
      { value: "retrieval.longest_common_subsequence", label: "Longest common subsequence" },
    ],
  },
  {
    title: "Statistical claims",
    options: [
      { value: "stats.p_value", label: "p-value" },
      { value: "stats.confidence_interval", label: "Confidence interval" },
      { value: "stats.lift", label: "A/B lift" },
      { value: "stats.chi_square", label: "Chi-square" },
      { value: "stats.correlation", label: "Correlation" },
      { value: "stats.numerai_corr", label: "Numerai CORR" },
      { value: "stats.numerai_sharpe", label: "Numerai Sharpe" },
      { value: "stats.mmc", label: "Numerai MMC" },
      { value: "stats.feature_neutral_corr", label: "Numerai FNC" },
      { value: "stats.max_feature_exposure", label: "Max feature exposure" },
      { value: "stats.effect_size", label: "Effect size" },
      { value: "stats.mann_whitney", label: "Mann-Whitney U" },
      { value: "stats.ks_test", label: "KS test" },
      { value: "stats.anova", label: "One-way ANOVA" },
      { value: "stats.proportion_z", label: "Two-proportion z-test" },
      { value: "stats.fisher_exact", label: "Fisher's exact test" },
      { value: "stats.odds_ratio", label: "Odds ratio" },
      { value: "stats.relative_risk", label: "Relative risk" },
      { value: "stats.cramers_v", label: "Cram\u00e9r's V" },
      { value: "stats.skewness", label: "Skewness" },
      { value: "stats.kurtosis", label: "Kurtosis" },
      { value: "stats.bowley_skewness", label: "Bowley skewness" },
      { value: "stats.moors_kurtosis", label: "Moors kurtosis" },
      { value: "stats.l_skewness", label: "L-skewness" },
      { value: "stats.l_kurtosis", label: "L-kurtosis" },
      { value: "stats.jarque_bera", label: "Jarque-Bera" },
      { value: "stats.autocorrelation", label: "Autocorrelation" },
      { value: "stats.partial_autocorrelation", label: "Partial autocorrelation" },
      { value: "stats.box_pierce", label: "Box-Pierce Q" },
      { value: "stats.permutation_entropy", label: "Permutation entropy" },
      { value: "stats.runs_test", label: "Wald-Wolfowitz runs test" },
      { value: "stats.arch_lm", label: "Engle ARCH-LM" },
      { value: "stats.point_biserial", label: "Point-biserial correlation" },
      { value: "stats.kendall_tau", label: "Kendall's tau-b" },
      { value: "stats.distance_correlation", label: "Distance correlation" },
      { value: "stats.somers_d", label: "Somers' D" },
      { value: "stats.goodman_kruskal_gamma", label: "Goodman-Kruskal \u03b3" },
      { value: "stats.theil_sen_slope", label: "Theil-Sen slope" },
      { value: "stats.cliffs_delta", label: "Cliff's delta" },
      { value: "stats.rank_biserial", label: "Rank-biserial correlation" },
      { value: "stats.hedges_g", label: "Hedges' g" },
      { value: "stats.glass_delta", label: "Glass's delta" },
      { value: "stats.common_language_effect_size", label: "Common-language effect size" },
      { value: "stats.cohens_h", label: "Cohen's h" },
      { value: "stats.eta_squared", label: "Eta-squared (\u03b7\u00b2)" },
      { value: "stats.g_test", label: "G-test of independence" },
      { value: "stats.mcnemar", label: "McNemar's test" },
      { value: "stats.levene", label: "Levene's test" },
      { value: "stats.bartlett", label: "Bartlett's test" },
      { value: "stats.fligner", label: "Fligner-Killeen test" },
      { value: "stats.mood_test", label: "Mood scale test" },
      { value: "stats.ansari_bradley", label: "Ansari-Bradley test" },
      { value: "stats.brunner_munzel", label: "Brunner-Munzel test" },
      { value: "stats.kruskal_wallis", label: "Kruskal-Wallis H" },
      { value: "stats.wilcoxon_signed_rank", label: "Wilcoxon signed-rank" },
      { value: "stats.anderson_darling", label: "Anderson-Darling A\u00b2" },
      { value: "stats.wilson_lower", label: "Wilson CI (lower)" },
      { value: "stats.wilson_upper", label: "Wilson CI (upper)" },
      { value: "stats.bh_rejections", label: "Benjamini-Hochberg rejections" },
      { value: "stats.holm_rejections", label: "Holm-Bonferroni rejections" },
      { value: "stats.bonferroni_rejections", label: "Bonferroni rejections" },
      { value: "stats.sidak_rejections", label: "\u0160id\u00e1k rejections" },
      { value: "stats.holm_sidak_rejections", label: "Holm-\u0160id\u00e1k rejections" },
      { value: "stats.hochberg_rejections", label: "Hochberg rejections" },
      { value: "stats.benjamini_yekutieli", label: "Benjamini-Yekutieli rejections" },
      { value: "stats.kupiec_pof", label: "Kupiec POF (VaR backtest)" },
      { value: "stats.christoffersen_independence", label: "Christoffersen independence" },
      { value: "stats.christoffersen_cc", label: "Christoffersen conditional coverage" },
      { value: "stats.var_breach_rate", label: "VaR breach rate" },
      { value: "stats.realized_shortfall", label: "Realized shortfall" },
      { value: "stats.expected_exceedance", label: "Expected exceedance" },
      { value: "stats.basel_traffic_light", label: "Basel traffic-light add-on" },
      { value: "stats.es_backtest_ratio", label: "ES backtest ratio" },
      { value: "stats.acerbi_szekely_z1", label: "Acerbi\u2013Sz\u00e9kely Z1" },
      { value: "stats.acerbi_szekely_z2", label: "Acerbi\u2013Sz\u00e9kely Z2" },
      { value: "stats.psi", label: "Population Stability Index" },
      { value: "stats.information_value", label: "Information Value (IV)" },
      { value: "stats.kl_divergence", label: "KL divergence" },
      { value: "stats.js_divergence", label: "Jensen-Shannon divergence" },
      { value: "stats.hellinger_distance", label: "Hellinger distance" },
      { value: "stats.total_variation_distance", label: "Total variation distance" },
      { value: "stats.bhattacharyya_distance", label: "Bhattacharyya distance" },
      { value: "stats.jeffreys_divergence", label: "Jeffreys divergence" },
      { value: "stats.chi_square_distance", label: "\u03c7\u00b2 distance" },
      { value: "stats.wasserstein_1d", label: "Wasserstein-1 distance" },
      { value: "stats.energy_distance", label: "Energy distance" },
      { value: "stats.ks_2samp", label: "Two-sample KS statistic" },
      { value: "stats.concordance_index", label: "Concordance index (C-index)" },
      { value: "stats.km_median_survival", label: "Kaplan-Meier median survival" },
      { value: "stats.km_survival_at", label: "Kaplan-Meier S(t)" },
      { value: "stats.nelson_aalen_cumhaz", label: "Nelson-Aalen cumulative hazard" },
      { value: "stats.restricted_mean_survival_time", label: "Restricted mean survival time" },
      { value: "stats.mutual_info_score", label: "Mutual information" },
      { value: "stats.normalized_mutual_info", label: "Normalized mutual information" },
      { value: "stats.homogeneity_score", label: "Homogeneity" },
      { value: "stats.completeness_score", label: "Completeness" },
      { value: "stats.v_measure_score", label: "V-measure" },
      { value: "stats.rand_index", label: "Rand index" },
      { value: "stats.adjusted_rand_index", label: "Adjusted Rand index" },
      { value: "stats.fowlkes_mallows_clustering", label: "Fowlkes-Mallows (clustering)" },
      { value: "stats.purity", label: "Cluster purity" },
      { value: "stats.bcubed_precision", label: "B-cubed precision" },
      { value: "stats.bcubed_recall", label: "B-cubed recall" },
      { value: "stats.bcubed_f1", label: "B-cubed F1" },
      { value: "stats.average_treatment_effect", label: "Average treatment effect" },
      { value: "stats.risk_difference", label: "Risk difference" },
      { value: "stats.relative_risk_reduction", label: "Relative risk reduction" },
      { value: "stats.number_needed_to_treat", label: "Number needed to treat" },
      { value: "stats.standardized_mean_difference", label: "Standardized mean difference" },
      { value: "stats.cuped_ate", label: "CUPED-adjusted ATE" },
      { value: "stats.variance_reduction_cuped", label: "CUPED variance reduction" },
      { value: "stats.srm_pvalue", label: "Sample ratio mismatch (SRM)" },
      { value: "stats.kstat_third", label: "Third k-statistic" },
      { value: "stats.kstat_fourth", label: "Fourth k-statistic" },
      { value: "stats.skewtest", label: "Skewness test (D'Agostino)" },
      { value: "stats.kurtosistest", label: "Kurtosis test (Anscombe-Glynn)" },
      { value: "stats.normaltest", label: "Normality test (omnibus)" },
      { value: "stats.wilcoxon_rank_sum", label: "Wilcoxon rank-sum" },
      { value: "stats.mood_median_test", label: "Mood's median test" },
      { value: "stats.differential_entropy", label: "Differential entropy (Vasicek)" },
      { value: "stats.tschuprow_t", label: "Tschuprow's T" },
      { value: "stats.pearson_contingency_coefficient", label: "Contingency coefficient (C)" },
      { value: "stats.cohens_w", label: "Cohen's w" },
      { value: "stats.omega_squared", label: "Omega-squared (\u03c9\u00b2)" },
      { value: "stats.epsilon_squared", label: "Epsilon-squared (\u03b5\u00b2)" },
      { value: "stats.cohens_f", label: "Cohen's f" },
      { value: "stats.zero_crossing_rate", label: "Zero-crossing rate" },
      { value: "stats.hjorth_mobility", label: "Hjorth mobility" },
      { value: "stats.hjorth_complexity", label: "Hjorth complexity" },
      { value: "stats.turning_point_rate", label: "Turning-point rate" },
      { value: "stats.rms_successive_differences", label: "RMSSD" },
      { value: "stats.mean_absolute_change", label: "Mean absolute change" },
      { value: "stats.siegel_slope", label: "Siegel slope" },
      { value: "stats.linregress_slope_stderr", label: "Slope standard error" },
      { value: "stats.linregress_intercept_stderr", label: "Intercept standard error" },
      { value: "stats.chatterjee_xi", label: "Chatterjee's \u03be" },
      { value: "stats.blomqvist_beta", label: "Blomqvist's \u03b2" },
      { value: "stats.gaussian_rank_correlation", label: "Gaussian-rank correlation" },
      { value: "stats.conditional_entropy", label: "Conditional entropy" },
      { value: "stats.joint_entropy", label: "Joint entropy" },
      { value: "stats.variation_of_information", label: "Variation of information" },
      { value: "stats.uncertainty_coefficient", label: "Uncertainty coefficient (Theil's U)" },
      { value: "stats.symmetric_uncertainty", label: "Symmetric uncertainty" },
      { value: "stats.normalized_variation_of_information", label: "Normalized VI" },
    ],
  },
  {
    title: "Business & finance",
    options: [
      { value: "finance.cagr", label: "CAGR" },
      { value: "finance.npv", label: "NPV" },
      { value: "finance.irr", label: "IRR" },
      { value: "finance.churn_rate", label: "Churn / retention" },
      { value: "finance.margin_pct", label: "Margin" },
      { value: "finance.return_on_equity", label: "Return on equity" },
      { value: "finance.return_on_assets", label: "Return on assets" },
      { value: "finance.return_on_invested_capital", label: "Return on invested capital" },
      { value: "finance.asset_turnover", label: "Asset turnover" },
      { value: "finance.days_sales_outstanding", label: "Days sales outstanding" },
      { value: "finance.operating_margin", label: "Operating margin" },
      { value: "finance.net_margin", label: "Net margin" },
      { value: "finance.free_cash_flow_margin", label: "FCF margin" },
      { value: "finance.dividend_payout_ratio", label: "Dividend payout ratio" },
      { value: "finance.reconciliation_total", label: "Reconciliation" },
      { value: "finance.bond_price", label: "Bond price (PV)" },
      { value: "finance.macaulay_duration", label: "Macaulay duration" },
      { value: "finance.modified_duration", label: "Modified duration" },
      { value: "finance.convexity", label: "Convexity" },
      { value: "finance.dv01", label: "DV01 / PV01" },
      { value: "finance.weighted_average_life", label: "Weighted avg life" },
      { value: "finance.yield_to_maturity", label: "Yield to maturity" },
      { value: "finance.par_yield", label: "Par yield" },
      { value: "finance.annuity_factor", label: "Annuity factor" },
      { value: "finance.forward_rate", label: "Forward rate" },
      { value: "finance.curve_pv", label: "Curve PV (multi-curve)" },
      { value: "finance.effective_duration", label: "Effective duration" },
      { value: "finance.effective_convexity", label: "Effective convexity" },
      { value: "finance.spread_duration", label: "Spread duration" },
      { value: "finance.spread_dv01", label: "Spread DV01" },
      { value: "finance.z_spread", label: "Z-spread" },
      { value: "finance.modified_irr", label: "Modified IRR (MIRR)" },
      { value: "finance.profitability_index", label: "Profitability index" },
      { value: "finance.equivalent_annual_annuity", label: "Equivalent annual annuity" },
      { value: "finance.days_inventory_outstanding", label: "Days inventory outstanding" },
      { value: "finance.days_payable_outstanding", label: "Days payable outstanding" },
      { value: "finance.cash_conversion_cycle", label: "Cash conversion cycle" },
      { value: "finance.fixed_charge_coverage", label: "Fixed-charge coverage" },
    ],
  },
  {
    title: "Fund & LP economics",
    options: [
      { value: "fund.tvpi", label: "TVPI" },
      { value: "fund.dpi", label: "DPI" },
      { value: "fund.rvpi", label: "RVPI" },
      { value: "fund.called_pct", label: "Called %" },
      { value: "fund.carried_interest", label: "Carried interest" },
      { value: "fund.realization_ratio", label: "Realization ratio" },
      { value: "fund.ks_pme", label: "Kaplan-Schoar PME" },
      { value: "fund.direct_alpha", label: "Direct Alpha" },
      { value: "fund.pme_plus_lambda", label: "PME+ lambda" },
    ],
  },
  {
    title: "Execution & transaction cost",
    options: [
      { value: "execution.implementation_shortfall", label: "Implementation shortfall" },
      { value: "execution.arrival_slippage", label: "Arrival slippage" },
      { value: "execution.vwap_slippage", label: "VWAP slippage" },
      { value: "execution.effective_spread_bps", label: "Effective spread" },
      { value: "execution.participation_rate", label: "Participation rate" },
      { value: "execution.realized_spread_bps", label: "Realized spread" },
      { value: "execution.price_impact_bps", label: "Price impact" },
    ],
  },
  {
    title: "Exposure & operational risk",
    options: [
      { value: "exposure.gross_exposure", label: "Gross exposure" },
      { value: "exposure.net_exposure", label: "Net exposure" },
      { value: "exposure.long_exposure", label: "Long exposure" },
      { value: "exposure.short_exposure", label: "Short exposure" },
      { value: "exposure.long_short_ratio", label: "Long/short ratio" },
      { value: "exposure.largest_position", label: "Largest position" },
      { value: "exposure.liquidity_coverage", label: "Liquidity coverage" },
    ],
  },
  {
    title: "Liquidity & microstructure",
    options: [
      { value: "liquidity.amihud_illiquidity", label: "Amihud illiquidity" },
      { value: "liquidity.amivest_liquidity", label: "Amivest liquidity" },
      { value: "liquidity.roll_spread", label: "Roll effective spread" },
      { value: "liquidity.kyle_lambda", label: "Kyle's lambda" },
      { value: "liquidity.vwap", label: "VWAP" },
      { value: "liquidity.relative_spread", label: "Relative quoted spread" },
      { value: "liquidity.corwin_schultz_spread", label: "Corwin-Schultz spread" },
      { value: "liquidity.abdi_ranaldo_spread", label: "Abdi-Ranaldo spread" },
      { value: "liquidity.order_flow_imbalance", label: "Order-flow imbalance" },
      { value: "liquidity.share_turnover", label: "Share turnover" },
    ],
  },
  {
    title: "Options & derivatives risk",
    options: [
      { value: "derivatives.bs_value", label: "Book value (Black-Scholes)" },
      { value: "derivatives.bs_delta", label: "Book delta" },
      { value: "derivatives.bs_gamma", label: "Book gamma" },
      { value: "derivatives.bs_vega", label: "Book vega" },
      { value: "derivatives.bs_theta", label: "Book theta" },
      { value: "derivatives.bs_rho", label: "Book rho" },
      { value: "derivatives.bs_vanna", label: "Book vanna" },
      { value: "derivatives.bs_volga", label: "Book volga / vomma" },
      { value: "derivatives.bs_speed", label: "Book speed" },
      { value: "derivatives.bs_zomma", label: "Book zomma" },
      { value: "derivatives.bs_charm", label: "Book charm" },
      { value: "derivatives.bs_color", label: "Book color" },
      { value: "derivatives.bs_veta", label: "Book veta" },
      { value: "derivatives.bs_ultima", label: "Book ultima" },
      { value: "derivatives.bs_lambda", label: "Book lambda (elasticity)" },
      { value: "derivatives.bs_implied_vol", label: "Implied vol" },
    ],
  },
  {
    title: "Credit & default risk",
    options: [
      { value: "credit.expected_loss", label: "Expected loss" },
      { value: "credit.expected_loss_rate", label: "Expected loss rate" },
      { value: "credit.weighted_lgd", label: "Exposure-weighted LGD" },
      { value: "credit.unexpected_loss", label: "Unexpected loss" },
      { value: "credit.asrf_capital_requirement", label: "ASRF capital (Basel IRB)" },
      { value: "credit.asrf_rwa", label: "Risk-weighted assets" },
      { value: "credit.vasicek_conditional_pd", label: "Vasicek conditional PD" },
      { value: "credit.recovery_rate", label: "Recovery rate" },
      { value: "credit.exposure_weighted_pd", label: "Exposure-weighted PD" },
      { value: "credit.exposure_weighted_maturity", label: "Exposure-weighted maturity" },
      { value: "credit.altman_z", label: "Altman Z-score" },
      { value: "credit.altman_z_prime", label: "Altman Z\u2033-score" },
      { value: "credit.merton_distance_to_default", label: "Merton distance-to-default" },
      { value: "credit.merton_pd", label: "Merton default probability" },
      { value: "credit.debt_to_ebitda", label: "Debt / EBITDA" },
      { value: "credit.net_debt_to_ebitda", label: "Net debt / EBITDA" },
      { value: "credit.interest_coverage", label: "Interest coverage" },
      { value: "credit.debt_to_equity", label: "Debt / equity" },
      { value: "credit.current_ratio", label: "Current ratio" },
      { value: "credit.quick_ratio", label: "Quick ratio" },
      { value: "credit.ebitda_margin", label: "EBITDA margin" },
      { value: "credit.altman_z_double_prime", label: "Altman Z''-score" },
      { value: "credit.springate_score", label: "Springate S-score" },
      { value: "credit.zmijewski_score", label: "Zmijewski X-score" },
      { value: "credit.capital_adequacy_ratio", label: "Capital adequacy ratio (CAR)" },
      { value: "credit.tier1_leverage_ratio", label: "Tier-1 leverage ratio" },
      { value: "credit.provision_coverage_ratio", label: "Provision coverage ratio" },
      { value: "credit.cds_implied_hazard", label: "CDS-implied hazard rate" },
    ],
  },
  {
    title: "Portfolio construction & attribution",
    options: [
      { value: "portfolio.brinson_allocation", label: "Brinson allocation effect" },
      { value: "portfolio.brinson_selection", label: "Brinson selection effect" },
      { value: "portfolio.brinson_interaction", label: "Brinson interaction" },
      { value: "portfolio.brinson_total_active", label: "Total active return" },
      { value: "portfolio.brinson_fachler_allocation", label: "Brinson-Fachler allocation" },
      { value: "portfolio.geometric_excess_return", label: "Geometric excess return" },
      { value: "portfolio.active_share", label: "Active share" },
      { value: "portfolio.portfolio_turnover", label: "Turnover" },
      { value: "portfolio.effective_number_of_bets", label: "Effective number of bets" },
    ],
  },
  {
    title: "Compiled recipes",
    options: [
      { value: "compiled.sem", label: "Standard error of the mean" },
      { value: "compiled.coefficient_of_variation", label: "Coefficient of variation" },
    ],
  },
];
