"""SOTA validation of the full recipe library against published reference implementations.

assets/reference_vectors.json is generated by calibration/gen_reference_vectors.py from
scikit-learn / SciPy / NumPy (plus the HumanEval pass@k estimator and the Guo et al. ECE
definition). This suite re-runs every case through Calma's deterministic kernels and recipes -
pure stdlib here, per the repo rule - and then exercises the recipe layer: convention parsing,
degenerate paths, bit-stability, string-tag columns and cross-artifact bindings end-to-end.
Run: python3 test_recipes_sota.py
"""
import csv
import json
import math
import os
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, ".."))
import numeric as N  # noqa: E402
import recipes as R  # noqa: E402
import recompute as RC  # noqa: E402
import compare as C  # noqa: E402
import draft_contract as D  # noqa: E402

VECTORS = os.path.join(HERE, "..", "..", "assets", "reference_vectors.json")

_n = _fail = 0


def isnan(x):
    return isinstance(x, float) and x != x


def approx(got, want, atol, rtol, label):
    global _n, _fail
    _n += 1
    if not (abs(got - want) <= atol + rtol * abs(want)):
        _fail += 1
        print("  FAIL [%s] got %r want %r (atol %g rtol %g)" % (label, got, want, atol, rtol))


def truth(cond, label):
    global _n, _fail
    _n += 1
    if not cond:
        _fail += 1
        print("  FAIL [%s]" % label)


# ---------------- part A: every reference vector ----------------

KINDS = {
    "total_return": lambda a: N.total_return(a["rets"]),
    "sharpe": lambda a: N.sharpe(a["rets"], a["periods"])[0],
    "max_drawdown": lambda a: N.max_drawdown(a["rets"]),
    "rmse": lambda a: N.rmse(a["pred"], a["actual"]),
    "mae": lambda a: N.mae(a["pred"], a["actual"]),
    "r2": lambda a: N.r2(a["pred"], a["actual"]),
    "accuracy": lambda a: N.accuracy(a["preds"], a["labels"]),
    "precision": lambda a: N.precision(a["preds"], a["labels"]),
    "recall": lambda a: N.recall(a["preds"], a["labels"]),
    "f1": lambda a: N.f1(a["preds"], a["labels"]),
    "auc": lambda a: N.auc(a["scores"], a["labels"]),
    "brier": lambda a: N.brier(a["probs"], a["labels"]),
    "column_sum": lambda a: N.col_sum(a["xs"]),
    "column_mean": lambda a: N.col_mean(a["xs"]),
    "quantile": lambda a: N.quantile(a["xs"], a["q"]),
    "speedup": lambda a: N.speedup_ratio(a["before"], a["after"], a["mode"]),
    "throughput": lambda a: N.throughput(a["durs"]),
    "peak": lambda a: N.peak(a["xs"]),
    "coverage": lambda a: N.coverage_fraction(a["hits"]),
    "error_rate": lambda a: N.error_rate(a["flags"], a["mode"]),
    "null_fraction": lambda a: N.null_fraction(a["raw"]),
    "distinct_count": lambda a: N.distinct_count(a["raw"], a["include_null"]),
    "duplicate_count": lambda a: N.duplicate_count(a["raw"]),
    "growth_rate": lambda a: N.growth_rate(a["xs"], a["mode"]),
    "ratio_share": lambda a: N.ratio_share(a["flags"]),
    "groupby": lambda a: N.groupby_aggregate(a["groups"], a["values"], a["agg"], a["label"])[0],
    "recall_at_k": lambda a: N.recall_at_k(a["queries"], a["ranks"], a["rels"], a["k"]),
    "ndcg_at_k": lambda a: N.ndcg_at_k(a["queries"], a["ranks"], a["rels"], a["k"], a["gain"]),
    "mrr": lambda a: N.mrr(a["queries"], a["ranks"], a["rels"], a["k"]),
    "hit_at_k": lambda a: N.hit_at_k(a["queries"], a["ranks"], a["rels"], a["k"]),
    "pass_at_k": lambda a: N.pass_at_k(a["problems"], a["corrects"], a["k"]),
    "macro_f1": lambda a: N.macro_f1(a["preds"], a["labels"]),
    "micro_f1": lambda a: N.micro_f1(a["preds"], a["labels"]),
    "mcc": lambda a: N.mcc(a["preds"], a["labels"]),
    "average_precision": lambda a: N.average_precision(a["scores"], a["labels"]),
    "log_loss": lambda a: N.log_loss(a["probs"], a["labels"], a["clip"]),
    "ece": lambda a: N.ece(a["probs"], a["labels"], a["bins"]),
    "t_test_p": lambda a: N.t_test_p(a["a"], a["b"], a["mode"]),
    "ci_half_width": lambda a: N.ci_half_width(a["xs"], a["level"], a["dist"]),
    "lift": lambda a: N.lift(a["a"], a["b"], a["mode"]),
    "chi_square": lambda a: N.chi_square(a["groups"], a["outcomes"], a["yates"], a["output"]),
    "correlation": lambda a: (N.spearman_r(a["xs"], a["ys"]) if a["mode"] == "spearman"
                              else N.pearson_r(a["xs"], a["ys"])),
    "cohen_d": lambda a: N.cohen_d(a["a"], a["b"], a["mode"]),
    "cagr": lambda a: N.cagr(a["xs"], a["ppy"]),
    "npv": lambda a: N.npv(a["cashflows"], a["rate"]),
    "irr": lambda a: N.irr(a["cashflows"]),
    "churn_rate": lambda a: N.churn_rate(a["flags"], a["mode"]),
    "margin_pct": lambda a: N.margin_pct(a["revenue"], a["cost"]),
    "reconciliation": lambda a: N.reconciliation_diff(a["a"], a["b"]),
    "mape": lambda a: N.mape(a["pred"], a["actual"], a["symmetric"]),
    "mase": lambda a: N.mase(a["pred"], a["actual"], a["m"]),
    "pinball": lambda a: N.pinball(a["pred"], a["actual"], a["q"]),
    "dlog": lambda a: N.dlog(a["x"]),
    "dexp": lambda a: N.dexp(a["x"]),
    "dlgamma": lambda a: N.dlgamma(a["z"]),
    "betainc": lambda a: N.betainc_reg(a["a"], a["b"], a["x"]),
    "gammaincc": lambda a: N.gammainc_upper_reg(a["s"], a["x"]),
    "erfc": lambda a: N.derfc(a["x"]),
    "t_sf2": lambda a: N.t_sf_two_sided(a["t"], a["df"]),
    "chi2_sf": lambda a: N.chi2_sf(a["x"], a["df"]),
    "t_ppf2": lambda a: N.t_ppf_two_sided(a["alpha"], a["df"]),
    "z_ppf2": lambda a: N.z_ppf_two_sided(a["alpha"]),
}

doc = json.load(open(VECTORS))
seen_kinds = set()
for case in doc["cases"]:
    seen_kinds.add(case["kind"])
    got = KINDS[case["kind"]](case["args"])
    approx(got, case["expected"], case["atol"], case["rtol"], "ref:" + case["id"])
truth(set(KINDS) == seen_kinds, "every dispatch kind exercised by the vector file")
truth(len(doc["cases"]) >= 290, "reference corpus is full-size (%d cases)" % len(doc["cases"]))

# ---------------- part B: registry completeness + manifest sanity ----------------

EXPECTED = {
    # the original 15
    "total_return", "sharpe", "max_drawdown", "accuracy", "auc", "precision", "recall", "f1",
    "brier", "rmse", "mae", "r2", "column_sum", "column_mean", "row_count",
    # pack 1
    "speedup_ratio", "latency_p50", "latency_p95", "latency_p99", "throughput", "peak_memory",
    "test_coverage", "error_rate",
    # pack 2
    "column_median", "percentile", "groupby_aggregate", "distinct_count", "growth_rate",
    "ratio_share", "null_fraction", "duplicate_count", "join_row_loss",
    # pack 3
    "recall_at_k", "ndcg_at_k", "mrr", "exact_match", "pass_at_k", "top_k_accuracy",
    "macro_f1", "micro_f1", "pr_auc", "log_loss", "mcc", "ece",
    # pack 4
    "p_value", "confidence_interval", "lift", "chi_square", "correlation", "effect_size",
    # pack 5
    "cagr", "npv", "irr", "churn_rate", "margin_pct", "reconciliation_total",
    # pack 6
    "mape", "mase", "pinball_loss",
}
truth(set(R.ids()) == EXPECTED, "registry holds exactly the 59 recipes (got %d)" % len(R.ids()))
for mid in R.ids():
    fn = R.get(mid)
    truth(isinstance(fn.manifest.get("family"), str) and fn.manifest.get("required_tags") is not None,
          "manifest complete: %s" % mid)
    stags = set(fn.manifest.get("string_tags") or [])
    truth(stags <= set(fn.manifest.get("required_tags") or []), "string_tags subset of required: %s" % mid)

# ---------------- part C: recipe layer - conventions, degenerate paths, bit-stability ----------------

res = R.get("percentile")({"v": [1.0, 2.0, 3.0, 4.0]}, {"value": "v"}, "p75")
approx(res["value"], 3.25, 1e-12, 0, "percentile recipe p75")
truth(R.get("percentile")({"v": [1.0, 2.0]}, {"value": "v"}, None)["degenerate"],
      "percentile without a quantile convention degrades to degenerate")
approx(R.get("percentile")({"v": [1.0, 2.0, 3.0, 4.0]}, {"value": "v"}, "q=0.75")["value"],
       3.25, 1e-12, 0, "percentile q=0.75 spelling")

rq = {"q": ["a", "a", "b", "b"], "r": [1.0, 2.0, 1.0, 2.0], "rel": [0.0, 1.0, 1.0, 0.0]}
res = R.get("recall_at_k")(rq, {"query": "q", "rank": "r", "relevance": "rel"}, "k=1")
approx(res["value"], 0.5, 1e-12, 0, "recall_at_k k=1 hand case")
res = R.get("ndcg_at_k")(rq, {"query": "q", "rank": "r", "relevance": "rel"}, "k=2,exp")
truth(res["terms"]["gain"] == "exp" and res["terms"]["k"] == 2, "ndcg convention 'k=2,exp' parsed")
res = R.get("ece")({"p": [0.9, 0.1], "y": [1.0, 0.0]}, {"prob": "p", "label": "y"}, "bins=10")
approx(res["value"], 0.1, 1e-12, 0, "ece bins=10 hand case")  # both bins: |acc-conf| = .1
res = R.get("confidence_interval")({"v": [1.0, 2.0, 3.0, 4.0]}, {"value": "v"}, "z95")
truth(res["terms"]["dist"] == "z" and res["terms"]["level"] == 0.95, "ci convention 'z95' parsed")
res = R.get("chi_square")({"g": ["a", "a", "b", "b"], "o": ["x", "y", "x", "y"]},
                          {"group": "g", "outcome": "o"}, "statistic-no-yates")
truth(res["terms"]["output"] == "statistic" and not res["terms"]["yates"], "chi2 convention parsed")
res = R.get("pass_at_k")({"p": ["t1"] * 4, "c": [1.0, 0.0, 0.0, 0.0]}, {"problem": "p", "correct": "c"}, "k=2")
approx(res["value"], 1.0 - (3 * 2) / (4 * 3), 1e-12, 0, "pass@2 n=4 c=1 exact combinatorics")
truth(R.get("pass_at_k")({"p": ["t1"] * 2, "c": [1.0, 0.0]}, {"problem": "p", "correct": "c"},
                         "k=5")["degenerate"], "pass@k with k > n is degenerate, never silently valid")

# exact_match: strict vs SQuAD-normalized
em_cols = {"p": ["The Cat", "dog!", "x"], "r": ["cat", "a dog", "y"]}
approx(R.get("exact_match")(em_cols, {"prediction": "p", "reference": "r"}, None)["value"],
       0.0, 0, 0, "exact_match strict")
approx(R.get("exact_match")(em_cols, {"prediction": "p", "reference": "r"}, "normalized")["value"],
       2.0 / 3.0, 1e-12, 0, "exact_match normalized (case/punct/articles)")

# groupby: no label -> degenerate (no scalar to compare), per-group kept in terms
res = R.get("groupby_aggregate")({"g": ["w", "e"], "v": [1.0, 2.0]}, {"group": "g", "value": "v"}, "sum")
truth(res["degenerate"] and res["terms"]["groups"] == {"w": 1.0, "e": 2.0},
      "groupby without group label is degenerate with per-group terms")
approx(R.get("groupby_aggregate")({"g": ["w", "e", "w"], "v": [1.0, 2.0, 4.0]},
                                  {"group": "g", "value": "v"}, "sum:w")["value"],
       5.0, 0, 0, "groupby sum:w")

# log_loss exact vs clip on a wrong-side hard zero
ll = {"p": [0.0, 0.9], "y": [1.0, 1.0]}
truth(R.get("log_loss")(ll, {"prob": "p", "label": "y"}, None)["degenerate"],
      "log_loss exact mode: p=0 on a positive -> degenerate (inf), never a quiet number")
truth(not R.get("log_loss")(ll, {"prob": "p", "label": "y"}, "clip")["degenerate"],
      "log_loss clip mode stays finite")

# pack 5/6 recipe layer: conventions + degenerate paths
truth(R.get("npv")({"cf": [-100.0, 60.0, 60.0]}, {"cashflow": "cf"}, None)["degenerate"],
      "npv without a rate convention degrades to degenerate")
res = R.get("npv")({"cf": [-100.0, 60.0, 60.0]}, {"cashflow": "cf"}, "rate=0.0")
approx(res["value"], 20.0, 1e-12, 0, "npv rate=0 = plain sum")
truth(isnan(N.irr([100.0, 50.0])), "irr with no sign change -> nan")
r_irr = N.irr([-1000.0, 1100.0])
approx(r_irr, 0.1, 1e-10, 0, "irr single-period hand case = 10%")
truth(isnan(N.mape([1.0, 2.0], [0.0, 2.0])), "mape with a zero actual -> nan, never an epsilon fudge")
res = R.get("pinball_loss")({"p": [1.0, 3.0], "t": [2.0, 2.0]}, {"prediction": "p", "target": "t"}, None)
approx(res["value"], 0.5, 1e-12, 0, "pinball default q=0.5 hand case")
res = R.get("cagr")({"v": [100.0, 121.0]}, {"value": "v"}, None)
approx(res["value"], 0.21, 1e-12, 0, "cagr 1 period annual = simple growth")
res = R.get("churn_rate")({"f": [1.0, 0.0, 0.0, 0.0]}, {"flag": "f"}, "retention")
approx(res["value"], 0.75, 1e-12, 0, "churn_rate retention convention")
truth(isnan(N.mase([1.0, 2.0], [5.0, 5.0], 1)), "mase on a flat series -> nan (zero scale)")
truth(isnan(N.margin_pct([0.0, 0.0], [1.0])), "margin with zero revenue -> nan")

# NaN propagation across the new families
nan = float("nan")
truth(isnan(N.quantile([1.0, nan], 0.5)), "quantile NaN -> nan")
truth(isnan(N.t_test_p([1.0, nan, 2.0], [1.0, 2.0, 3.0])), "t_test NaN -> nan")
truth(isnan(N.speedup_ratio([1.0], [nan])), "speedup NaN -> nan")
truth(isnan(N.ece([nan], [1], 15)), "ece NaN -> nan")
truth(isnan(N.pearson_r([1.0, 2.0], [nan, 1.0])), "pearson NaN -> nan")
truth(isnan(N.growth_rate([100.0], "period")), "growth_rate n<2 -> nan")
truth(isnan(N.lift([0.0, 0.0], [1.0]) ), "lift zero control mean -> nan")
truth(isnan(N.chi_square(["a", "a"], ["x", "y"])), "chi2 single group -> nan")
truth(N.mcc([1.0, 1.0], [1.0, 1.0]) == 0.0, "mcc degenerate marginals -> 0.0 (sklearn)")

# bit-stability of transcendental-bearing recipes
truth(N.t_test_p([1.0, 2.0, 3.5], [2.0, 4.0, 4.5]) == N.t_test_p([1.0, 2.0, 3.5], [2.0, 4.0, 4.5]),
      "p_value bit-stable across calls")
nd = lambda: N.ndcg_at_k(["a", "a", "a"], [1.0, 2.0, 3.0], [3.0, 1.0, 2.0], 3, "exp")
truth(nd() == nd(), "ndcg bit-stable across calls")
truth(N.dlog(7.3) == N.dlog(7.3) and N.dexp(-3.2) == N.dexp(-3.2), "kernels bit-stable")

# ---------------- part D: pipeline e2e - string tags, cross-artifact binding, na drop ----------------

with tempfile.TemporaryDirectory() as td:
    def write_csv(name, header, rows):
        with open(os.path.join(td, name), "w", newline="") as fh:
            w = csv.writer(fh)
            w.writerow(header)
            w.writerows(rows)

    write_csv("timings.csv", ["before_ms", "after_ms"],
              [[100.0, 42.0], [110.0, 44.0], [105.0, 40.0], [98.0, 41.0]])
    write_csv("left.csv", ["id"], [[i] for i in range(120)])
    write_csv("merged.csv", ["id"], [[i] for i in range(117)])
    write_csv("ratings.csv", ["query", "rank", "relevance"],
              [["q1", 1, 1], ["q1", 2, 0], ["q1", 3, 1], ["q2", 1, 0], ["q2", 2, 1]])
    write_csv("ab.csv", ["control", "treatment"],
              [[10.1, 11.2], [10.4, 11.9], [9.8, 11.1], [10.0, 12.0], ["", 11.5]])
    contract = {
        "run": {"entrypoint": "MANUAL", "network": "off", "cwd": "."},
        "artifacts": [
            {"path": "timings.csv", "columns": {"before_ms": {"tag": "before", "na_policy": "error"},
                                                "after_ms": {"tag": "after", "na_policy": "error"}}},
            {"path": "merged.csv", "columns": {"id": {"tag": "joined_key", "na_policy": "error"}}},
            {"path": "left.csv", "columns": {"id": {"tag": "left_key", "na_policy": "error"}}},
            {"path": "ratings.csv", "columns": {"query": {"tag": "query", "na_policy": "error"},
                                                "rank": {"tag": "rank", "na_policy": "error"},
                                                "relevance": {"tag": "relevance", "na_policy": "error"}}},
            {"path": "ab.csv", "columns": {"control": {"tag": "sample_a", "na_policy": "drop"},
                                           "treatment": {"tag": "sample_b", "na_policy": "drop"}}},
        ],
        "metrics": [
            {"metric_id": "speedup_ratio", "artifact": "timings.csv",
             "binding": {"before": "before_ms", "after": "after_ms"}, "convention": "mean",
             "claimed_value": 2.47, "headline": True, "binding_status": "independently-bound",
             "claim_confirmed": True},
            {"metric_id": "join_row_loss", "artifact": "merged.csv",
             "binding": {"left_key": "left.csv::id", "joined_key": "id"}, "convention": None,
             "claimed_value": 0.0, "headline": True, "binding_status": "independently-bound",
             "claim_confirmed": True},
            {"metric_id": "recall_at_k", "artifact": "ratings.csv",
             "binding": {"query": "query", "rank": "rank", "relevance": "relevance"},
             "convention": "k=1", "claimed_value": 0.25, "headline": False,
             "binding_status": "independently-bound", "claim_confirmed": True},
            {"metric_id": "p_value", "artifact": "ab.csv",
             "binding": {"sample_a": "control", "sample_b": "treatment"}, "convention": "welch",
             "claimed_value": None, "headline": False, "binding_status": "independently-bound",
             "claim_confirmed": False},
        ],
        "baselines": [],
    }
    cpath = os.path.join(td, "verify.yaml")
    json.dump(contract, open(cpath, "w"))
    rec = RC.recompute_contract(cpath, td, k=2)
    by_id = {m["metric_id"]: m for m in rec["metrics"]}
    approx(by_id["speedup_ratio"]["value"], (100 + 110 + 105 + 98) / (42.0 + 44 + 40 + 41),
           1e-12, 0, "e2e speedup from csv")
    approx(by_id["join_row_loss"]["value"], 3.0, 0, 0, "e2e cross-artifact join_row_loss = 3 rows lost")
    approx(by_id["recall_at_k"]["value"], 0.25, 1e-12, 0, "e2e recall@1 with string query column")
    truth(not isnan(by_id["p_value"]["value"]) and 0.0 < by_id["p_value"]["value"] < 0.05,
          "e2e welch p on na_policy=drop unequal columns is finite and small")
    truth(all(m["k_spread"] == 0.0 for m in rec["metrics"]), "e2e deterministic: zero k-spread")
    diff = C.compare(rec, contract)
    verd = {m["metric_id"]: m["verdict"] for m in diff["metrics"]}
    truth(verd["speedup_ratio"] == "CONFIRMED",
          "e2e speedup 2.47 claim CONFIRMED within reported precision (got %s)" % verd["speedup_ratio"])
    truth(verd["join_row_loss"] == "REFUTED",
          "e2e 'merged without losing rows' vs 3 lost rows -> REFUTED (got %s)" % verd["join_row_loss"])
    truth(verd["recall_at_k"] == "CONFIRMED",
          "e2e recall@1 claim CONFIRMED (got %s)" % verd["recall_at_k"])
    truth(verd["p_value"] == "INCONCLUSIVE",
          "e2e numberless p_value claim -> INCONCLUSIVE (got %s)" % verd["p_value"])

# ---------------- part E: claim parsing regressions for the new metric families ----------------

for claim, want_v, want_hint in [
    ("f1 0.84", 0.84, "f1"), ("top-5 accuracy 0.91", 0.91, "top_k_accuracy"),
    ("recall@10 = 0.84", 0.84, "recall_at_k"), ("p95 latency 120ms", 120.0, "latency_p95"),
    ("chi2 = 5.99", 5.99, "chi_square"), ("pass@1 0.47", 0.47, "pass_at_k"),
    ("2.3x faster", 2.3, "speedup_ratio"), ("up 23% MoM", 0.23, "growth_rate"),
    ("ndcg@10 0.71", 0.71, "ndcg_at_k"), ("test coverage 87%", 0.87, "test_coverage"),
    ("average precision 0.62", 0.62, "pr_auc"), ("macro f1 0.55", 0.55, "macro_f1"),
    ("the lift was 12%", 0.12, "lift"), ("spearman correlation 0.8", 0.8, "correlation"),
    ("median 42", 42.0, "column_median"), ("12,402 distinct users", 12402.0, "distinct_count"),
    ("null fraction 0.02", 0.02, "null_fraction"), ("throughput 4,200 rps", 4200.0, "throughput"),
    ("p-value 0.003", 0.003, "p_value"), ("effect size 0.4", 0.4, "effect_size"),
]:
    v, hint = D.parse_claim(claim)
    truth(v == want_v and hint == want_hint,
          "claim %r -> (%r, %s) want (%r, %s)" % (claim, v, hint, want_v, want_hint))

# ---------------- part F: convention inference from claim text + percent-precision fix ----------------

for claim, mid, want_conv in [
    ("pass@5 0.62", "pass_at_k", "k=5"), ("recall@20 was 0.91", "recall_at_k", "k=20"),
    ("ndcg@5 0.7 with exp gains", "ndcg_at_k", "k=5,exp"), ("monthly CAGR 23.87%", "cagr", "periods=12"),
    ("NPV $310 at 8%", "npv", "rate=0.08"), ("spearman correlation 0.8", "correlation", "spearman"),
    ("99% confidence interval 0.4", "confidence_interval", "t99"), ("5xx error rate 0.3%", "error_rate", "http5xx"),
    ("92% retention", "churn_rate", "retention"), ("sMAPE 11%", "mape", "smape"),
    ("90th percentile 120", "percentile", "p90"), ("p99.9 latency 480ms", "percentile", "p99.9"),
    ("accuracy 0.87", "accuracy", None),
]:
    _, hint = D.parse_claim(claim)
    got = D.infer_convention(claim, mid)
    truth(hint == mid and got == want_conv,
          "convention %r -> (%s, %s) want (%s, %s)" % (claim, hint, got, mid, want_conv))

# percent-scaled claims must keep their REPORTED precision ('23.87%' -> 0.2387 +/- 5e-5,
# despite repr(23.87/100) carrying float artifacts)
truth(abs(C._infer_precision(23.87 / 100.0) - 5e-5) < 1e-18,
      "percent claim precision survives the /100 float artifact")
truth(C._infer_precision(0.42) == 0.005, "plain decimal precision unchanged")
truth(C._infer_precision(120.0) == 0.5, "integer claim precision unchanged")
truth(C._infer_precision(0.123456789012345) <= 5e-13, "genuinely long claims keep a tight budget")

# claim_precision: the suffix scale is part of the REPORTED precision ('$4.2M' is +/-50k, not +/-0.5)
truth(D.claim_precision("$4.2M revenue") == 50000.0, "claim_precision $4.2M -> 50k")
truth(abs(D.claim_precision("23.87%") - 5e-5) < 1e-18, "claim_precision 23.87%% -> 5e-5")
truth(D.claim_precision("processed 10,000 rows") == 0.5, "claim_precision integer -> 0.5")
truth(D.claim_precision("accuracy 0.87") == 0.005, "claim_precision 0.87 -> 0.005")
truth(D.claim_precision("no number here") is None, "claim_precision without a number -> None")

# ---------------- part G: audit fixes - tag aliases + degenerate (not crashed) bad bindings ----------------

with tempfile.TemporaryDirectory() as td2:
    with open(os.path.join(td2, "preds.csv"), "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["y_true", "y_pred", "prob"])
        for y, p, pr in [(1, 1, 0.9), (0, 0, 0.2), (1, 0, 0.4), (0, 0, 0.1)]:
            w.writerow([y, p, pr])
    # named metrics bind through aliases: log_loss needs `prob` (column tags as `score`),
    # rmse needs `target` (column y_true tags as `label`)
    c_ll = D.draft(td2, claim="log loss 0.3")
    truth(c_ll["metrics"] and c_ll["metrics"][0]["metric_id"] == "log_loss"
          and c_ll["metrics"][0]["binding"].get("prob") == "prob",
          "named log_loss claim binds the probability column via the score->prob alias")
    c_rmse = D.draft(td2, claim="rmse 0.5")
    truth(c_rmse["metrics"] and c_rmse["metrics"][0]["binding"].get("target") == "y_true",
          "named rmse claim binds y_true via the label->target alias")
    # auto-pick (no named metric) keeps the strict table: y_true/y_pred -> accuracy, never rmse
    c_auto = D.draft(td2, claim="0.75")
    truth(c_auto["metrics"] and c_auto["metrics"][0]["metric_id"] == "auc",
          "auto-pick unchanged by aliases (score+label -> auc), got %s"
          % (c_auto["metrics"][0]["metric_id"] if c_auto["metrics"] else None))

    # a contract binding a MISSING column degrades to a degenerate recompute, never a traceback
    bad = {"run": {"entrypoint": "MANUAL"}, "artifacts": [{"path": "preds.csv", "columns": {}}],
           "metrics": [{"metric_id": "accuracy", "artifact": "preds.csv",
                        "binding": {"prediction": "no_such_col", "label": "y_true"},
                        "convention": None, "claimed_value": 0.9, "headline": True,
                        "binding_status": "independently-bound", "claim_confirmed": True}],
           "baselines": []}
    bp = os.path.join(td2, "verify.yaml")
    json.dump(bad, open(bp, "w"))
    rec_bad = RC.recompute_contract(bp, td2)
    truth(rec_bad["metrics"][0]["degenerate"] and "binding failed" in rec_bad["metrics"][0]["error"],
          "missing column -> degenerate recompute with a named error")
    diff_bad = C.compare(rec_bad, bad)
    truth(diff_bad["metrics"][0]["verdict"] == "INCONCLUSIVE",
          "missing column -> INCONCLUSIVE, never a crash or a verdict")
    # a non-numeric cell in a numeric column likewise degrades
    with open(os.path.join(td2, "dirty.csv"), "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["value"])
        w.writerow([3.0])
        w.writerow(["oops-text"])
    dirty = {"run": {"entrypoint": "MANUAL"}, "artifacts": [{"path": "dirty.csv", "columns": {}}],
             "metrics": [{"metric_id": "column_sum", "artifact": "dirty.csv",
                          "binding": {"value": "value"}, "convention": None, "claimed_value": 3.0,
                          "headline": True, "binding_status": "independently-bound",
                          "claim_confirmed": True}], "baselines": []}
    dp = os.path.join(td2, "verify2.yaml")
    json.dump(dirty, open(dp, "w"))
    rec_dirty = RC.recompute_contract(dp, td2)
    truth(rec_dirty["metrics"][0]["degenerate"], "non-numeric cell -> degenerate, not a traceback")

# ---------------- part H: the site's recipe catalog stays in sync with the registry ----------------

_site_data = os.path.join(HERE, "..", "..", "..", "..", "..", "app", "recipes", "data.ts")
if os.path.exists(_site_data):
    import re as _re
    _ids = set(_re.findall(r'id:\s*"([a-z0-9_]+)"', open(_site_data).read()))
    truth(_ids == set(R.ids()),
          "app/recipes/data.ts mirrors the registry (site-only: %s; registry-only: %s)"
          % (sorted(_ids - set(R.ids())), sorted(set(R.ids()) - _ids)))

print("recipes-sota: %d checks, %d failures" % (_n, _fail))
sys.exit(1 if _fail else 0)
