"""SOTA validation of the full recipe library against published reference implementations.

assets/reference_vectors.json is generated by calibration/gen_reference_vectors.py from
scikit-learn / SciPy / NumPy (plus the HumanEval pass@k estimator and the Guo et al. ECE
definition). This suite re-runs every case through Calma's deterministic kernels and recipes -
pure stdlib here, per the repo rule - and then exercises the recipe layer: convention parsing,
degenerate paths, bit-stability, string-tag columns and cross-artifact bindings end-to-end.
Run: python3 test_recipes_sota.py
"""
import csv
import json
import math
import os
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, ".."))
import numeric as N  # noqa: E402
import recipes as R  # noqa: E402
import recompute as RC  # noqa: E402
import compare as C  # noqa: E402
import draft_contract as D  # noqa: E402

VECTORS = os.path.join(HERE, "..", "..", "assets", "reference_vectors.json")

_n = _fail = 0


def isnan(x):
    return isinstance(x, float) and x != x


def approx(got, want, atol, rtol, label):
    global _n, _fail
    _n += 1
    if not (abs(got - want) <= atol + rtol * abs(want)):
        _fail += 1
        print("  FAIL [%s] got %r want %r (atol %g rtol %g)" % (label, got, want, atol, rtol))


def truth(cond, label):
    global _n, _fail
    _n += 1
    if not cond:
        _fail += 1
        print("  FAIL [%s]" % label)


# ---------------- part A: every reference vector ----------------

KINDS = {
    "total_return": lambda a: N.total_return(a["rets"]),
    "sharpe": lambda a: N.sharpe(a["rets"], a["periods"])[0],
    "max_drawdown": lambda a: N.max_drawdown(a["rets"]),
    "rmse": lambda a: N.rmse(a["pred"], a["actual"]),
    "mae": lambda a: N.mae(a["pred"], a["actual"]),
    "r2": lambda a: N.r2(a["pred"], a["actual"]),
    "accuracy": lambda a: N.accuracy(a["preds"], a["labels"]),
    "precision": lambda a: N.precision(a["preds"], a["labels"]),
    "recall": lambda a: N.recall(a["preds"], a["labels"]),
    "f1": lambda a: N.f1(a["preds"], a["labels"]),
    "auc": lambda a: N.auc(a["scores"], a["labels"]),
    "brier": lambda a: N.brier(a["probs"], a["labels"]),
    "column_sum": lambda a: N.col_sum(a["xs"]),
    "column_mean": lambda a: N.col_mean(a["xs"]),
    "quantile": lambda a: N.quantile(a["xs"], a["q"]),
    "speedup": lambda a: N.speedup_ratio(a["before"], a["after"], a["mode"]),
    "throughput": lambda a: N.throughput(a["durs"]),
    "peak": lambda a: N.peak(a["xs"]),
    "coverage": lambda a: N.coverage_fraction(a["hits"]),
    "error_rate": lambda a: N.error_rate(a["flags"], a["mode"]),
    "null_fraction": lambda a: N.null_fraction(a["raw"]),
    "distinct_count": lambda a: N.distinct_count(a["raw"], a["include_null"]),
    "duplicate_count": lambda a: N.duplicate_count(a["raw"]),
    "growth_rate": lambda a: N.growth_rate(a["xs"], a["mode"]),
    "ratio_share": lambda a: N.ratio_share(a["flags"]),
    "groupby": lambda a: N.groupby_aggregate(a["groups"], a["values"], a["agg"], a["label"])[0],
    "recall_at_k": lambda a: N.recall_at_k(a["queries"], a["ranks"], a["rels"], a["k"]),
    "ndcg_at_k": lambda a: N.ndcg_at_k(a["queries"], a["ranks"], a["rels"], a["k"], a["gain"]),
    "mrr": lambda a: N.mrr(a["queries"], a["ranks"], a["rels"], a["k"]),
    "hit_at_k": lambda a: N.hit_at_k(a["queries"], a["ranks"], a["rels"], a["k"]),
    "pass_at_k": lambda a: N.pass_at_k(a["problems"], a["corrects"], a["k"]),
    "macro_f1": lambda a: N.macro_f1(a["preds"], a["labels"]),
    "micro_f1": lambda a: N.micro_f1(a["preds"], a["labels"]),
    "mcc": lambda a: N.mcc(a["preds"], a["labels"]),
    "average_precision": lambda a: N.average_precision(a["scores"], a["labels"]),
    "log_loss": lambda a: N.log_loss(a["probs"], a["labels"], a["clip"]),
    "ece": lambda a: N.ece(a["probs"], a["labels"], a["bins"]),
    "t_test_p": lambda a: N.t_test_p(a["a"], a["b"], a["mode"]),
    "ci_half_width": lambda a: N.ci_half_width(a["xs"], a["level"], a["dist"]),
    "lift": lambda a: N.lift(a["a"], a["b"], a["mode"]),
    "chi_square": lambda a: N.chi_square(a["groups"], a["outcomes"], a["yates"], a["output"]),
    "correlation": lambda a: (N.spearman_r(a["xs"], a["ys"]) if a["mode"] == "spearman"
                              else N.pearson_r(a["xs"], a["ys"])),
    "cohen_d": lambda a: N.cohen_d(a["a"], a["b"], a["mode"]),
    "cagr": lambda a: N.cagr(a["xs"], a["ppy"]),
    "npv": lambda a: N.npv(a["cashflows"], a["rate"]),
    "irr": lambda a: N.irr(a["cashflows"]),
    "churn_rate": lambda a: N.churn_rate(a["flags"], a["mode"]),
    "margin_pct": lambda a: N.margin_pct(a["revenue"], a["cost"]),
    "reconciliation": lambda a: N.reconciliation_diff(a["a"], a["b"]),
    "mape": lambda a: N.mape(a["pred"], a["actual"], a["symmetric"]),
    "mase": lambda a: N.mase(a["pred"], a["actual"], a["m"]),
    "pinball": lambda a: N.pinball(a["pred"], a["actual"], a["q"]),
    "volatility": lambda a: N.volatility(a["rets"], a["periods"]),
    "downside_deviation": lambda a: N.downside_deviation(a["rets"], a["periods"]),
    "sortino": lambda a: N.sortino(a["rets"], a["periods"]),
    "calmar": lambda a: N.calmar(a["rets"], a["periods"]),
    "value_at_risk": lambda a: N.value_at_risk(a["rets"], a["level"]),
    "cvar": lambda a: N.cvar(a["rets"], a["level"]),
    "win_rate": lambda a: N.win_rate(a["rets"]),
    "profit_factor": lambda a: N.profit_factor(a["rets"]),
    "omega_ratio": lambda a: N.omega_ratio(a["rets"], a["threshold"]),
    "beta": lambda a: N.beta(a["rets"], a["bench"]),
    "alpha": lambda a: N.alpha(a["rets"], a["bench"], a["periods"]),
    "tracking_error": lambda a: N.tracking_error(a["rets"], a["bench"], a["periods"]),
    "information_ratio": lambda a: N.information_ratio(a["rets"], a["bench"], a["periods"]),
    "balanced_accuracy": lambda a: N.balanced_accuracy(a["preds"], a["labels"]),
    "cohen_kappa": lambda a: N.cohen_kappa(a["preds"], a["labels"]),
    "specificity": lambda a: N.specificity(a["preds"], a["labels"]),
    "fbeta": lambda a: N.fbeta(a["preds"], a["labels"], a["beta"]),
    "jaccard": lambda a: N.jaccard(a["preds"], a["labels"]),
    "weighted_f1": lambda a: N.weighted_f1(a["preds"], a["labels"]),
    "ks_statistic": lambda a: N.ks_statistic(a["scores"], a["labels"]),
    "gini_norm": lambda a: N.gini_norm(a["scores"], a["labels"]),
    "msle": lambda a: N.msle(a["pred"], a["actual"], a["root"]),
    "medae": lambda a: N.medae(a["pred"], a["actual"]),
    "max_error": lambda a: N.max_error(a["pred"], a["actual"]),
    "explained_variance": lambda a: N.explained_variance(a["pred"], a["actual"]),
    "wape": lambda a: N.wape(a["pred"], a["actual"]),
    "forecast_bias": lambda a: N.forecast_bias(a["pred"], a["actual"]),
    "adjusted_r2": lambda a: N.adjusted_r2(a["pred"], a["actual"], a["p"]),
    "nrmse": lambda a: N.nrmse(a["pred"], a["actual"], a["mode"]),
    "durbin_watson": lambda a: N.durbin_watson(a["pred"], a["actual"]),
    "column_min": lambda a: N.col_min(a["xs"]),
    "column_max": lambda a: N.col_max(a["xs"]),
    "column_std": lambda a: N.col_std(a["xs"], a["ddof"]),
    "iqr": lambda a: N.iqr(a["xs"]),
    "outlier_count": lambda a: N.outlier_count(a["xs"], a["k"]),
    "mode_share": lambda a: N.mode_share(a["raw"]),
    "gini_coefficient": lambda a: N.gini_coefficient(a["xs"]),
    "hhi": lambda a: N.hhi(a["xs"]),
    "entropy": lambda a: N.cat_entropy(a["raw"], a["base"]),
    "apdex": lambda a: N.apdex(a["durs"], a["t"]),
    "mann_whitney_p": lambda a: N.mann_whitney_p(a["a"], a["b"]),
    "ks_p": lambda a: N.ks_p(a["a"], a["b"]),
    "anova": lambda a: N.anova_p(a["groups"], a["values"], a["output"]),
    "proportion_z_p": lambda a: N.proportion_z_p(a["a"], a["b"]),
    "fisher_exact_p": lambda a: N.fisher_exact_p(a["groups"], a["outcomes"]),
    "odds_ratio_2x2": lambda a: N.odds_ratio_2x2(a["groups"], a["outcomes"], a["haldane"]),
    "relative_risk_2x2": lambda a: N.relative_risk_2x2(a["groups"], a["outcomes"]),
    "cramers_v": lambda a: N.cramers_v(a["groups"], a["outcomes"]),
    "skewness": lambda a: N.skewness(a["xs"]),
    "kurtosis": lambda a: N.kurtosis_excess(a["xs"]),
    "jarque_bera": lambda a: N.jarque_bera_p(a["xs"], a["output"]),
    "autocorrelation": lambda a: N.autocorrelation(a["xs"], a["lag"]),
    "precision_at_k": lambda a: N.precision_at_k(a["queries"], a["ranks"], a["rels"], a["k"]),
    "map_at_k": lambda a: N.map_at_k(a["queries"], a["ranks"], a["rels"], a["k"]),
    "perplexity": lambda a: N.perplexity(a["logprobs"]),
    "wer": lambda a: N.wer(a["preds"], a["refs"], a["char_level"]),
    "dlog": lambda a: N.dlog(a["x"]),
    "dexp": lambda a: N.dexp(a["x"]),
    "dlgamma": lambda a: N.dlgamma(a["z"]),
    "betainc": lambda a: N.betainc_reg(a["a"], a["b"], a["x"]),
    "gammaincc": lambda a: N.gammainc_upper_reg(a["s"], a["x"]),
    "erfc": lambda a: N.derfc(a["x"]),
    "t_sf2": lambda a: N.t_sf_two_sided(a["t"], a["df"]),
    "chi2_sf": lambda a: N.chi2_sf(a["x"], a["df"]),
    "t_ppf2": lambda a: N.t_ppf_two_sided(a["alpha"], a["df"]),
    "z_ppf2": lambda a: N.z_ppf_two_sided(a["alpha"]),
    # pack QR - quant-risk depth
    "ulcer_index": lambda a: N.ulcer_index(a["rets"]),
    "pain_index": lambda a: N.pain_index(a["rets"]),
    "martin_ratio": lambda a: N.martin_ratio(a["rets"], a["periods"]),
    "recovery_factor": lambda a: N.recovery_factor(a["rets"]),
    "gain_to_pain_ratio": lambda a: N.gain_to_pain_ratio(a["rets"]),
    "tail_ratio": lambda a: N.tail_ratio(a["rets"]),
    "gain_loss_ratio": lambda a: N.gain_loss_ratio(a["rets"]),
    "win_loss_ratio": lambda a: N.win_loss_ratio(a["rets"]),
    "kelly_criterion": lambda a: N.kelly_criterion(a["rets"]),
    "upside_deviation": lambda a: N.upside_deviation(a["rets"], a["periods"]),
    "upside_potential_ratio": lambda a: N.upside_potential_ratio(a["rets"]),
    "kappa_three": lambda a: N.kappa_three(a["rets"]),
    "cdar": lambda a: N.cdar(a["rets"], a["level"]),
    "max_drawdown_duration": lambda a: N.max_drawdown_duration(a["rets"]),
    "parametric_var": lambda a: N.parametric_var(a["rets"], a["level"]),
    "parametric_es": lambda a: N.parametric_es(a["rets"], a["level"]),
    "cornish_fisher_var": lambda a: N.cornish_fisher_var(a["rets"], a["level"]),
    "adjusted_sharpe_ratio": lambda a: N.adjusted_sharpe_ratio(a["rets"]),
    "probabilistic_sharpe_ratio": lambda a: N.probabilistic_sharpe_ratio(a["rets"], a["benchmark_sr"]),
    "up_capture_ratio": lambda a: N.up_capture_ratio(a["rets"], a["bench"]),
    "down_capture_ratio": lambda a: N.down_capture_ratio(a["rets"], a["bench"]),
    "capture_ratio": lambda a: N.capture_ratio(a["rets"], a["bench"]),
    "treynor_ratio": lambda a: N.treynor_ratio(a["rets"], a["bench"], a["periods"]),
    "r_squared": lambda a: N.r_squared(a["rets"], a["bench"]),
    "active_return": lambda a: N.active_return(a["rets"], a["bench"], a["periods"]),
    # pack ST - statistics & hypothesis tests
    "point_biserial": lambda a: N.point_biserial(a["binary"], a["value"]),
    "kendall_tau": lambda a: N.kendall_tau(a["xs"], a["ys"]),
    "theil_sen_slope": lambda a: N.theil_sen_slope(a["xs"], a["ys"]),
    "cliffs_delta": lambda a: N.cliffs_delta(a["a"], a["b"]),
    "rank_biserial": lambda a: N.rank_biserial(a["a"], a["b"]),
    "eta_squared": lambda a: N.eta_squared(a["groups"], a["values"]),
    "g_test": lambda a: N.g_test(a["groups"], a["outcomes"], a["output"]),
    "mcnemar": lambda a: N.mcnemar_p(a["a"], a["b"]),
    # pack ST2
    "levene": lambda a: N.levene(a["groups"], a["values"]),
    "bartlett": lambda a: N.bartlett(a["groups"], a["values"]),
    "fligner": lambda a: N.fligner(a["groups"], a["values"]),
    "kruskal_wallis": lambda a: N.kruskal_wallis(a["groups"], a["values"]),
    "wilcoxon_signed_rank": lambda a: N.wilcoxon_signed_rank(a["a"], a["b"]),
    "anderson_darling": lambda a: N.anderson_darling(a["xs"]),
    "wilson_lower": lambda a: N.wilson_lower(a["flags"], a["level"]),
    "wilson_upper": lambda a: N.wilson_upper(a["flags"], a["level"]),
    "bh_rejections": lambda a: N.bh_rejections(a["pvals"], a["alpha"]),
    "holm_rejections": lambda a: N.holm_rejections(a["pvals"], a["alpha"]),
    # pack RM - risk-model validation
    "kupiec_pof": lambda a: N.kupiec_pof(a["flags"], a["p0"], "p"),
    "christoffersen_independence": lambda a: N.christoffersen_independence(a["flags"], "p"),
    "christoffersen_cc": lambda a: N.christoffersen_cc(a["flags"], a["p0"], "p"),
    "psi": lambda a: N.psi(a["expected"], a["actual"]),
    "information_value": lambda a: N.information_value(a["groups"], a["labels"]),
    "kl_divergence": lambda a: N.kl_divergence(a["p"], a["q"]),
    "js_divergence": lambda a: N.js_divergence(a["p"], a["q"]),
    "wasserstein_1d": lambda a: N.wasserstein_1d(a["a"], a["b"]),
    "energy_distance": lambda a: N.energy_distance(a["a"], a["b"]),
    "ks_2samp": lambda a: N.ks_2samp(a["a"], a["b"]),
    # pack CR - classification & regression depth
    "g_mean": lambda a: N.g_mean(a["pred"], a["label"]),
    "youden_j": lambda a: N.youden_j(a["pred"], a["label"]),
    "markedness": lambda a: N.markedness(a["pred"], a["label"]),
    "negative_predictive_value": lambda a: N.negative_predictive_value(a["pred"], a["label"]),
    "false_positive_rate": lambda a: N.false_positive_rate(a["pred"], a["label"]),
    "false_negative_rate": lambda a: N.false_negative_rate(a["pred"], a["label"]),
    "false_discovery_rate": lambda a: N.false_discovery_rate(a["pred"], a["label"]),
    "positive_likelihood_ratio": lambda a: N.positive_likelihood_ratio(a["pred"], a["label"]),
    "negative_likelihood_ratio": lambda a: N.negative_likelihood_ratio(a["pred"], a["label"]),
    "diagnostic_odds_ratio": lambda a: N.diagnostic_odds_ratio(a["pred"], a["label"]),
    "threat_score": lambda a: N.threat_score(a["pred"], a["label"]),
    "fowlkes_mallows": lambda a: N.fowlkes_mallows(a["pred"], a["label"]),
    "concordance_correlation": lambda a: N.concordance_correlation(a["pred"], a["actual"]),
    "huber_loss": lambda a: N.huber_loss(a["pred"], a["actual"], a["delta"]),
    "poisson_deviance": lambda a: N.poisson_deviance(a["pred"], a["actual"]),
    "gamma_deviance": lambda a: N.gamma_deviance(a["pred"], a["actual"]),
    "d2_absolute_error": lambda a: N.d2_absolute_error(a["pred"], a["actual"]),
    # pack AN - analytics / data-quality / robust-stats
    "variance": lambda a: N.variance(a["xs"]),
    "range_value": lambda a: N.range_value(a["xs"]),
    "mean_abs_deviation": lambda a: N.mean_abs_deviation(a["xs"]),
    "median_abs_deviation": lambda a: N.median_abs_deviation(a["xs"]),
    "trimmed_mean": lambda a: N.trimmed_mean(a["xs"], a["proportion"]),
    "geometric_mean": lambda a: N.geometric_mean(a["xs"]),
    "harmonic_mean": lambda a: N.harmonic_mean(a["xs"]),
    "weighted_mean": lambda a: N.weighted_mean(a["values"], a["weights"]),
    "covariance": lambda a: N.covariance(a["xs"], a["ys"]),
    "theil_index": lambda a: N.theil_index(a["xs"]),
    "atkinson_index": lambda a: N.atkinson_index(a["xs"]),
    "quartile_coefficient_dispersion": lambda a: N.quartile_coefficient_dispersion(a["xs"]),
    "index_of_dispersion": lambda a: N.index_of_dispersion(a["xs"]),
    "uniqueness_ratio": lambda a: N.uniqueness_ratio(a["raw"]),
    "ljung_box": lambda a: N.ljung_box(a["xs"], a["lags"]),
    # pack TS - forecasting / time-series accuracy
    "theil_u1": lambda a: N.theil_u1(a["pred"], a["actual"]),
    "theil_u2": lambda a: N.theil_u2(a["pred"], a["actual"]),
    "rmsse": lambda a: N.rmsse(a["pred"], a["actual"]),
    "tracking_signal": lambda a: N.tracking_signal(a["pred"], a["actual"]),
    "mean_directional_accuracy": lambda a: N.mean_directional_accuracy(a["pred"], a["actual"]),
    "relative_absolute_error": lambda a: N.relative_absolute_error(a["pred"], a["actual"]),
    "relative_squared_error": lambda a: N.relative_squared_error(a["pred"], a["actual"]),
    "mean_percentage_error": lambda a: N.mean_percentage_error(a["pred"], a["actual"]),
    "median_absolute_percentage_error": lambda a: N.median_absolute_percentage_error(a["pred"], a["actual"]),
    # pack FAIR - fairness / bias
    "demographic_parity_difference": lambda a: N.demographic_parity_difference(a["pred"], a["label"], a["group"]),
    "demographic_parity_ratio": lambda a: N.demographic_parity_ratio(a["pred"], a["label"], a["group"]),
    "equalized_odds_difference": lambda a: N.equalized_odds_difference(a["pred"], a["label"], a["group"]),
    "equalized_odds_ratio": lambda a: N.equalized_odds_ratio(a["pred"], a["label"], a["group"]),
    "equal_opportunity_difference": lambda a: N.equal_opportunity_difference(a["pred"], a["label"], a["group"]),
    "predictive_parity_difference": lambda a: N.predictive_parity_difference(a["pred"], a["label"], a["group"]),
    "fpr_parity_difference": lambda a: N.fpr_parity_difference(a["pred"], a["label"], a["group"]),
    "accuracy_parity_difference": lambda a: N.accuracy_parity_difference(a["pred"], a["label"], a["group"]),
    # pack BC - survival concordance + clustering agreement
    "concordance_index": lambda a: N.concordance_index(a["time"], a["score"], a["event"]),
    "mutual_info_score": lambda a: N.mutual_info_score(a["a"], a["b"]),
    "normalized_mutual_info": lambda a: N.normalized_mutual_info(a["a"], a["b"]),
    "homogeneity_score": lambda a: N.homogeneity_score(a["a"], a["b"]),
    "completeness_score": lambda a: N.completeness_score(a["a"], a["b"]),
    "v_measure_score": lambda a: N.v_measure_score(a["a"], a["b"]),
    "rand_index": lambda a: N.rand_index(a["a"], a["b"]),
    "adjusted_rand_index": lambda a: N.adjusted_rand_index(a["a"], a["b"]),
    "fowlkes_mallows_clustering": lambda a: N.fowlkes_mallows_clustering(a["a"], a["b"]),
    # pack ENG - performance / SRE depth
    "latency_p75": lambda a: N.latency_p75(a["durations"]),
    "latency_p999": lambda a: N.latency_p999(a["durations"]),
    "tail_latency_ratio": lambda a: N.tail_latency_ratio(a["durations"]),
    "latency_stddev": lambda a: N.latency_stddev(a["durations"]),
    "jitter": lambda a: N.jitter(a["durations"]),
    "slo_attainment": lambda a: N.slo_attainment(a["durations"], a["threshold"]),
    "error_budget_burn": lambda a: N.error_budget_burn(a["flags"], a["target"]),
    "compression_ratio": lambda a: N.compression_ratio(a["original"], a["compressed"]),
    "availability": lambda a: N.availability(a["uptime"], a["downtime"]),
    "mtbf": lambda a: N.mtbf(a["flags"]),
    # pack QR2 - quant performance depth
    "pain_ratio": lambda a: N.pain_ratio(a["rets"], a["periods"]),
    "sterling_ratio": lambda a: N.sterling_ratio(a["rets"], a["periods"]),
    "burke_ratio": lambda a: N.burke_ratio(a["rets"], a["periods"]),
    "m2_measure": lambda a: N.m2_measure(a["rets"], a["bench"]),
    "appraisal_ratio": lambda a: N.appraisal_ratio(a["rets"], a["bench"]),
    "common_sense_ratio": lambda a: N.common_sense_ratio(a["rets"]),
    "rachev_ratio": lambda a: N.rachev_ratio(a["rets"], a["level"]),
    "downside_potential": lambda a: N.downside_potential(a["rets"]),
    "upside_potential": lambda a: N.upside_potential(a["rets"]),
    "omega_sharpe_ratio": lambda a: N.omega_sharpe_ratio(a["rets"], a["threshold"]),
    # pack EXP - causal / experimentation
    "average_treatment_effect": lambda a: N.average_treatment_effect(a["treatment"], a["control"]),
    "risk_difference": lambda a: N.risk_difference(a["treatment"], a["control"]),
    "relative_risk_reduction": lambda a: N.relative_risk_reduction(a["treatment"], a["control"]),
    "number_needed_to_treat": lambda a: N.number_needed_to_treat(a["treatment"], a["control"]),
    "standardized_mean_difference": lambda a: N.standardized_mean_difference(a["treatment"], a["control"]),
    "cuped_ate": lambda a: N.cuped_ate(a["value"], a["covariate"], a["group"]),
    "variance_reduction_cuped": lambda a: N.variance_reduction_cuped(a["value"], a["covariate"]),
    "srm_pvalue": lambda a: N.srm_pvalue(a["group"]),
    # pack IR - retrieval / ranking + token-overlap
    "r_precision": lambda a: N.r_precision(a["queries"], a["ranks"], a["rels"]),
    "mean_average_precision": lambda a: N.mean_average_precision(a["queries"], a["ranks"], a["rels"]),
    "f1_at_k": lambda a: N.f1_at_k(a["queries"], a["ranks"], a["rels"], a["k"]),
    "fallout_at_k": lambda a: N.fallout_at_k(a["queries"], a["ranks"], a["rels"], a["k"]),
    "rbp": lambda a: N.rbp(a["queries"], a["ranks"], a["rels"], a["p"]),
    "token_f1": lambda a: N.token_f1(a["preds"], a["refs"]),
    "token_jaccard": lambda a: N.token_jaccard(a["preds"], a["refs"]),
    "token_dice": lambda a: N.token_dice(a["preds"], a["refs"]),
    # pack FI - fixed income
    "bond_price": lambda a: N.bond_price(a["cashflow"], a["time"], a["ytm"]),
    "macaulay_duration": lambda a: N.macaulay_duration(a["cashflow"], a["time"], a["ytm"]),
    "modified_duration": lambda a: N.modified_duration(a["cashflow"], a["time"], a["ytm"]),
    "convexity": lambda a: N.convexity(a["cashflow"], a["time"], a["ytm"]),
    "dv01": lambda a: N.dv01(a["cashflow"], a["time"], a["ytm"]),
    "weighted_average_life": lambda a: N.weighted_average_life(a["cashflow"], a["time"]),
    "yield_to_maturity": lambda a: N.yield_to_maturity(a["cashflow"], a["time"], a["price"]),
    # pack OPT - Black-Scholes options & Greeks
    "bs_value": lambda a: N.bs_value(a["S"], a["K"], a["T"], a["sigma"], a["r"], a["qty"], a["is_call"]),
    "bs_delta": lambda a: N.bs_delta(a["S"], a["K"], a["T"], a["sigma"], a["r"], a["qty"], a["is_call"]),
    "bs_gamma": lambda a: N.bs_gamma(a["S"], a["K"], a["T"], a["sigma"], a["r"], a["qty"], a["is_call"]),
    "bs_vega": lambda a: N.bs_vega(a["S"], a["K"], a["T"], a["sigma"], a["r"], a["qty"], a["is_call"]),
    "bs_theta": lambda a: N.bs_theta(a["S"], a["K"], a["T"], a["sigma"], a["r"], a["qty"], a["is_call"]),
    "bs_rho": lambda a: N.bs_rho(a["S"], a["K"], a["T"], a["sigma"], a["r"], a["qty"], a["is_call"]),
    "bs_vanna": lambda a: N.bs_vanna(a["S"], a["K"], a["T"], a["sigma"], a["r"], a["qty"], a["is_call"]),
    "bs_volga": lambda a: N.bs_volga(a["S"], a["K"], a["T"], a["sigma"], a["r"], a["qty"], a["is_call"]),
    "bs_implied_vol": lambda a: N.bs_implied_vol(a["S"], a["K"], a["T"], a["r"], a["price"], a["is_call"]),
    # pack ES - expected-shortfall / VaR backtesting
    "var_breach_rate": lambda a: N.var_breach_rate(a["rets"], a["var"]),
    "realized_shortfall": lambda a: N.realized_shortfall(a["rets"], a["var"]),
    "expected_exceedance": lambda a: N.expected_exceedance(a["rets"], a["var"]),
    "basel_traffic_light": lambda a: N.basel_traffic_light(a["rets"], a["var"]),
    "es_backtest_ratio": lambda a: N.es_backtest_ratio(a["rets"], a["var"], a["es"]),
    "acerbi_szekely_z1": lambda a: N.acerbi_szekely_z1(a["rets"], a["var"], a["es"], a["level"]),
    "acerbi_szekely_z2": lambda a: N.acerbi_szekely_z2(a["rets"], a["var"], a["es"], a["level"]),
    # pack CR - credit / default risk
    "expected_loss": lambda a: N.expected_loss(a["pd"], a["lgd"], a["ead"]),
    "expected_loss_rate": lambda a: N.expected_loss_rate(a["pd"], a["lgd"], a["ead"]),
    "weighted_lgd": lambda a: N.weighted_lgd(a["lgd"], a["ead"]),
    "unexpected_loss": lambda a: N.unexpected_loss(a["pd"], a["lgd"], a["ead"]),
    "altman_z": lambda a: N.altman_z(a["x1"], a["x2"], a["x3"], a["x4"], a["x5"]),
    "altman_z_prime": lambda a: N.altman_z_prime(a["x1"], a["x2"], a["x3"], a["x4"]),
    "merton_distance_to_default": lambda a: N.merton_distance_to_default(a["v"], a["d"], a["mu"], a["sigma"], a["t"]),
    "merton_pd": lambda a: N.merton_pd(a["v"], a["d"], a["mu"], a["sigma"], a["t"]),
    # pack PA - portfolio construction & attribution
    "brinson_allocation": lambda a: N.brinson_allocation(a["wp"], a["wb"], a["rb"]),
    "brinson_selection": lambda a: N.brinson_selection(a["wb"], a["rp"], a["rb"]),
    "brinson_interaction": lambda a: N.brinson_interaction(a["wp"], a["wb"], a["rp"], a["rb"]),
    "brinson_total_active": lambda a: N.brinson_total_active(a["wp"], a["wb"], a["rp"], a["rb"]),
    "active_share": lambda a: N.active_share(a["wp"], a["wb"]),
    "portfolio_turnover": lambda a: N.portfolio_turnover(a["wprev"], a["wcurr"]),
    "effective_number_of_bets": lambda a: N.effective_number_of_bets(a["weight"]),
    # pack RC - rates / curve analytics
    "par_yield": lambda a: N.par_yield(a["zero"], a["time"]),
    "annuity_factor": lambda a: N.annuity_factor(a["zero"], a["time"]),
    "forward_rate": lambda a: N.forward_rate(a["zero"], a["time"]),
    "curve_pv": lambda a: N.curve_pv(a["cashflow"], a["zero"], a["time"]),
    "effective_duration": lambda a: N.effective_duration(a["cashflow"], a["time"], a["ytm"]),
    "effective_convexity": lambda a: N.effective_convexity(a["cashflow"], a["time"], a["ytm"]),
    # pack FM - fund / LP economics
    "dpi": lambda a: N.dpi(a["contribution"], a["distribution"]),
    "rvpi": lambda a: N.rvpi(a["contribution"], a["nav"]),
    "tvpi": lambda a: N.tvpi(a["contribution"], a["distribution"], a["nav"]),
    "called_pct": lambda a: N.called_pct(a["contribution"], a["committed"]),
    "carried_interest": lambda a: N.carried_interest(a["contribution"], a["distribution"], a["carry"]),
    "realization_ratio": lambda a: N.realization_ratio(a["distribution"], a["nav"]),
    # pack LQ - liquidity / microstructure
    "amihud_illiquidity": lambda a: N.amihud_illiquidity(a["ret"], a["dvol"]),
    "amivest_liquidity": lambda a: N.amivest_liquidity(a["ret"], a["dvol"]),
    "roll_spread": lambda a: N.roll_spread(a["price"]),
    "kyle_lambda": lambda a: N.kyle_lambda(a["dp"], a["q"]),
    "vwap": lambda a: N.vwap(a["price"], a["volume"]),
    "relative_spread": lambda a: N.relative_spread(a["bid"], a["ask"]),
    # pack AB - multiple-testing corrections
    "bonferroni_rejections": lambda a: N.bonferroni_rejections(a["pvals"], a["alpha"]),
    "sidak_rejections": lambda a: N.sidak_rejections(a["pvals"], a["alpha"]),
    "holm_sidak_rejections": lambda a: N.holm_sidak_rejections(a["pvals"], a["alpha"]),
    "hochberg_rejections": lambda a: N.hochberg_rejections(a["pvals"], a["alpha"]),
    "benjamini_yekutieli": lambda a: N.benjamini_yekutieli(a["pvals"], a["alpha"]),
    # pack TS - time-series / return diagnostics
    "variance_ratio": lambda a: N.variance_ratio(a["rets"], a["q"]),
    "runs_test": lambda a: N.runs_test(a["xs"]),
    "arch_lm": lambda a: N.arch_lm(a["xs"]),
    # pack OPS - exposure, leverage & ODD metrics
    "gross_exposure": lambda a: N.gross_exposure(a["exposure"]),
    "net_exposure": lambda a: N.net_exposure(a["exposure"]),
    "long_exposure": lambda a: N.long_exposure(a["exposure"]),
    "short_exposure": lambda a: N.short_exposure(a["exposure"]),
    "long_short_ratio": lambda a: N.long_short_ratio(a["exposure"]),
    "largest_position": lambda a: N.largest_position(a["exposure"]),
    "liquidity_coverage": lambda a: N.liquidity_coverage(a["weight"], a["days"], a["threshold"]),
    # pack FX - single-factor market-model risk
    "idiosyncratic_volatility": lambda a: N.idiosyncratic_volatility(a["ret"], a["bench"]),
    "alpha_tstat": lambda a: N.alpha_tstat(a["ret"], a["bench"]),
    "beta_tstat": lambda a: N.beta_tstat(a["ret"], a["bench"]),
    "bull_beta": lambda a: N.bull_beta(a["ret"], a["bench"]),
    "bear_beta": lambda a: N.bear_beta(a["ret"], a["bench"]),
    "up_down_beta_ratio": lambda a: N.up_down_beta_ratio(a["ret"], a["bench"]),
    # pack AR - credit-quality / covenant ratios
    "current_ratio": lambda a: N.current_ratio(a["ca"], a["cl"]),
    "quick_ratio": lambda a: N.quick_ratio(a["ca"], a["inv"], a["cl"]),
    "interest_coverage": lambda a: N.interest_coverage(a["ebit"], a["interest"]),
    "debt_to_equity": lambda a: N.debt_to_equity(a["debt"], a["equity"]),
    "debt_to_ebitda": lambda a: N.debt_to_ebitda(a["debt"], a["ebitda"]),
    "net_debt_to_ebitda": lambda a: N.net_debt_to_ebitda(a["debt"], a["cash"], a["ebitda"]),
    "ebitda_margin": lambda a: N.ebitda_margin(a["ebitda"], a["revenue"]),
    # pack CAL - probability-calibration depth
    "maximum_calibration_error": lambda a: N.maximum_calibration_error(a["probs"], a["labels"], a["bins"]),
    "brier_reliability": lambda a: N.brier_reliability(a["probs"], a["labels"], a["bins"]),
    "brier_resolution": lambda a: N.brier_resolution(a["probs"], a["labels"], a["bins"]),
    "brier_skill_score": lambda a: N.brier_skill_score(a["probs"], a["labels"]),
    "calibration_in_the_large": lambda a: N.calibration_in_the_large(a["probs"], a["labels"]),
    "spiegelhalter_z": lambda a: N.spiegelhalter_z(a["probs"], a["labels"]),
    "sharpness": lambda a: N.sharpness(a["probs"]),
    # pack DIST - distribution-distance depth
    "hellinger_distance": lambda a: N.hellinger_distance(a["p"], a["q"]),
    "total_variation_distance": lambda a: N.total_variation_distance(a["p"], a["q"]),
    "bhattacharyya_distance": lambda a: N.bhattacharyya_distance(a["p"], a["q"]),
    "jeffreys_divergence": lambda a: N.jeffreys_divergence(a["p"], a["q"]),
    "chi_square_distance": lambda a: N.chi_square_distance(a["p"], a["q"]),
    # pack SV - survival / time-to-event
    "km_median_survival": lambda a: N.km_median_survival(a["dur"], a["ev"]),
    "km_survival_at": lambda a: N.km_survival_at(a["dur"], a["ev"], a["t"]),
    "nelson_aalen_cumhaz": lambda a: N.nelson_aalen_cumhaz(a["dur"], a["ev"], a["t"]),
    "restricted_mean_survival_time": lambda a: N.restricted_mean_survival_time(a["dur"], a["ev"], a["horizon"]),
    # pack TX - transaction-cost analysis
    "implementation_shortfall": lambda a: N.implementation_shortfall(a["exec"], a["bench"], a["qty"], a["side"]),
    "arrival_slippage": lambda a: N.arrival_slippage(a["exec"], a["bench"], a["qty"], a["side"]),
    "vwap_slippage": lambda a: N.vwap_slippage(a["exec"], a["bench"], a["qty"], a["side"]),
    "effective_spread_bps": lambda a: N.effective_spread_bps(a["exec"], a["bench"], a["qty"], a["side"]),
    "participation_rate": lambda a: N.participation_rate(a["order"], a["market"]),
    # pack PME - private-market benchmarking
    "ks_pme": lambda a: N.ks_pme(a["c"], a["d"], a["index"], a["nav"]),
    "direct_alpha": lambda a: N.direct_alpha(a["c"], a["d"], a["index"], a["nav"]),
    "pme_plus_lambda": lambda a: N.pme_plus_lambda(a["c"], a["d"], a["index"], a["nav"]),
    # pack IC - information criteria / model selection
    "log_likelihood_gaussian": lambda a: N.log_likelihood_gaussian(a["resid"]),
    "aic": lambda a: N.aic(a["resid"], a["k"]),
    "bic": lambda a: N.bic(a["resid"], a["k"]),
    "aicc": lambda a: N.aicc(a["resid"], a["k"]),
    "hqic": lambda a: N.hqic(a["resid"], a["k"]),
    # pack INE - inequality / concentration depth
    "hoover_index": lambda a: N.hoover_index(a["xs"]),
    "mean_log_deviation": lambda a: N.mean_log_deviation(a["xs"]),
    "generalized_entropy_index": lambda a: N.generalized_entropy_index(a["xs"], a["alpha"]),
    "percentile_ratio": lambda a: N.percentile_ratio(a["xs"]),
    # pack EF - effect-size depth
    "glass_delta": lambda a: N.glass_delta(a["a"], a["b"]),
    "hedges_g": lambda a: N.hedges_g(a["a"], a["b"]),
    "common_language_effect_size": lambda a: N.common_language_effect_size(a["a"], a["b"]),
    "cohens_h": lambda a: N.cohens_h(a["a"], a["b"]),
    # pack VOL - range-based volatility estimators
    "parkinson_volatility": lambda a: N.parkinson_volatility(a["high"], a["low"]),
    "garman_klass_volatility": lambda a: N.garman_klass_volatility(a["open"], a["high"], a["low"], a["close"]),
    "rogers_satchell_volatility": lambda a: N.rogers_satchell_volatility(a["open"], a["high"], a["low"], a["close"]),
    "yang_zhang_volatility": lambda a: N.yang_zhang_volatility(a["open"], a["high"], a["low"], a["close"]),
    # pack RGD - regression / GLM deviance depth
    "mean_squared_error": lambda a: N.mean_squared_error(a["pred"], a["actual"]),
    "rmsle": lambda a: N.msle(a["pred"], a["actual"], True),
    "mean_tweedie_deviance": lambda a: N.mean_tweedie_deviance(a["pred"], a["actual"], a["power"]),
    "d2_tweedie_score": lambda a: N.d2_tweedie_score(a["pred"], a["actual"], a["power"]),
    # pack FCI - prediction-interval / probabilistic-forecast eval
    "interval_coverage": lambda a: N.interval_coverage(a["lower"], a["upper"], a["actual"]),
    "mean_interval_width": lambda a: N.mean_interval_width(a["lower"], a["upper"]),
    "winkler_score": lambda a: N.winkler_score(a["lower"], a["upper"], a["actual"], a["alpha"]),
    "coverage_deviation": lambda a: N.coverage_deviation(a["lower"], a["upper"], a["actual"], a["alpha"]),
    # pack AG - inter-rater agreement coefficients
    "percentage_agreement": lambda a: N.percentage_agreement(a["ra"], a["rb"]),
    "scott_pi": lambda a: N.scott_pi(a["ra"], a["rb"]),
    "brennan_prediger": lambda a: N.brennan_prediger(a["ra"], a["rb"]),
    "gwet_ac1": lambda a: N.gwet_ac1(a["ra"], a["rb"]),
    # pack CO - correlation / dependence depth
    "distance_correlation": lambda a: N.distance_correlation(a["x"], a["y"]),
    "somers_d": lambda a: N.somers_d(a["x"], a["y"]),
    "goodman_kruskal_gamma": lambda a: N.goodman_kruskal_gamma(a["x"], a["y"]),
    # pack RNK - ranking / IR depth
    "err_at_k": lambda a: N.err_at_k(a["queries"], a["ranks"], a["rels"], a["k"]),
    "success_at_k": lambda a: N.success_at_k(a["queries"], a["ranks"], a["rels"], a["k"]),
    "arhr_at_k": lambda a: N.arhr_at_k(a["queries"], a["ranks"], a["rels"], a["k"]),
    # pack SH - robust distribution shape
    "bowley_skewness": lambda a: N.bowley_skewness(a["xs"]),
    "moors_kurtosis": lambda a: N.moors_kurtosis(a["xs"]),
    "l_skewness": lambda a: N.l_skewness(a["xs"]),
    "l_kurtosis": lambda a: N.l_kurtosis(a["xs"]),
}

doc = json.load(open(VECTORS))
seen_kinds = set()
for case in doc["cases"]:
    seen_kinds.add(case["kind"])
    got = KINDS[case["kind"]](case["args"])
    approx(got, case["expected"], case["atol"], case["rtol"], "ref:" + case["id"])
truth(set(KINDS) == seen_kinds, "every dispatch kind exercised by the vector file")
truth(len(doc["cases"]) >= 290, "reference corpus is full-size (%d cases)" % len(doc["cases"]))

# ---------------- part B: registry completeness + manifest sanity ----------------

EXPECTED = {
    # the original 15
    "total_return", "sharpe", "max_drawdown", "accuracy", "auc", "precision", "recall", "f1",
    "brier", "rmse", "mae", "r2", "column_sum", "column_mean", "row_count",
    # pack 1
    "speedup_ratio", "latency_p50", "latency_p95", "latency_p99", "throughput", "peak_memory",
    "test_coverage", "error_rate",
    # pack 2
    "column_median", "percentile", "groupby_aggregate", "distinct_count", "growth_rate",
    "ratio_share", "null_fraction", "duplicate_count", "join_row_loss",
    # pack 3
    "recall_at_k", "ndcg_at_k", "mrr", "exact_match", "pass_at_k", "top_k_accuracy",
    "macro_f1", "micro_f1", "pr_auc", "log_loss", "mcc", "ece",
    # pack 4
    "p_value", "confidence_interval", "lift", "chi_square", "correlation", "effect_size",
    # pack 5
    "cagr", "npv", "irr", "churn_rate", "margin_pct", "reconciliation_total",
    # pack 6
    "mape", "mase", "pinball_loss",
    # pack 7 - quant risk & relative performance
    "volatility", "downside_deviation", "sortino", "calmar", "value_at_risk", "cvar",
    "win_rate", "profit_factor", "omega_ratio", "beta", "alpha", "information_ratio",
    "tracking_error",
    # pack 8 - classification & regression depth II
    "balanced_accuracy", "cohen_kappa", "specificity", "fbeta", "jaccard", "weighted_f1",
    "ks_statistic", "gini_norm", "msle", "medae", "max_error", "explained_variance",
    "wape", "forecast_bias", "adjusted_r2", "nrmse", "durbin_watson",
    # pack 9 - analytics & engineering depth II
    "column_min", "column_max", "column_std", "iqr", "outlier_count", "mode_share",
    "gini_coefficient", "hhi", "entropy", "latency_p90", "apdex", "uptime_pct",
    "cache_hit_rate",
    # pack 10 - statistical tests II
    "mann_whitney", "ks_test", "anova", "proportion_z", "fisher_exact", "odds_ratio",
    "relative_risk", "cramers_v", "skewness", "kurtosis", "jarque_bera", "autocorrelation",
    # pack 11 - retrieval / LLM evals II
    "precision_at_k", "map_at_k", "perplexity", "wer",
    # pack QR - quant-risk depth (25)
    "ulcer_index", "pain_index", "martin_ratio", "recovery_factor", "gain_to_pain_ratio",
    "tail_ratio", "gain_loss_ratio", "win_loss_ratio", "kelly_criterion", "upside_deviation",
    "upside_potential_ratio", "kappa_three", "cdar", "max_drawdown_duration", "parametric_var",
    "parametric_es", "cornish_fisher_var", "adjusted_sharpe_ratio", "probabilistic_sharpe_ratio",
    "up_capture_ratio", "down_capture_ratio", "capture_ratio", "treynor_ratio", "r_squared",
    "active_return",
    # pack ST - statistics & hypothesis tests (8)
    "point_biserial", "kendall_tau", "theil_sen_slope", "cliffs_delta", "rank_biserial",
    "eta_squared", "g_test", "mcnemar",
    # pack ST2 - variance / distribution / nonparametric + CIs + multiplicity (10)
    "levene", "bartlett", "fligner", "kruskal_wallis", "wilcoxon_signed_rank",
    "anderson_darling", "wilson_lower", "wilson_upper", "bh_rejections", "holm_rejections",
    # pack RM - risk-model validation (10)
    "kupiec_pof", "christoffersen_independence", "christoffersen_cc", "psi", "information_value",
    "kl_divergence", "js_divergence", "wasserstein_1d", "energy_distance", "ks_2samp",
    # pack CR - classification & regression depth (17)
    "g_mean", "youden_j", "markedness", "negative_predictive_value", "false_positive_rate", "false_negative_rate",
    "false_discovery_rate", "positive_likelihood_ratio", "negative_likelihood_ratio",
    "diagnostic_odds_ratio", "threat_score", "fowlkes_mallows", "concordance_correlation",
    "huber_loss", "poisson_deviance", "gamma_deviance", "d2_absolute_error",
    # pack AN - analytics / data-quality / robust-stats depth (15)
    "variance", "range_value", "mean_abs_deviation", "median_abs_deviation", "trimmed_mean",
    "geometric_mean", "harmonic_mean", "weighted_mean", "covariance", "theil_index",
    "atkinson_index", "quartile_coefficient_dispersion", "index_of_dispersion", "uniqueness_ratio",
    "ljung_box",
    # pack TS - forecasting / time-series accuracy (9)
    "theil_u1", "theil_u2", "rmsse", "tracking_signal", "mean_directional_accuracy",
    "relative_absolute_error", "relative_squared_error", "mean_percentage_error",
    "median_absolute_percentage_error",
    # pack FAIR - fairness / bias (8)
    "demographic_parity_difference", "demographic_parity_ratio", "equalized_odds_difference",
    "equalized_odds_ratio", "equal_opportunity_difference", "predictive_parity_difference",
    "fpr_parity_difference", "accuracy_parity_difference",
    # pack BC - survival concordance + clustering agreement (9)
    "concordance_index", "mutual_info_score", "normalized_mutual_info", "homogeneity_score",
    "completeness_score", "v_measure_score", "rand_index", "adjusted_rand_index",
    "fowlkes_mallows_clustering",
    # pack ENG - performance / SRE depth (10)
    "latency_p75", "latency_p999", "tail_latency_ratio", "latency_stddev", "jitter",
    "slo_attainment", "error_budget_burn", "compression_ratio", "availability", "mtbf",
    # pack QR2 - quant performance depth (10)
    "pain_ratio", "sterling_ratio", "burke_ratio", "m2_measure", "appraisal_ratio",
    "common_sense_ratio", "rachev_ratio", "downside_potential", "upside_potential",
    "omega_sharpe_ratio",
    # pack EXP - causal / experimentation (8)
    "average_treatment_effect", "risk_difference", "relative_risk_reduction",
    "number_needed_to_treat", "standardized_mean_difference", "cuped_ate",
    "variance_reduction_cuped", "srm_pvalue",
    # pack IR - retrieval / ranking + token-overlap (8)
    "r_precision", "mean_average_precision", "f1_at_k", "fallout_at_k", "rbp",
    "token_f1", "token_jaccard", "token_dice",
    # pack FI - fixed income (7)
    "bond_price", "macaulay_duration", "modified_duration", "convexity", "dv01",
    "weighted_average_life", "yield_to_maturity",
    # pack OPT - Black-Scholes options & Greeks (9)
    "bs_value", "bs_delta", "bs_gamma", "bs_vega", "bs_theta",
    "bs_rho", "bs_vanna", "bs_volga", "bs_implied_vol",
    # pack ES - expected-shortfall / VaR backtesting (7)
    "var_breach_rate", "realized_shortfall", "expected_exceedance", "basel_traffic_light",
    "es_backtest_ratio", "acerbi_szekely_z1", "acerbi_szekely_z2",
    # pack CR - credit / default risk (8)
    "expected_loss", "expected_loss_rate", "weighted_lgd", "unexpected_loss",
    "altman_z", "altman_z_prime", "merton_distance_to_default", "merton_pd",
    # pack PA - portfolio construction & attribution (7)
    "brinson_allocation", "brinson_selection", "brinson_interaction", "brinson_total_active",
    "active_share", "portfolio_turnover", "effective_number_of_bets",
    # pack RC - rates / curve analytics (6)
    "par_yield", "annuity_factor", "forward_rate", "curve_pv",
    "effective_duration", "effective_convexity",
    # pack FM - fund / LP economics (6)
    "dpi", "rvpi", "tvpi", "called_pct", "carried_interest", "realization_ratio",
    # pack LQ - liquidity / microstructure (6)
    "amihud_illiquidity", "amivest_liquidity", "roll_spread", "kyle_lambda",
    "vwap", "relative_spread",
    # pack AB - multiple-testing corrections (5)
    "bonferroni_rejections", "sidak_rejections", "holm_sidak_rejections",
    "hochberg_rejections", "benjamini_yekutieli",
    # pack TS - time-series / return diagnostics (3)
    "variance_ratio", "runs_test", "arch_lm",
    # pack OPS - exposure, leverage & ODD metrics (7)
    "gross_exposure", "net_exposure", "long_exposure", "short_exposure",
    "long_short_ratio", "largest_position", "liquidity_coverage",
    # pack FX - single-factor market-model risk (6)
    "idiosyncratic_volatility", "alpha_tstat", "beta_tstat",
    "bull_beta", "bear_beta", "up_down_beta_ratio",
    # pack AR - credit-quality / covenant ratios (7)
    "current_ratio", "quick_ratio", "interest_coverage", "debt_to_equity",
    "debt_to_ebitda", "net_debt_to_ebitda", "ebitda_margin",
    # pack CAL - probability-calibration depth (7)
    "maximum_calibration_error", "brier_reliability", "brier_resolution",
    "brier_skill_score", "calibration_in_the_large", "spiegelhalter_z", "sharpness",
    # pack DIST - distribution-distance depth (5)
    "hellinger_distance", "total_variation_distance", "bhattacharyya_distance",
    "jeffreys_divergence", "chi_square_distance",
    # pack SV - survival / time-to-event (4)
    "km_median_survival", "km_survival_at", "nelson_aalen_cumhaz",
    "restricted_mean_survival_time",
    # pack TX - transaction-cost analysis (5)
    "implementation_shortfall", "arrival_slippage", "vwap_slippage",
    "effective_spread_bps", "participation_rate",
    # pack PME - private-market benchmarking (3)
    "ks_pme", "direct_alpha", "pme_plus_lambda",
    # pack IC - information criteria / model selection (5)
    "log_likelihood_gaussian", "aic", "bic", "aicc", "hqic",
    # pack INE - inequality / concentration depth (4)
    "hoover_index", "mean_log_deviation", "generalized_entropy_index", "percentile_ratio",
    # pack EF - effect-size depth (4)
    "glass_delta", "hedges_g", "common_language_effect_size", "cohens_h",
    # pack VOL - range-based volatility estimators (4)
    "parkinson_volatility", "garman_klass_volatility",
    "rogers_satchell_volatility", "yang_zhang_volatility",
    # pack RGD - regression / GLM deviance depth (4)
    "mean_squared_error", "rmsle", "mean_tweedie_deviance", "d2_tweedie_score",
    # pack FCI - prediction-interval / probabilistic-forecast eval (4)
    "interval_coverage", "mean_interval_width", "winkler_score", "coverage_deviation",
    # pack AG - inter-rater agreement coefficients (4)
    "percentage_agreement", "scott_pi", "brennan_prediger", "gwet_ac1",
    # pack CO - correlation / dependence depth (3)
    "distance_correlation", "somers_d", "goodman_kruskal_gamma",
    # pack RNK - ranking / IR depth (3)
    "err_at_k", "success_at_k", "arhr_at_k",
    # pack SH - robust distribution shape (4)
    "bowley_skewness", "moors_kurtosis", "l_skewness", "l_kurtosis",
}
_reviewed = {m for m in R.ids() if R.get(m).manifest.get("set_maturity") != "compiled-validated"}
_compiled = set(R.ids()) - _reviewed
truth(_reviewed == EXPECTED, "registry holds exactly the 412 reviewed recipes (got %d)" % len(_reviewed))
# compiled recipes are admitted-by-gate only: maturity tag + frozen program hash re-validates
import dsl as _dsl  # noqa: E402
import json as _json  # noqa: E402
_compiled_path = os.path.join(HERE, "..", "..", "assets", "compiled_recipes.json")
_book = {r["metric_id"]: r for r in (_json.load(open(_compiled_path))["recipes"]
                                     if os.path.exists(_compiled_path) else [])}
truth(_compiled == set(_book), "every compiled registration comes from compiled_recipes.json")
for mid in sorted(_compiled):
    fn = R.get(mid)
    truth(fn.manifest.get("set_maturity") == "compiled-validated",
          "compiled recipe %s carries the compiled-validated maturity" % mid)
    truth(_dsl.program_hash(_book[mid]["program"]) == _book[mid]["program_sha256"]
          and not _dsl.validate(_book[mid]["program"]),
          "compiled recipe %s: frozen program re-hashes and re-validates" % mid)
for mid in R.ids():
    fn = R.get(mid)
    truth(isinstance(fn.manifest.get("family"), str) and fn.manifest.get("required_tags") is not None,
          "manifest complete: %s" % mid)
    stags = set(fn.manifest.get("string_tags") or [])
    truth(stags <= set(fn.manifest.get("required_tags") or []), "string_tags subset of required: %s" % mid)

# ---------------- part C: recipe layer - conventions, degenerate paths, bit-stability ----------------

res = R.get("percentile")({"v": [1.0, 2.0, 3.0, 4.0]}, {"value": "v"}, "p75")
approx(res["value"], 3.25, 1e-12, 0, "percentile recipe p75")
truth(R.get("percentile")({"v": [1.0, 2.0]}, {"value": "v"}, None)["degenerate"],
      "percentile without a quantile convention degrades to degenerate")
approx(R.get("percentile")({"v": [1.0, 2.0, 3.0, 4.0]}, {"value": "v"}, "q=0.75")["value"],
       3.25, 1e-12, 0, "percentile q=0.75 spelling")

rq = {"q": ["a", "a", "b", "b"], "r": [1.0, 2.0, 1.0, 2.0], "rel": [0.0, 1.0, 1.0, 0.0]}
res = R.get("recall_at_k")(rq, {"query": "q", "rank": "r", "relevance": "rel"}, "k=1")
approx(res["value"], 0.5, 1e-12, 0, "recall_at_k k=1 hand case")
res = R.get("ndcg_at_k")(rq, {"query": "q", "rank": "r", "relevance": "rel"}, "k=2,exp")
truth(res["terms"]["gain"] == "exp" and res["terms"]["k"] == 2, "ndcg convention 'k=2,exp' parsed")
res = R.get("ece")({"p": [0.9, 0.1], "y": [1.0, 0.0]}, {"prob": "p", "label": "y"}, "bins=10")
approx(res["value"], 0.1, 1e-12, 0, "ece bins=10 hand case")  # both bins: |acc-conf| = .1
res = R.get("confidence_interval")({"v": [1.0, 2.0, 3.0, 4.0]}, {"value": "v"}, "z95")
truth(res["terms"]["dist"] == "z" and res["terms"]["level"] == 0.95, "ci convention 'z95' parsed")
res = R.get("chi_square")({"g": ["a", "a", "b", "b"], "o": ["x", "y", "x", "y"]},
                          {"group": "g", "outcome": "o"}, "statistic-no-yates")
truth(res["terms"]["output"] == "statistic" and not res["terms"]["yates"], "chi2 convention parsed")
res = R.get("pass_at_k")({"p": ["t1"] * 4, "c": [1.0, 0.0, 0.0, 0.0]}, {"problem": "p", "correct": "c"}, "k=2")
approx(res["value"], 1.0 - (3 * 2) / (4 * 3), 1e-12, 0, "pass@2 n=4 c=1 exact combinatorics")
truth(R.get("pass_at_k")({"p": ["t1"] * 2, "c": [1.0, 0.0]}, {"problem": "p", "correct": "c"},
                         "k=5")["degenerate"], "pass@k with k > n is degenerate, never silently valid")

# exact_match: strict vs SQuAD-normalized
em_cols = {"p": ["The Cat", "dog!", "x"], "r": ["cat", "a dog", "y"]}
approx(R.get("exact_match")(em_cols, {"prediction": "p", "reference": "r"}, None)["value"],
       0.0, 0, 0, "exact_match strict")
approx(R.get("exact_match")(em_cols, {"prediction": "p", "reference": "r"}, "normalized")["value"],
       2.0 / 3.0, 1e-12, 0, "exact_match normalized (case/punct/articles)")

# groupby: no label -> degenerate (no scalar to compare), per-group kept in terms
res = R.get("groupby_aggregate")({"g": ["w", "e"], "v": [1.0, 2.0]}, {"group": "g", "value": "v"}, "sum")
truth(res["degenerate"] and res["terms"]["groups"] == {"w": 1.0, "e": 2.0},
      "groupby without group label is degenerate with per-group terms")
approx(R.get("groupby_aggregate")({"g": ["w", "e", "w"], "v": [1.0, 2.0, 4.0]},
                                  {"group": "g", "value": "v"}, "sum:w")["value"],
       5.0, 0, 0, "groupby sum:w")

# log_loss exact vs clip on a wrong-side hard zero
ll = {"p": [0.0, 0.9], "y": [1.0, 1.0]}
truth(R.get("log_loss")(ll, {"prob": "p", "label": "y"}, None)["degenerate"],
      "log_loss exact mode: p=0 on a positive -> degenerate (inf), never a quiet number")
truth(not R.get("log_loss")(ll, {"prob": "p", "label": "y"}, "clip")["degenerate"],
      "log_loss clip mode stays finite")

# pack 5/6 recipe layer: conventions + degenerate paths
truth(R.get("npv")({"cf": [-100.0, 60.0, 60.0]}, {"cashflow": "cf"}, None)["degenerate"],
      "npv without a rate convention degrades to degenerate")
res = R.get("npv")({"cf": [-100.0, 60.0, 60.0]}, {"cashflow": "cf"}, "rate=0.0")
approx(res["value"], 20.0, 1e-12, 0, "npv rate=0 = plain sum")
truth(isnan(N.irr([100.0, 50.0])), "irr with no sign change -> nan")
r_irr = N.irr([-1000.0, 1100.0])
approx(r_irr, 0.1, 1e-10, 0, "irr single-period hand case = 10%")
truth(isnan(N.mape([1.0, 2.0], [0.0, 2.0])), "mape with a zero actual -> nan, never an epsilon fudge")
res = R.get("pinball_loss")({"p": [1.0, 3.0], "t": [2.0, 2.0]}, {"prediction": "p", "target": "t"}, None)
approx(res["value"], 0.5, 1e-12, 0, "pinball default q=0.5 hand case")
res = R.get("cagr")({"v": [100.0, 121.0]}, {"value": "v"}, None)
approx(res["value"], 0.21, 1e-12, 0, "cagr 1 period annual = simple growth")
res = R.get("churn_rate")({"f": [1.0, 0.0, 0.0, 0.0]}, {"flag": "f"}, "retention")
approx(res["value"], 0.75, 1e-12, 0, "churn_rate retention convention")
truth(isnan(N.mase([1.0, 2.0], [5.0, 5.0], 1)), "mase on a flat series -> nan (zero scale)")
truth(isnan(N.margin_pct([0.0, 0.0], [1.0])), "margin with zero revenue -> nan")

# NaN propagation across the new families
nan = float("nan")
truth(isnan(N.quantile([1.0, nan], 0.5)), "quantile NaN -> nan")
truth(isnan(N.t_test_p([1.0, nan, 2.0], [1.0, 2.0, 3.0])), "t_test NaN -> nan")
truth(isnan(N.speedup_ratio([1.0], [nan])), "speedup NaN -> nan")
truth(isnan(N.ece([nan], [1], 15)), "ece NaN -> nan")
truth(isnan(N.pearson_r([1.0, 2.0], [nan, 1.0])), "pearson NaN -> nan")
truth(isnan(N.growth_rate([100.0], "period")), "growth_rate n<2 -> nan")
truth(isnan(N.lift([0.0, 0.0], [1.0]) ), "lift zero control mean -> nan")
truth(isnan(N.chi_square(["a", "a"], ["x", "y"])), "chi2 single group -> nan")
truth(N.mcc([1.0, 1.0], [1.0, 1.0]) == 0.0, "mcc degenerate marginals -> 0.0 (sklearn)")

# bit-stability of transcendental-bearing recipes
truth(N.t_test_p([1.0, 2.0, 3.5], [2.0, 4.0, 4.5]) == N.t_test_p([1.0, 2.0, 3.5], [2.0, 4.0, 4.5]),
      "p_value bit-stable across calls")
nd = lambda: N.ndcg_at_k(["a", "a", "a"], [1.0, 2.0, 3.0], [3.0, 1.0, 2.0], 3, "exp")
truth(nd() == nd(), "ndcg bit-stable across calls")
truth(N.dlog(7.3) == N.dlog(7.3) and N.dexp(-3.2) == N.dexp(-3.2), "kernels bit-stable")

# ---------------- part D: pipeline e2e - string tags, cross-artifact binding, na drop ----------------

with tempfile.TemporaryDirectory() as td:
    def write_csv(name, header, rows):
        with open(os.path.join(td, name), "w", newline="") as fh:
            w = csv.writer(fh)
            w.writerow(header)
            w.writerows(rows)

    write_csv("timings.csv", ["before_ms", "after_ms"],
              [[100.0, 42.0], [110.0, 44.0], [105.0, 40.0], [98.0, 41.0]])
    write_csv("left.csv", ["id"], [[i] for i in range(120)])
    write_csv("merged.csv", ["id"], [[i] for i in range(117)])
    write_csv("ratings.csv", ["query", "rank", "relevance"],
              [["q1", 1, 1], ["q1", 2, 0], ["q1", 3, 1], ["q2", 1, 0], ["q2", 2, 1]])
    write_csv("ab.csv", ["control", "treatment"],
              [[10.1, 11.2], [10.4, 11.9], [9.8, 11.1], [10.0, 12.0], ["", 11.5]])
    contract = {
        "run": {"entrypoint": "MANUAL", "network": "off", "cwd": "."},
        "artifacts": [
            {"path": "timings.csv", "columns": {"before_ms": {"tag": "before", "na_policy": "error"},
                                                "after_ms": {"tag": "after", "na_policy": "error"}}},
            {"path": "merged.csv", "columns": {"id": {"tag": "joined_key", "na_policy": "error"}}},
            {"path": "left.csv", "columns": {"id": {"tag": "left_key", "na_policy": "error"}}},
            {"path": "ratings.csv", "columns": {"query": {"tag": "query", "na_policy": "error"},
                                                "rank": {"tag": "rank", "na_policy": "error"},
                                                "relevance": {"tag": "relevance", "na_policy": "error"}}},
            {"path": "ab.csv", "columns": {"control": {"tag": "sample_a", "na_policy": "drop"},
                                           "treatment": {"tag": "sample_b", "na_policy": "drop"}}},
        ],
        "metrics": [
            {"metric_id": "speedup_ratio", "artifact": "timings.csv",
             "binding": {"before": "before_ms", "after": "after_ms"}, "convention": "mean",
             "claimed_value": 2.47, "headline": True, "binding_status": "independently-bound",
             "claim_confirmed": True},
            {"metric_id": "join_row_loss", "artifact": "merged.csv",
             "binding": {"left_key": "left.csv::id", "joined_key": "id"}, "convention": None,
             "claimed_value": 0.0, "headline": True, "binding_status": "independently-bound",
             "claim_confirmed": True},
            {"metric_id": "recall_at_k", "artifact": "ratings.csv",
             "binding": {"query": "query", "rank": "rank", "relevance": "relevance"},
             "convention": "k=1", "claimed_value": 0.25, "headline": False,
             "binding_status": "independently-bound", "claim_confirmed": True},
            {"metric_id": "p_value", "artifact": "ab.csv",
             "binding": {"sample_a": "control", "sample_b": "treatment"}, "convention": "welch",
             "claimed_value": None, "headline": False, "binding_status": "independently-bound",
             "claim_confirmed": False},
        ],
        "baselines": [],
    }
    cpath = os.path.join(td, "verify.yaml")
    json.dump(contract, open(cpath, "w"))
    rec = RC.recompute_contract(cpath, td, k=2)
    by_id = {m["metric_id"]: m for m in rec["metrics"]}
    approx(by_id["speedup_ratio"]["value"], (100 + 110 + 105 + 98) / (42.0 + 44 + 40 + 41),
           1e-12, 0, "e2e speedup from csv")
    approx(by_id["join_row_loss"]["value"], 3.0, 0, 0, "e2e cross-artifact join_row_loss = 3 rows lost")
    approx(by_id["recall_at_k"]["value"], 0.25, 1e-12, 0, "e2e recall@1 with string query column")
    truth(not isnan(by_id["p_value"]["value"]) and 0.0 < by_id["p_value"]["value"] < 0.05,
          "e2e welch p on na_policy=drop unequal columns is finite and small")
    truth(all(m["k_spread"] == 0.0 for m in rec["metrics"]), "e2e deterministic: zero k-spread")
    diff = C.compare(rec, contract)
    verd = {m["metric_id"]: m["verdict"] for m in diff["metrics"]}
    truth(verd["speedup_ratio"] == "CONFIRMED",
          "e2e speedup 2.47 claim CONFIRMED within reported precision (got %s)" % verd["speedup_ratio"])
    truth(verd["join_row_loss"] == "REFUTED",
          "e2e 'merged without losing rows' vs 3 lost rows -> REFUTED (got %s)" % verd["join_row_loss"])
    truth(verd["recall_at_k"] == "CONFIRMED",
          "e2e recall@1 claim CONFIRMED (got %s)" % verd["recall_at_k"])
    truth(verd["p_value"] == "INCONCLUSIVE",
          "e2e numberless p_value claim -> INCONCLUSIVE (got %s)" % verd["p_value"])

# ---------------- part E: claim parsing regressions for the new metric families ----------------

for claim, want_v, want_hint in [
    ("f1 0.84", 0.84, "f1"), ("top-5 accuracy 0.91", 0.91, "top_k_accuracy"),
    ("recall@10 = 0.84", 0.84, "recall_at_k"), ("p95 latency 120ms", 120.0, "latency_p95"),
    ("chi2 = 5.99", 5.99, "chi_square"), ("pass@1 0.47", 0.47, "pass_at_k"),
    ("2.3x faster", 2.3, "speedup_ratio"), ("up 23% MoM", 0.23, "growth_rate"),
    ("ndcg@10 0.71", 0.71, "ndcg_at_k"), ("test coverage 87%", 0.87, "test_coverage"),
    ("average precision 0.62", 0.62, "pr_auc"), ("macro f1 0.55", 0.55, "macro_f1"),
    ("the lift was 12%", 0.12, "lift"), ("spearman correlation 0.8", 0.8, "correlation"),
    ("median 42", 42.0, "column_median"), ("12,402 distinct users", 12402.0, "distinct_count"),
    ("null fraction 0.02", 0.02, "null_fraction"), ("throughput 4,200 rps", 4200.0, "throughput"),
    ("p-value 0.003", 0.003, "p_value"), ("effect size 0.4", 0.4, "effect_size"),
]:
    v, hint = D.parse_claim(claim)
    truth(v == want_v and hint == want_hint,
          "claim %r -> (%r, %s) want (%r, %s)" % (claim, v, hint, want_v, want_hint))

# ---------------- part F: convention inference from claim text + percent-precision fix ----------------

for claim, mid, want_conv in [
    ("pass@5 0.62", "pass_at_k", "k=5"), ("recall@20 was 0.91", "recall_at_k", "k=20"),
    ("ndcg@5 0.7 with exp gains", "ndcg_at_k", "k=5,exp"), ("monthly CAGR 23.87%", "cagr", "periods=12"),
    ("NPV $310 at 8%", "npv", "rate=0.08"), ("spearman correlation 0.8", "correlation", "spearman"),
    ("99% confidence interval 0.4", "confidence_interval", "t99"), ("5xx error rate 0.3%", "error_rate", "http5xx"),
    ("92% retention", "churn_rate", "retention"), ("sMAPE 11%", "mape", "smape"),
    ("90th percentile 120", "percentile", "p90"), ("p99.9 latency 480ms", "percentile", "p99.9"),
    ("accuracy 0.87", "accuracy", None),
]:
    _, hint = D.parse_claim(claim)
    got = D.infer_convention(claim, mid)
    truth(hint == mid and got == want_conv,
          "convention %r -> (%s, %s) want (%s, %s)" % (claim, hint, got, mid, want_conv))

# percent-scaled claims must keep their REPORTED precision ('23.87%' -> 0.2387 +/- 5e-5,
# despite repr(23.87/100) carrying float artifacts)
truth(abs(C._infer_precision(23.87 / 100.0) - 5e-5) < 1e-18,
      "percent claim precision survives the /100 float artifact")
truth(C._infer_precision(0.42) == 0.005, "plain decimal precision unchanged")
truth(C._infer_precision(120.0) == 0.5, "integer claim precision unchanged")
truth(C._infer_precision(0.123456789012345) <= 5e-13, "genuinely long claims keep a tight budget")

# claim_precision: the suffix scale is part of the REPORTED precision ('$4.2M' is +/-50k, not +/-0.5)
truth(D.claim_precision("$4.2M revenue") == 50000.0, "claim_precision $4.2M -> 50k")
truth(abs(D.claim_precision("23.87%") - 5e-5) < 1e-18, "claim_precision 23.87%% -> 5e-5")
truth(D.claim_precision("processed 10,000 rows") == 0.5, "claim_precision integer -> 0.5")
truth(D.claim_precision("accuracy 0.87") == 0.005, "claim_precision 0.87 -> 0.005")
truth(D.claim_precision("no number here") is None, "claim_precision without a number -> None")

# ---------------- part G: audit fixes - tag aliases + degenerate (not crashed) bad bindings ----------------

with tempfile.TemporaryDirectory() as td2:
    with open(os.path.join(td2, "preds.csv"), "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["y_true", "y_pred", "prob"])
        for y, p, pr in [(1, 1, 0.9), (0, 0, 0.2), (1, 0, 0.4), (0, 0, 0.1)]:
            w.writerow([y, p, pr])
    # named metrics bind through aliases: log_loss needs `prob` (column tags as `score`),
    # rmse needs `target` (column y_true tags as `label`)
    c_ll = D.draft(td2, claim="log loss 0.3")
    truth(c_ll["metrics"] and c_ll["metrics"][0]["metric_id"] == "log_loss"
          and c_ll["metrics"][0]["binding"].get("prob") == "prob",
          "named log_loss claim binds the probability column via the score->prob alias")
    c_rmse = D.draft(td2, claim="rmse 0.5")
    truth(c_rmse["metrics"] and c_rmse["metrics"][0]["binding"].get("target") == "y_true",
          "named rmse claim binds y_true via the label->target alias")
    # auto-pick (no named metric) keeps the strict table: y_true/y_pred -> accuracy, never rmse
    c_auto = D.draft(td2, claim="0.75")
    truth(c_auto["metrics"] and c_auto["metrics"][0]["metric_id"] == "auc",
          "auto-pick unchanged by aliases (score+label -> auc), got %s"
          % (c_auto["metrics"][0]["metric_id"] if c_auto["metrics"] else None))

    # a contract binding a MISSING column degrades to a degenerate recompute, never a traceback
    bad = {"run": {"entrypoint": "MANUAL"}, "artifacts": [{"path": "preds.csv", "columns": {}}],
           "metrics": [{"metric_id": "accuracy", "artifact": "preds.csv",
                        "binding": {"prediction": "no_such_col", "label": "y_true"},
                        "convention": None, "claimed_value": 0.9, "headline": True,
                        "binding_status": "independently-bound", "claim_confirmed": True}],
           "baselines": []}
    bp = os.path.join(td2, "verify.yaml")
    json.dump(bad, open(bp, "w"))
    rec_bad = RC.recompute_contract(bp, td2)
    truth(rec_bad["metrics"][0]["degenerate"] and "binding failed" in rec_bad["metrics"][0]["error"],
          "missing column -> degenerate recompute with a named error")
    diff_bad = C.compare(rec_bad, bad)
    truth(diff_bad["metrics"][0]["verdict"] == "INCONCLUSIVE",
          "missing column -> INCONCLUSIVE, never a crash or a verdict")
    # a non-numeric cell in a numeric column likewise degrades
    with open(os.path.join(td2, "dirty.csv"), "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["value"])
        w.writerow([3.0])
        w.writerow(["oops-text"])
    dirty = {"run": {"entrypoint": "MANUAL"}, "artifacts": [{"path": "dirty.csv", "columns": {}}],
             "metrics": [{"metric_id": "column_sum", "artifact": "dirty.csv",
                          "binding": {"value": "value"}, "convention": None, "claimed_value": 3.0,
                          "headline": True, "binding_status": "independently-bound",
                          "claim_confirmed": True}], "baselines": []}
    dp = os.path.join(td2, "verify2.yaml")
    json.dump(dirty, open(dp, "w"))
    rec_dirty = RC.recompute_contract(dp, td2)
    truth(rec_dirty["metrics"][0]["degenerate"], "non-numeric cell -> degenerate, not a traceback")

# ---------------- part H: the site's recipe catalog stays in sync with the registry ----------------

_site_data = os.path.join(HERE, "..", "..", "..", "..", "..", "app", "recipes", "data.ts")
if os.path.exists(_site_data):
    import re as _re
    _ids = set(_re.findall(r'id:\s*"([a-z0-9_]+)"', open(_site_data).read()))
    truth(_ids == set(R.ids()),
          "app/recipes/data.ts mirrors the registry (site-only: %s; registry-only: %s)"
          % (sorted(_ids - set(R.ids())), sorted(set(R.ids()) - _ids)))

print("recipes-sota: %d checks, %d failures" % (_n, _fail))
sys.exit(1 if _fail else 0)
